### ISSUE TITLE
No PMIX_EVENT_JOB_END event for debug daemon when attach to prterun

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#1004]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Built from current PRRTE master

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Built from current PMIx master

### Please describe the system on which you are running

* Operating system/version:
RHEL 7.6

* Computer hardware:
Single Power 9 node

* Network type:
Localhost

-----------------------------

## Details of the problem
The current PRRTE debugger example hangs when attaching to a running prterun process which I start as follows

~~~
prterun -n 2 --report-uri + ./hello 60
attach <prterun_namespace>
~~~

The hang is waiting for notification of either a PMIX_ERR_LOST_CONNECTION or PMIX_EVENT_JOB_END event for the debugger daemon launched by the attach program.

I modified the example to debug it, source at https://gist.github.com/drwootton/49d9b9b06a8f34bdfff4f97bc9346833

The current example code tries to filter for these events by setting the PMIX_EVENT_AFFECTED_PROC attribute to the proc for the debug daemon when registering for these events.

I modified the example to comment out setting that attribute (line 455) and attach no longer hangs, but it is not getting notification of either of these events from the debugger daemon. It does get two PMIX_EVENT_JOB_END events from the application.

I turned on the PMIx event client and server traces and it looks like I see the same thing in those traces.

I did try running with three application tasks thinking it had something to do with number of application tasks but still got two events.

I'm not sure if I am doing something wrong here. The attach program does run successfully if I run it as a multi-node colaunch case.

**Comment by rhc54** [comment]
Not doing anything wrong, but as I said earlier, PRRTE currently does not monitor debugger daemons and therefore does not generate a "job_end" event when they terminate. It'll take a bit to modify the code to add monitoring of debugger daemons. I can take a look at it after completing the current priority list.

**Comment by drwootton** [comment]
I changed the attach code to register an event handler for PMIX_ERR_LOST_CONNECTION and not PMIX_EVENT_JOB_END since I understand I should be getting a lost connection event when the daemon terminates. I printed the nspace and rank fields from the event passed to the handler and it is the namespace and rank of the prterun process, not the daemon. 

Shouldn't attach get a lost event notification from the daemon? Could there be an ordering problem where if prterun exits before the daemon exits, the daemon's lost connection event gets lost even though the tool, not prterun launched the daemon?

From a tool perspective, maybe it doesn't matter since if the prterun process exits, the session is over anyway. However, the tool might care if a daemon exited for some reason (crash) before prterun exited.

**Comment by drwootton** [comment]
I also checked for the PMIX_EVENT_AFFECTED_PROC attribute in the lost connection event thinking the daemon proc object might be there but so such attribute was included in the lost connection event.

**Comment by rhc54** [comment]
You cannot get a "lost connection" event when the daemon terminates because your tool isn't connected to the daemons - you are connected to `prterun`.

**Comment by drwootton** [comment]
I modified the attach example so that it expects and handles a PMIX_ERR_LOST_CONNECTION notification from prterun and the attach example works now.
