### ISSUE TITLE
pcc ignores PRTE_PREFIX and PRTE_INCLUDEDIR

### ISSUE THREAD

**Issue by mike0042** [openpmix/prrte#1029]
## Background information

The pcc command should determine its include directory based on the PRTE_PREFIX and PRTE_INCLUDE environment variables. OpenMPI appears to do this with mpicc using OPAL_PREFIX while PRRTE does not.

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

OMPI nightly build source dated July 3rd, 2021

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

OMPI nightly build source dated July 3rd, 2021

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2.0
* Computer hardware: x86_64 AWS instance
* Network type: AWS EC2 network

-----------------------------

## Details of the problem

The following example illustrates the problem:

```
ip-172-31-55-96 vnc_ec2@ip-172-31-55-96 OMPI mkaro/scripts > env | grep PREFIX
PRTE_PREFIX=/opt/altair/vov/201901/linux64/openmpi
PMIX_PREFIX=/opt/altair/vov/201901/linux64/openmpi
OPAL_PREFIX=/opt/altair/vov/201901/linux64/openmpi
ip-172-31-55-96 vnc_ec2@ip-172-31-55-96 OMPI mkaro/scripts > mpicc -o hello hello.c
ip-172-31-55-96 vnc_ec2@ip-172-31-55-96 OMPI mkaro/scripts > pcc -o hello hello.c
hello.c:1:10: fatal error: mpi.h: No such file or directory
 #include "mpi.h"
          ^~~~~~~
compilation terminated.
ip-172-31-55-96 vnc_ec2@ip-172-31-55-96 OMPI mkaro/scripts > 
```

**Comment by rhc54** [comment]
Couple of things going on here. First, you cannot use `pcc` to compile an MPI program. PRRTE has no concept of `MPI` in it and doesn't know anything about MPI, so it won't link in the MPI library. You have to use `mpicc` for the specific MPI implementation you are using to compile an MPI program.

That said, `pcc` and `pmixcc` should both respect their respective "prefix" envars. Pretty sure they don't, so that is something we'll have to fix.

**Comment by rhc54** [comment]
I fixed a naming bug in the `pmixcc` wrapper - but couldn't find anything wrong with the `pcc` one. Given that you installed from OMPI, however, I'm not sure that PRRTE's wrapper compiler has any idea what is going on. We probably shouldn't be installing it in that scenario.

@bwbarrett Any thoughts here?

**Comment by wckzhang** [comment]
It's unclear to me what the problem here is. Is pcc ignoring PRTE_INCLUDE env?

**Comment by rhc54** [comment]
Yes that is the problem

**Comment by rhc54** [comment]
Clarification: it is PRTE_PREFIX that is ignored

**Comment by rhc54** [comment]
Looks like we have don't have anyone interested in looking at this, so let's just close it. Maybe someone will deal with it in the future.
