### ISSUE TITLE
missing flex error when using tarball

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1031]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

 - prte-2.0.0rc1 
 - https://github.com/openpmix/prrte/releases/tag/v2.0.0rc1

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

 - pmix-4.1.0rc1
 - https://github.com/openpmix/openpmix/releases/tag/v4.1.0rc1

### Please describe the system on which you are running

* Operating system/version: linux 
* Computer hardware: ppc64le
* Network type: ib

-----------------------------

## Details of the problem

Testing 2.0.0rc1 release tarball on failed to configure due to missing `flex` but working from tarball so already have the `configure` script (message states flex not needed).

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
./build_summit-prrte.sh

...<snip>...

checking dependency style of gcc... gcc3
checking for flex... flex
checking for lex output file root... lex.yy
checking for lex library... none needed
checking for library containing yywrap... no
configure: WARNING: yywrap not found; giving up on flex
configure: WARNING: *** Could not find Flex on your system.
configure: WARNING: *** Flex is required for developer builds of PRTE.
configure: WARNING: *** Other versions of Lex are not supported.
configure: WARNING: *** NOTE: If you are building from a tarball downloaded from the PRTE web site, you do not need Flex.
configure: error: Cannot continue
####################################################
# USING:
#  LIBEVENT_INSTALL_DIR=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/libevent-2.1.12-stable
#     HWLOC_INSTALL_DIR=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/hwloc-2.2.0
#      PMIX_INSTALL_DIR=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/pmix-4.1.0rc1
# ---
#
#  PRRTE_INSTALL_DIR=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/prrte-2.0.0rc1
####################################################
# END: Wed Jul 14 14:38:11 EDT 2021
[naughton@login5.summit prrte-2.0.0rc1]$ which flex
/usr/bin/flex
[naughton@login5.summit prrte-2.0.0rc1]$ flex --version
flex 2.5.37
[naughton@login5.summit prrte-2.0.0rc1]$
[naughton@login5.summit prrte-2.0.0rc1]$ head config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by prte configure 2.0.0rc1, which was
generated by GNU Autoconf 2.71.  Invocation command line was

  $ ../../../../source/prrte-2.0.0rc1/configure --prefix=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/prrte-2.0.0rc1 --enable-prte-prefix-by-default --with-libevent=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/libevent-2.1.12-stable --with-hwloc=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/hwloc-2.2.0 --with-pmix=/sw/summit/ums/ompix/DEVELOP/gcc/6.4.0/install/pmix-4.1.0rc1

## --------- ##
## Platform. ##
[naughton@login5.summit prrte-2.0.0rc1]$
```

**Comment by naughtont3** [comment]
[tjn_prte-2.0.0rc1_config.log](https://github.com/openpmix/prrte/files/6818344/tjn_prte-2.0.0rc1_config.log)

**Comment by naughtont3** [comment]
I'm guessing this is a `make dist` issue, but not sure about the autotooling details here.  

FWIW, when i run `autogen.pl` manually things configure/build fine.

**Comment by rhc54** [comment]
@bwbarrett Could you take a quick look? I'm not sure why Flex is being checked here - probably the check for Flex should be in autogen.pl and not somewhere in configure?

**Comment by bwbarrett** [comment]
@rhc54 there's an actual bug here, but I'm not sure the history.  The issue was introduced in https://github.com/openpmix/prrte/commit/9ee1683fca1a174731b7e888fa8c8beac06d946f, which looks like it's a simple AC 2.70 update patch.  But `AM_PROG_LEX` was changed to `AC_PROG_LEX(yywrap)`  The `yywrap` argument is the problem; in order to run the test, it needs to find the flex library, which means having flex installed.  I think the answer is to change `AC_PROG_LEX(yywrap)` to `AC_PROG_LEX(noyywrap)` and then the old behavior should be restored.  I'll test and try to make a patch later today, but want to finish some other issues first.

**Comment by naughtont3** [comment]
@rhc54 @bwbarrett Could it be the `make dist`?  I tried recreating a dist tarball w/ the tag and the resulting `configure` was fine.  But maybe something is happening that I did not expect during my `make dist`?

```
  git clone -b  v2.0.0rc1 https://github.com/openpmix/prrte.git prrte-tag-v2.0.0rc1
  cd prrte-tag-v2.0.0rc1/

./autogen.pl \
&& ./configure \
   --with-libevent=/home/3t4/projects/pmix/scratch/MELTED-PARROT/install \
   --with-hwloc=/home/3t4/projects/pmix/scratch/MELTED-PARROT/install \
   --with-pmix=/home/3t4/projects/pmix/scratch/MELTED-PARROT/source/pmix-4.1.0rc1/_install \
&& make clean \
&& make dist
```
```
ls -l prte-gitclone*
prte-gitclone.tar.bz2  prte-gitclone.tar.gz
```
```
mkdir ../TMPFOO/
tar -xf prte-gitclone.tar.bz2 -C ../TMPFOO/
cd ../TMPFOO/prte-gitclone/
./configure \
  --enable-prte-prefix-by-default \
    --prefix=$MY_PKG_INSTALL_DIR \
   --with-libevent=/home/3t4/projects/pmix/scratch/MELTED-PARROT/install \
   --with-hwloc=/home/3t4/projects/pmix/scratch/MELTED-PARROT/install \
   --with-pmix=/home/3t4/projects/pmix/scratch/MELTED-PARROT/source/pmix-4.1.0rc1/_install
```

**Comment by bwbarrett** [comment]
Do you maybe have the flex libraries installed on some build nodes and not on others (it looks like on the first run flex the binary was installed but the helper library was not found)?  There was most definitely a bug in the "do I need flex" logic that was looking at the wrong path to see if the generated `.c` file existed.  However, that bug only matters if flex/lex isn't found.  I was able to reproduce the issue on my machines pretty regularly with dist tarballs I was building.

**Comment by naughtont3** [comment]
I had `flex` installed.  That's the part that was most curious, and was able to do a configure from git clone, and build a dist tarball from that checkout.  And run the subsequent `configure` that came with that locally generated dist tarball.  

Regardless, I'll check the next rc with your change.  If still have issue, we can dig further.

**Comment by naughtont3** [comment]
Looks good for me in prte-2.0.0rc2
