### ISSUE TITLE
successful autogen/configure leaves code in unbuildable state.

### ISSUE THREAD

**Issue by dsolt** [openpmix/prrte#1032]
Thank you for taking the time to submit an issue!

## Background information

just did a clone/autogen/configure:

configure --prefix 'somewhere' --with-pmix='somewhere-else'

make[3]: Entering directory '/smpi_dev/dsolt/prrte/src/util/hostfile'
  CC       hostfile_lex.lo
  CC       hostfile.lo
In file included from /smpi_dev/dsolt/prrte/src/util/proc_info.h:44,
                 from /smpi_dev/dsolt/prrte/src/pmix/pmix-internal.h:33,
                 from /smpi_dev/dsolt/prrte/src/util/cmd_line.h:124,
                 from /smpi_dev/dsolt/prrte/src/mca/base/base.h:44,
                 from hostfile.c:37:
/smpi_dev/dsolt/prrte/src/hwloc/hwloc-internal.h:29:27: error: #include expects "FILENAME" or <FILENAME>
 #include PRTE_HWLOC_HEADER
                           ^

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
master
##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
master
### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware: power
* Network type: ethernet

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ prun -np 2 ./hello_world
```

**Comment by jjhursey** [comment]
I wonder why configure didn't complain about the missing `--with-hwloc` and `--with-libevent` (which should match whatever you used with OpenPMIx). From the error message it seems like it didn't find what it needed from hwloc.

**Comment by dsolt** [comment]
Yes, I think that is the real issue.  I hacked the /smpi_dev/dsolt/prrte/src/hwloc/hwloc-internal.h: file AND rebuilt with --with-hwloc flag and now it works.  I need to go back and restore the /smpi_dev/dsolt/prrte/src/hwloc/hwloc-internal.h: file and make sure just setting --with-hwloc is sufficient.  I'm confident it is all that is needed, but I'm also 99% sure that my configure without --with-hwloc completed without errors.

**Comment by rhc54** [comment]
It should have failed configure - @bwbarrett is going to address it as part of #1033
