### ISSUE TITLE
fail mapping when pass `--host` option with dvm

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1061]
## Background information

When running with DVM and hostfile, a subsequent `prun` for a specific host (`prun --host node1`) will fail to map.  

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

prte-2.0.0.rc2

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

pmix-4.1.0rc2

### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware: 
* Network type:

-----------------------------

## Details of the problem

```shell
batch4: $ uniq myhosts
batch4
e27n01
e27n02

batch4: $ prte --hostfile myhosts --report-uri dvm.uri --daemonize

batch4: $ prun  --dvm-uri file:dvm.uri --np 1  hostname
batch4

batch4: $ prun  --dvm-uri file:dvm.uri --np 1  --map-by :NOLOCAL  hostname
e27n01

batch4: $ prun  --dvm-uri file:dvm.uri --np 1  --map-by :NOLOCAL --host e27n01  hostname
--------------------------------------------------------------------------
At least one of the requested hosts is not included in the current allocation.

Missing requested host: e27n01

Please check your allocation or your request.
--------------------------------------------------------------------------
[batch4:33896] PMIx_Spawn failed (-179): JOB FAILED TO MAP

batch4: $ prun  --dvm-uri file:dvm.uri --np 1  --host batch4 hostname
[batch4:34520] PMIx_Spawn failed (-179): JOB FAILED TO MAP

batch4: $ pterm --dvm-uri file:dvm.uri
TERMINATING DVM...DONE
batch4: $
```

**Comment by naughtont3** [comment]
Hmmm, looks like it works on my vanilla cluster?  Need to look more closely at why this fails.

```shell
node0:$ uniq myhosts 
node0
node1
node2

node0:$ prte --hostfile myhosts --report-uri dvm.uri --daemonize

node0:$ prun --dvm-uri file:dvm.uri --np 1 hostname
node0

node0:$ prun --dvm-uri file:dvm.uri --np 1 --map-by :NOLOCAL hostname
node1

node0:$ prun --dvm-uri file:dvm.uri --np 1 --map-by :NOLOCAL --host node2 hostname
node2

node0:$ pterm --dvm-uri file:dvm.uri
TERMINATING DVM...DONE
node0:$
```

**Comment by rhc54** [comment]
In your first example, you reused nodes - in this one, you kept using a different node. My guess is that the slot counting code is cleaning up too much and thinks the nodes are "used up"

**Comment by rhc54** [comment]
Well, I've tried every combination of your cmd line on my local vanilla cluster, and I can't find any problem either. What is the difference on that initial test system? Where were you running it?

**Comment by naughtont3** [comment]
This was an issue of mixing things up.  The `ras/lsf` was being used, but passing `--host nodeN` caused the problem.  The fix was to avoid using the `ras/lsf` if using the hostfile/host arg approach.  So closing this ticket.

**Comment by rhc54** [comment]
This turns out to be happening whenever we have a managed allocation (not just LSF) and someone uses `--host`.

I'm investigating.
