### ISSUE TITLE
An improper locking due to the unreleased lock before program exit

### ISSUE THREAD

**Issue by ycaibb** [openpmix/prrte#1080]
Hi developers, in the below codes, the lock `class_lock` could be not released before program's exit `exit(-1);` . I think there is no harm to write` prte_mutex_unlock(&class_lock); ` before the `exit(-1);` for better resource management and code symmetry. Thanks!

https://github.com/openpmix/prrte/blob/3da58aea19a7d6461c34f1a19ac4d64dcba8e4b0/src/class/prte_object.c#L95-L134

Best,

**Comment by rhc54** [comment]
I'm not sure I understand. It looks to me like the lock/unlock calls are balanced. I'm not sure what doing an unlock just prior to calling `exit` would accomplish - all lock resources are dropped when the process exits. Guess I don't care if we add such a line, but I'd like to better understand what it does for us.

What am I missing?

**Comment by ycaibb** [comment]
@rhc54 Thank you for your reply. Your understanding is correct but the lock/unlock calls are imbalanced prior to calling `exit`. According to [this](https://stackoverflow.com/questions/39627669/is-it-necessary-to-unlock-a-mutex-at-the-end-of-main), it would be better to write such a line.

**Comment by rhc54** [comment]
Errr...that's a pretty lame logical argument. You could apply that to all resources used by the program when calling `exit` in an error path. Frankly, we shouldn't be calling `exit` from within a library anyway. Unfortunately, we can't think of a reliable way to get out of the library in this scenario.

Still, I have no moral objection to making the change.

**Comment by ycaibb** [comment]
@rhc54 Thank you very much for your detailed reply and fix.
