### ISSUE TITLE
Missing Ready For Debug event in indirect prun case

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1130]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
2.0.1rc2

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
4.1.1rc2

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

The indirect prun case (using a system server)
```
examples/debugger/indirect bin/prun -n 2 examples/hello
```
gives output ending
```
WAITING FOR APPLICATION LAUNCH
Error: Failed to launch by the timeout
```
whereas it should go on to spawn the debugger daemons.  The failure is due to PMIX_READY_FOR_DEBUG event not being received.
The indirect prterun (rather than prun) case receives the event as expected.

**Comment by rhc54** [comment]
This is fixed by a combination of https://github.com/openpmix/prrte/pull/1134 and https://github.com/openpmix/openpmix/pull/2382
