### ISSUE TITLE
prrte-2.0.1rc3 require PMIX_DATA_BUFFER_STATIC_INIT

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1136]
## Background information

Latest prrte v2.0.1rc3 adds use of `PMIX_DATA_BUFFER_STATIC_INIT` that puts prereq of pmix >= 4.1.1rc5.

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

- prrte 2.0.1rc3

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

 - pmix 4.1.1rc5   # should work
 - pmix 4.1.1rc4   # should fail

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

Was addition of `PMIX_DATA_BUFFER_STATIC_INIT` in prrte-2.0.1rc3 intentional or by accident?  If intentional, i think this sets the minimum OpenPMIx version to v4.1.1rc5.

Fails during configure/build of PRRTE if not using older version of openpmix.

Do we want to add a configure check or something in docs on min openpmix version?

```
  # Build install openpmix-4.1.1rc4
  # Build prrte-2.0.1rc5
  $ ./configure \
     --prefix=$PWD/_install \
   --enable-prte-prefix-by-default \
   --enable-debug \
   --with-devel-headers \
   --with-libevent=$LIBEVENT_INSTALL_DIR \
   --with-hwloc=$HWLOC_INSTALL_DIR \ 
   --with-pmix=$PMIX_INSTALL_DIR \
 && make 

  ...<snip>...

  CC       base/plm_base_launch_support.lo
base/plm_base_frame.c:54:23: error: ‘PMIX_DATA_BUFFER_STATIC_INIT’ undeclared here (not in a function)
     .tree_spawn_cmd = PMIX_DATA_BUFFER_STATIC_INIT,
                       ^
Makefile:860: recipe for target 'base/plm_base_frame.lo' failed
make[2]: *** [base/plm_base_frame.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/ssd/tjn/projects/pmix/CONFUSED-SCORPION/source/prrte-git-br-2.0.1rc3/src/mca/plm'
Makefile:1806: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/ssd/tjn/projects/pmix/CONFUSED-SCORPION/source/prrte-git-br-2.0.1rc3/src'
Makefile:976: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by naughtont3** [comment]
@rhc54 Someone pointed this out to me today.  I confirmed things. Not sure what intention is here, but figured easiest to just create issue to clarify.

**Comment by rhc54** [comment]
Yeah, no problem - I had forgotten to check it. What I can do is simply check for definition and then define it not present. I'll check to ensure we didn't miss anything else that falls into that category.

Thanks for pointing it out! Will have to tag another rc landing point...sigh...but no big deal.
