### ISSUE TITLE
mpirun --host localhost,localhost,localhost /bin/echo foo fails

### ISSUE THREAD

**Issue by yasushi-saito** [openpmix/prrte#1152]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

v2.0 (openmpi 5.0.0-rc2)

### Please describe the system on which you are running

* Operating system/version: 

Ubuntu 20.04.3.

* Computer hardware:

```AMD Ryzen 9 5950X 16-Core Processor```

* Network type:

Localhost

-----------------------------

## Details of the problem

We are trying openmpi 5.0.0-rc2 on a 16-core machine.

`mpirun --host localhost,localhost /bin/echo foo`

works as expected. 

 `mpirun --host localhost:3 /bin/echo foo`

works too. But

`mpirun --host localhost,localhost,localhost /bin/echo foo`

fails with:

```
There are not enough slots available in the system to satisfy the 3
slots that were requested by the application:

  /bin/echo

Either request fewer slots for your application, or make more slots
available for use.

....
```

It looks like the `break` statement in 

https://github.com/openpmix/prrte/blob/1439651a9eccd6f2e6ab8b21244c4635d4f497a5/src/util/dash_host/dash_host.c#L309

shouldn't be there. If I remove it, the last example works as expected.

**Comment by rhc54** [comment]
Ouch - thanks!
