### ISSUE TITLE
dvm options for ompi personality

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1196]
## Background information

Check that necessary options are added under ompi personality for using the DVM.  This will be needed for ompi v5 (see also PR#1176)

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

prte master

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

With stronger separation between personalities and associated option parsing, we need to make sure any useful bits related to DVM are carried over into the ompi personality (e.g., `--dvm-uri file:dvm.uri`, etc.).

**Comment by rhc54** [comment]
Just FWIW: remember that the OMPI community decided over a year ago that `mpirun` would not be allowed to connect to a pre-existing DVM. So options such as the one you cited make no sense for OMPI as you are not allowed to make that connection. You'd have to use `prun` and the default `prte` personality. You are, of course, free to revisit that decision - it wouldn't be _too_ difficult to implement, albeit non-trivial.

**Comment by rhc54** [comment]
Suggestion: instead of trying to enable mpirun to connect to a DVM, probably better to define a `prun` cmd line for the `prun --personality ompi` use-case. See the `schizo/prte` component for an example of how to do this.

**Comment by rhc54** [comment]
@naughtont3 Any reason to keep this open?

**Comment by rhc54** [comment]
Closing - feel free to reopen if necessary
