### ISSUE TITLE
Debugger daemons count towards resource limits

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1206]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
git v2.0 @ b5bc4992d7a387a8136500566d7b07df24ed71fb

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
git v4.1 @ 1bfcf4429179cb346f0d249b109cb8a395a928f5

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

The context of the issue is launching a job under control of a debugger (broadly following the indirect.c example).
The issue (actual behaviour) is that the debugger daemons count towards resource limits, even if the `PMIX_DEBUGGER_DAEMONS` directive is given; spawning debugger daemons with `PMIX_MAPBY=ppr:1:node` fails if the job has already taken all available slots, giving the error `All nodes which are allocated for this job are already filled`.
The expected behaviour is that debugger daemons can be spawned without reference to resource limits.

The issue can be worked around by spawning debugger daemons with `PMIX_MAPBY=ppr:1:node:oversubscribe`.
Alternatively the issue can be worked around with `PMIX_MAPBY=ppr:1:node` via the attached patch, which may help give an indication of the problem.

[prrte.patch.txt](https://github.com/openpmix/prrte/files/8088253/prrte.patch.txt)

**Comment by rhc54** [comment]
Indeed - great catch! And thanks so much for the patch - deeply appreciated. I will extend it to cover the other mappers as well for completeness (though the `ppr` mapper is clearly the one most used for this purpose) and check for any other missing spots.

I am working on a v4.2 release for use in OMPI v5 and will ensure this is carried across to it as well.
