### ISSUE TITLE
Compile: missing file in latest HEAD

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/prrte#1219]
Thank you for taking the time to submit an issue!

## Background information

Compile error in out-of-tree buiold

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master @ 4b890336b94ee9aea0bb92901671a9865b96e8c5

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

master @ 64b9d834122a9cd16a25c3060104b19a7a43b9ca

### Please describe the system on which you are running

* Operating system/version: CentOS 8.1
* Computer hardware: aarch64/a64fx
* Network type: IB

-----------------------------

## Details of the problem

```
  CC       hostfile_lex.lo
  CC       hostfile.lo
In file included from /lustre/home/arcurtis/src/openpmix/prrte/prrte-git/src/runtime/prte_globals.h:50,
                 from /lustre/home/arcurtis/src/openpmix/prrte/prrte-git/src/mca/errmgr/errmgr.h:63,
                 from ../../../../prrte-git/src/util/hostfile/hostfile.c:45:
/lustre/home/arcurtis/src/openpmix/prrte/prrte-git/src/pmix/pmix-internal.h:30:10: fatal error: src/threads/pmix_threads.h: No such file or directory
 #include "src/threads/pmix_threads.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by rhc54** [comment]
Afraid I'm blanking out trying to replicate this - seems to be working fine. Can you post your configure line?

**Comment by tonycurtis** [comment]
```
$ cd build
$ ../prrte-git/configure --prefix=/lustre/home/arcurtis/opt/./openpmix/prrte/git --with-pmix=/lustre/home/arcurtis/opt/./openpmix/pmix/git --enable-prte-prefix-by-default --with-hwloc=/lustre/software/hwloc/2.4.1 --disable-debug
```

**Comment by rhc54** [comment]
My bad - I need the configure line for PMIx

**Comment by tonycurtis** [comment]
```
../pmix-git/configure --prefix=/lustre/home/arcurtis/opt/./openpmix/pmix/git --disable-debug --with-hwloc=/lustre/software/hwloc/2.4.1
```

**Comment by tonycurtis** [comment]
BTW same problem with in-tree compile.

**Comment by rhc54** [comment]
I think I may have found it - it's a question of installing the pmix headers. For some reason, I'm getting it and you aren't. May have found the reason. Just verifying now. If correct, it means our CI is rather uniform in its configure settings.

**Comment by tonycurtis** [comment]
Anything to do with `--with-devel-headers` ?

**Comment by rhc54** [comment]
Yeah, that's the key. I always do it because (duh) I'm doing development. That check should have been removed as we required them for PRRTE.

**Comment by tonycurtis** [comment]
+1
