### ISSUE TITLE
Direct modex fails

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#1243]
The direct modex operation is failing - symptom is an assert due to a bad hotel room number. However, the root cause is that the process name and the key being looked for are getting mangled together. Here is an example of the debug output when setting `--prtemca pmix_server_verbose 5` and running the `examples/dmodex` code at 2ppn across 3 nodes:
```
[rhc-node01:12449] EVICTION FROM ROOM 4048
[rhc-node01:12449] [prterun-rhc-node01-12449@0,0] server:evict timeout - checking for key prterun-rhc-node01-12449@1-23-remote from proc prterun-rhc-node01-12449@1-23-remote:23
[rhc-node01:12449] [prterun-rhc-node01-12449@0,0] server:evict key prterun-rhc-node01-12449@1-23-remote not found - returning to hotel
[rhc-node01:12449] [prterun-rhc-node01-12449@0,0] server:evict checked back in to room 4048
[rhc-node01:12449] EVICTION FROM ROOM 4057
[rhc-node01:12449] [prterun-rhc-node01-12449@0,0] server:evict timeout - checking for key prterun-rhc-node01-12449@1-19-local from proc prterun-rhc-node01-12449@1-19-local:19
[rhc-node01:12449] [prterun-rhc-node01-12449@0,0] server:evict key prterun-rhc-node01-12449@1-19-local not found - returning to hotel
[rhc-node01:12449] [prterun-rhc-node01-12449@0,0] server:evict checked back in to room 4057
```
Note that the proc whose key we are requesting has a namespace that consists of the key. This is undoubtedly a pack/unpack mismatch somewhere in the PRRTE dmodex code path.

I'll try to take a gander at it again in the morning.

**Comment by rhc54** [comment]
I resolved the proc name problem - it was just issues in the `dmodex.c` example code. Final fix is in https://github.com/openpmix/prrte/pull/1246.

At this point, and including https://github.com/openpmix/openpmix/pull/2489, I'm stuck with a segfault in the odls subsystem when it attempts to harvest threads. PRRTE automatically starts multiple threads to help fork/exec local processes faster, and then harvests those threads afterwards to reduce the local OS noise. Somehow, the destructors for the prte_progress_thread trackers are getting messed up and we segfault when running them.

I'm going to have to stop here for now. Hopefully, someone else can pick this up. I'll try to return to it next week.

Note that non-dmodex operations appear to be okay. It might be memory corruption associated with the dmodex hotel operations that is the root cause.

**Comment by awlauria** [comment]
I think that test may be out of date...and potentially buggy? I am not sure.

The test in openpmix seems more maintained: https://github.com/openpmix/openpmix/blob/master/examples/dmodex.c

The one in prrte/examples came from the above, but has not gotten the updates. I notice that PMIx_Get_nb() was replaced with PMIx_Get(), among other things. I'm not sure why the changes were made, but it does seem to run better.
That said it still doesn't work for me, getting a PMIX_ERR_NOT_FOUND error on the PMIx_Get() calls.

**Comment by rhc54** [comment]
Yeah, we should probably refresh all the prrte examples with the ones in pmix - pretty sure the pmix ones have had greater scrutiny. I'll look into it.

**Comment by rhc54** [comment]
You know, looking at it more closely, why don't we get rid of the PRRTE examples directory and just use the ones in PMIx? I see no value in having two sets, and there is no such thing as a "PRRTE app" anyway.

**Comment by awlauria** [comment]
That seems reasonable to me. Maybe remove the tests and just leave a readme pointing to the openpmix examples?

**Comment by rhc54** [comment]
@awlauria Which dmodex example is the `correct` one now? The one in PMIx? Or the one in PRRTE?

**Comment by awlauria** [comment]
Re-opening this issue as we're seeing intermittent failures in CI from:
https://github.com/openpmix/pmix-tests/pull/118

**Comment by rhc54** [comment]
Are we still seeing it as an assert due to a bad room? My impression was that it was something else now.

**Comment by rhc54** [comment]
If I understand it correctly, the problem is now a "hang", possibly intermittent, when retrieving a value that was committed by a local peer. I believe this is likely due to the change of the "backend" storage from a hotel (which had a timeout) to a pointer array (which does not). For a local peer, we wouldn't be sending the request anywhere - and with the change, it wouldn't timeout either.

I'll poke at this a bit today and see if I can confirm. At one time, PMIx was supposed to handle such local requests internally at the server (including any timeout) - if that hasn't changed, then this would be a PMIx problem and not a PRRTE one.

**Comment by rhc54** [comment]
Okay, so here's the problem. It's a classic race condition. When a local client terminates, the PMIx server purges itself of any records of that client - including any data that client posted. So if another local process requests data from that client _after_ it terminates, it won't be found. Since your test doesn't include a "timeout" directive for the `PMIx_Get` calls, and since the PMIx server is dealing with this directly (i.e., the request does not go up to PRRTE), the test hangs because the specified data will never be found.

The PMIx server doesn't include a default timeout as we have no way of knowing where to set it. So the only solutions are:

* really push people to include a "timeout" directive on calls to `PMIx_Get` - I am modifying the test to add it so we don't hang, but this is likely a lost cause in the wild
* don't remove any info posted by a local client until the namespace itself gets cleaned up.

This isn't an "either/or" situation, and doing both makes sense. I'll try to get that done this week.

**Comment by rhc54** [comment]
Weird - I'm not getting anything like that at all. The `-46` error means "not found" - I'm changing the output to print the error strings so it is clearer.

**Comment by rhc54** [comment]
FWIW: here is the error I sometimes get:
```
Client ns prte-Ralphs-iMac-2-57368@1 rank 1: PMIx_Get prte-Ralphs-iMac-2-57368@1-1-local failed: NOT-FOUND
```
Note that rank=1 is looking for a value it "put" - this should never fail to be found. It's sporadic, which implies it most likely is some global info being accessed from outside an event. I'll scan the `PMIx_Get` code to see if something slid thru the cracks.

**Comment by awlauria** [comment]
Yeah, that is the main failure I see. It is fairly easily repeatable on my machines.

**Comment by awlauria** [comment]
The dmodex test is here: https://github.com/openpmix/openpmix/blob/master/examples/dmodex.c

I didn't write it - but it's possible it isn't valid.

FWIW, I can only reproduce on multiple ranks per node. Start hitting it easily at around 20 ppn.

**Comment by awlauria** [comment]
Yeah - it's strange that it works sometimes though, if it was a test case issue I would expect the fail to be more consistent with the output/failure.

**Comment by rhc54** [comment]
If it helps - this can be reproduced with PRRTE. Running it with the `test/simple/simptest` server, I had to use more procs to reliably get it to fail, but could do so:
```
$ /Users/rhc/pmix/clean/test/simple/simptest -n 20 -e ./dmodex
...
Client ns foobar rank 19: Running
Client foobar:9 job size 20

Client ns foobar rank 19: PMIx_Get foobar-19-local failed: NOT-FOUND
Client ns foobar rank 19: PMIx_Get foobar-19-local failed: NOT-FOUND
...
```
Weird thing - I didn't get a "looking for" message prior to those failures, though I did get it for other retrievals. My head hurts.

**Comment by awlauria** [comment]
I am able to reproduce with prrterun.

Will keep hacking at it this week, there doesn't seem to be obvious memory corruption, unless it is stack related. valgrind runs are clean for errors.

**Comment by rhc54** [comment]
My point really was that this isn't a direct modex problem - at least, not what I'm reporting as coming from this test. All I'm doing is pushing some key-vals up to the local PMIx server and locally retrieving them. This is enough to cause the test to fail. So whatever is going on, it has nothing to do with PRRTE.

**Comment by rhc54** [comment]
Found one bug - see https://github.com/openpmix/openpmix/pull/2523. The `test/simple/simpdmodex` test is showing the same "not found" behavior, only much more reproducible. It appears get_nb is returning not found if the value hasn't already been posted, without any delay to give it a chance to show up. I'll look at it a bit more.

**Comment by rhc54** [comment]
@awlauria Tracked it down - see if https://github.com/openpmix/openpmix/pull/2524 fixes the problem for you.

**Comment by awlauria** [comment]
@rhc54 thanks! I can confirm that this test ran clean at 20 ppn across two nodes and single node over 150 iterations. Seems to be fixed.

**Comment by rhc54** [comment]
I'm reopening this only because it still fails on PMIx v4.2 with PRRTE v2.1. I have narrowed it down to something about involvement of the dstore. If you set `PMIX_MCA_gds=hash` in the environment, then the `dmodex` test passes just fine. If you don't and instead allow the dstore to be involved, the test fails.

I'm seeing two oddities in the failure:

1. when a proc fails to get a key, it is always its own "local" key that isn't found. This is very strange as the proc "put" that key itself, and so the data is present in its own `hash` component. I've tried to track it down without success.
2. I sometimes get multiple failure messages from the same proc for the same key. Looking at the logic in the test, this should be impossible - when we fail to find the key, we do a `goto` down to the final fence/finalize. So we can't be failing to find the key multiple times - and yet, I see multiple copies of the message.

I'm hitting a wall on tracking this down, so I'm going to punt (and besides, I'm out all next week). Hopefully, fresh eyes might spot something useful.

**Comment by rhc54** [comment]
Just for clarification. The client always uses two GDS modules. It uses its own internal hash module for storing information it generates. It uses the "dstore" module (either ds12 or ds21, depending on what the server supports) to access job-level info provided by the server.

In the client/get return function, the client stores the data returned by the dmodex call in its own module - which will always be the hash one - and so we initially look for it there. However, in the release branches (where we still have the old ds12/ds21 dstore modules), two things are different:

(a) the server is putting the dmodex results in the shared GDS module - i.e., in the shmem-based dstore., and

(b) the server returns nothing more than an "ack" message to the client/get return function

Hence the need to check both the client's hash module and its dstore module for the data. We will still have to do this in the future as we will continue to have an internal hash module plus the shared "shmem" module (which will also be a hash table).

Hope that helps explain what is going on.

**Comment by rhc54** [comment]
This is now fixed.

**Comment by wckzhang** [comment]
Hmm, what is the policy on reopening an issue vs creating a new one? It looks like there were multiple separate issues that were each resolved, but it's not clear what the current issue is now. It looks like dmodex was re-enabled, so it looks like there's no more issue here anymore?

**Comment by rhc54** [comment]
There should be an open issue on this as it still needs resolution. There is a race condition that causes the CI test to fall which is why that test remains disabled

**Comment by wckzhang** [comment]
Ah I see, those commits naughtont2 pushed out aren't merged into pmix-tests. Thanks for the clarification Ralph

**Comment by rhc54** [comment]
The race condition appears to stem from the handling of the dmodex request by the daemon responsible for returning the data to the requestor. Requests flow from the client proc to their local PMIx server, which passes them to the host prted for processing. The prted looks up the host for the proc that should post the requested data and sends a message to the hosting daemon, which then requests that data from its local PMIx server.

The PMIx server returns data to the host via the `modex_resp` function in src/prted/pmix/pmix_server.c file, line 1052. As the comments there note, this is in the PMIx server's progress thread and needs to be thread-shifted into the prted's event thread for processing.

The race condition here is that the hotel can hit its eviction time and generate an eviction event while the thread-shift is in progress. Thus, either the modex response is handled first and the eviction event gets a stale object from the hotel, or the eviction event gets handled first and the modex response is left with the stale object. Either way, two messages get sent back to the requestor, which causes the requestor to bark an error about a missing cached request.

What we need to do is probably remove the hotel from the tracking system and replace it with a simple list. We can setup a periodic event that runs every N seconds (controlled by an MCA param) - whenever the event fires, we scan the list for entries that have been there too long and remove them, generating a "not found" response back to the original requestor.

When the thread-shift fires, we scan the list to find the corresponding request. If we don't find it, then we know that the timeout has occurred and we just dump the response. If we do find it, then we send the response back to the requestor and remove the tracker from the list.

Hope that helps, and that you can reproduce it so it will be easier to chase down.

**Comment by rhc54** [comment]
Note that if you can reproduce it but don't feel confident about making the code changes, let me know and I'll post a PR with them so you can test and see if we finally get it fixed.

**Comment by rhc54** [comment]
Actually, this might be a much simpler fix:
```diff
diff --git a/src/prted/pmix/pmix_server.c b/src/prted/pmix/pmix_server.c
index 7b16f4adfb..bb19c83051 100644
--- a/src/prted/pmix/pmix_server.c
+++ b/src/prted/pmix/pmix_server.c
@@ -446,6 +446,13 @@ static void eviction_cbfunc(struct pmix_hotel_t *hotel, int room_num, void *occu
                                 PRTE_NAME_PRINT(PRTE_PROC_MY_NAME), req->key, req->tproc.nspace,
                                 req->tproc.rank);
 
+            /* if we already responded, then just clean up - this is
+             * a stale request */
+            if (req->reply_sent) {
+                pmix_hotel_checkout(&prte_pmix_server_globals.reqs, req->room_num);
+                PMIX_RELEASE(req);
+                return;
+            }
             /* see if the key has arrived */
             if (PMIX_SUCCESS == PMIx_Get(&req->tproc, req->key, req->info, req->ninfo, &pval)) {
                 prte_output_verbose(2, prte_pmix_server_globals.output,
@@ -485,11 +492,11 @@ static void eviction_cbfunc(struct pmix_hotel_t *hotel, int room_num, void *occu
         pmix_show_help("help-prted.txt", "timedout", true, req->operation);
     }
 
-    error_condition:
-
+error_condition:
     /* don't let the caller hang */
     if (0 <= req->remote_room_num) {
         send_error(rc, &req->tproc, &req->proxy, req->remote_room_num);
+        req->reply_sent = true;  // in case refcount retains the req
     } else if (NULL != req->opcbfunc) {
         req->opcbfunc(PMIX_ERR_TIMEOUT, req->cbdata);
     } else if (NULL != req->mdxcbfunc) {
@@ -996,6 +1003,12 @@ static void _mdxresp(int sd, short args, void *cbdata)
 
     /* check us out of the hotel */
     pmix_hotel_checkout(&prte_pmix_server_globals.reqs, req->room_num);
+    /* if we already responded, then just clean up - this is
+     * a stale request */
+    if (req->reply_sent) {
+        PMIX_RELEASE(req);
+        return;
+    }
 
     /* pack the status */
     PMIX_DATA_BUFFER_CREATE(reply);
@@ -1041,11 +1054,13 @@ static void _mdxresp(int sd, short args, void *cbdata)
         PRTE_ERROR_LOG(prc);
         PMIX_DATA_BUFFER_RELEASE(reply);
     }
+    req->reply_sent = true;
 
 error:
     PMIX_RELEASE(req);
     return;
 }
+
 /* the modex_resp function takes place in the local PMIx server's
  * progress thread - we must therefore thread-shift it so we can
  * access our global data */
@@ -1554,6 +1569,7 @@ static void rqcon(pmix_server_req_t *p)
     p->key = NULL;
     p->flag = true;
     p->launcher = false;
+    p->reply_sent = false;
     p->remote_room_num = -1;
     p->uid = 0;
     p->gid = 0;
diff --git a/src/prted/pmix/pmix_server_internal.h b/src/prted/pmix/pmix_server_internal.h
index 2f616f2230..8ed388da48 100644
--- a/src/prted/pmix/pmix_server_internal.h
+++ b/src/prted/pmix/pmix_server_internal.h
@@ -91,6 +91,7 @@ typedef struct {
     int remote_room_num;
     bool flag;
     bool launcher;
+    bool reply_sent;
     uid_t uid;
     gid_t gid;
     pid_t pid;
```
You are welcome to see if it works.

**Comment by wckzhang** [comment]
Let me give it a look, thanks Ralph!

**Comment by wckzhang** [comment]
@rhc54 Does PRRTE use direct modex or full modex by default?

**Comment by rhc54** [comment]
Full

**Comment by awlauria** [comment]
@wckzhang the test here: https://github.com/openpmix/pmix-tests/tree/master/prrte/dmodex should scale to any number of nodes. The CI test would fail intermittently, sometimes it would work and sometimes it wouldn't, and we just disabled it until the root cause was tracked down.

You can see the run commands it would test here: https://github.com/openpmix/pmix-tests/blob/master/prrte/dmodex/run.sh

**Comment by wckzhang** [comment]
I've done some testing and it seems that if I don't include the node that I'm launching prun from in my hostfile, I will 100% have a connectivity issue such as:

```
--------------------------------------------------------------------------
PRTE has lost communication with a remote daemon.

  HNP daemon   : [prterun-compute-dy-c5n18xlarge-1-27681@0,0] on node compute-dy-c5n18xlarge-1
  Remote daemon: [prterun-compute-dy-c5n18xlarge-1-27681@0,2] on node compute-dy-c5n18xlarge-3

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
```

(In this case, I ran run.sh from "compute-dy-c5n18xlarge-1" with "compute-dy-c5n18xlarge-2" and "compute-dy-c5n18xlarge-3" in the hostfile)

If I include all three nodes in my hostfile, I will also lose connection:

```
--------------------------------------------------------------------------
PRTE has lost communication with a remote daemon.

  HNP daemon   : [prterun-compute-dy-c5n18xlarge-1-29855@0,0] on node compute-dy-c5n18xlarge-1
  Remote daemon: [prterun-compute-dy-c5n18xlarge-1-29855@0,1] on node compute-dy-c5n18xlarge-2

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
```

(Launched from node 1)

If I run with 1 node, it always completes the dmodex test successfully.

When I run with two nodes, as long as I include the node which I am launching prun with, it runs without issue. This is some very bizarre behavior and is very consistent.

**Comment by wckzhang** [comment]
I lowered the proc count to ```--map-by ppr:2:node``` as it seems this issue is hit no matter the proc count.

I don't think this is related to the eviction events as I passed "--prtemca pmix_server_verbose 5" to my prun command and it doesn't have any logs relating to eviction:

```
[ec2-user@compute-dy-c5n18xlarge-1 dmodex]$ ./run.sh 
+ FINAL_RTN=0
+ CI_HOSTFILE=/home/ec2-user/hostfile
+ NUM_NODES=3
+ cat /home/ec2-user/hostfile
+ xargs -L1 -I '{}' ssh '{}' rm -rf '/tmp/prte.*'
+ prterun --report-state-on-timeout --hostfile /home/ec2-user/hostfile --map-by ppr:2:node --prtemca pmix_server_verbose 5 ./dmodex
+ tee output.txt
[compute-dy-c5n18xlarge-1:05298] [prterun-compute-dy-c5n18xlarge-1-5298@0,0] spawn upcalled on behalf of proc prterun-compute-dy-c5n18xlarge-1-5298@0:0 with 3 job infos
[compute-dy-c5n18xlarge-1:05298] [prterun-compute-dy-c5n18xlarge-1-5298@0,0] spawn called from proc [prterun-compute-dy-c5n18xlarge-1-5298@0,0] with 1 apps
[compute-dy-c5n18xlarge-1:05298] [prterun-compute-dy-c5n18xlarge-1-5298@0,0] register nspace for prterun-compute-dy-c5n18xlarge-1-5298@1
Client ns prterun-compute-dy-c5n18xlarge-1-5298@1 rank 0: Running. World size 4
Got a list of local peers for proc 2: 0,2
Entering loop 0 on rank 2, host compute-dy-c5n18xlarge-2
Got a list of local peers for proc 0: 0,2
Entering loop 0 on rank 0, host compute-dy-c5n18xlarge-2
Retrieving ghex key value on rank 2 from rank 0
Successfully obtained the value 128 on rank 2 from rank 0
Entering loop 1 on rank 2, host compute-dy-c5n18xlarge-2
Entering loop 1 on rank 0, host compute-dy-c5n18xlarge-2
--------------------------------------------------------------------------
PRTE has lost communication with a remote daemon.

  HNP daemon   : [prterun-compute-dy-c5n18xlarge-1-5298@0,0] on node compute-dy-c5n18xlarge-1
  Remote daemon: [prterun-compute-dy-c5n18xlarge-1-5298@0,1] on node compute-dy-c5n18xlarge-2

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
Closed by https://github.com/openpmix/openpmix/pull/2640
