### ISSUE TITLE
Proctable: relative exe paths insufficient for attach

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1249]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

The context of the issue is attaching a tool to a running job.
If the job was launched using relative paths for the application executable, the proctable provided by PMIX_QUERY_PROC_TABLE currently also returns relative paths.  However the attaching tool does not know the working directory that was current when the job was launched, so is unable to locate the exe.
The issue could be addressed by returning absolute paths in the proctable (such as in the attached illustrative patch), or by providing cwd information to allow the absolute path to be derived.

[pmix_server_queries.c.patch.txt](https://github.com/openpmix/prrte/files/8208052/pmix_server_queries.c.patch.txt)

**Comment by rhc54** [comment]
Oh, just fwiw: OMPI v5 is going to use PMIx v4.2 and PRRTE v2.1 branches. I'll update the PRRTE branch with this change.
