### ISSUE TITLE
Global proctable returns pid=0

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1250]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

### Please describe the system on which you are running

* Operating system/version: RHEL 7
* Computer hardware: x86_64 cluster
* WLM: Slurm

-----------------------------

## Details of the problem

The context of the issue is attaching a tool to a running job launched from the head node of a cluster.
```shell
shell$ salloc -N 1
shell$ mpirun -n 2 <app>
```
Connecting a tool to the mpirun server using PMIX_SERVER_PIDINFO and querying the global proctable via PMIX_QUERY_PROC_TABLE returns the list of application processes as expected, however each returned process has a pid of 0.  The valid pid information is required for tool attach to succeed.

**Comment by rhc54** [comment]
Clarifying: the `pid` values are present for procs local to `mpirun`. They are missing for procs remote from that location.

**Comment by rhc54** [comment]
You can use the `pquery` tool from the PMIx library to test this:
```text
$ prterun --map-by ppr:2:node sleep 10000 &
[1] 16370
$ pquery --pid 16370 PMIX_QUERY_PROC_TABLE[PMIX_NSPACE=prterun-rhc-node01-16370@1]
[rhc-node01:16370] recvd query from client
[rhc-node01:16370] RECVD 1 QUERIES
PMIX_QUERY_PROC_TABLE: 
   PMIX_VALUE:  Data type: PMIX_DATA_ARRAY	Size: 4
  Data type: PMIX_PROC_INFO	Value:
 	PROC: prterun-rhc-node01-16370@1:0
 	Hostname: rhc-node01	Executable: /usr/bin/sleep
 	Pid: 16375	Exit code: 0	State: PROC EXECUTING
  Data type: PMIX_PROC_INFO	Value:
 	PROC: prterun-rhc-node01-16370@1:1
 	Hostname: rhc-node02	Executable: /usr/bin/sleep
 	Pid: 1177	Exit code: 0	State: PROC EXECUTING
  Data type: PMIX_PROC_INFO	Value:
 	PROC: prterun-rhc-node01-16370@1:2
 	Hostname: rhc-node01	Executable: /usr/bin/sleep
 	Pid: 16376	Exit code: 0	State: PROC EXECUTING
  Data type: PMIX_PROC_INFO	Value:
 	PROC: prterun-rhc-node01-16370@1:3
 	Hostname: rhc-node02	Executable: /usr/bin/sleep
 	Pid: 1178	Exit code: 0	State: PROC EXECUTING
```
