### ISSUE TITLE
Missing Ready For Debug event in multi-node indirect prun case

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1252]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

### Please describe the system on which you are running

* Operating system/version: RHEL7
* Computer hardware: x86_64 cluster
* WLM: Slurm

-----------------------------

## Details of the problem

Issue #1130 appears resolved in the single node case however I still observe it in the multi-node slurm case:

```shell
shell$ salloc -N 1
shell$ indirect prun -n 2 <app>
```

**Comment by rhc54** [comment]
Working fine with https://github.com/openpmix/prrte/pull/1307
