### ISSUE TITLE
Compile: missing stdatomic.h

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/prrte#1262]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master @ f484c2fdc073adef50dd7b7464e738136eda23c4

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

master @ 8ef501f3b09f7b0b0e3b27fbedffc8b691aab952

### Please describe the system on which you are running

* Operating system/version: CentOS 7.6
* Computer hardware: ARM
* Network type: IB

-----------------------------

## Details of the problem

```
make[3]: Entering directory `/users/arcurtis/src/openpmix/prrte/build/src/util/hostfile'
depbase=`echo hostfile.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../../../prrte-git/src/util/hostfile -I../../../src/include   -iquote/users/arcurtis/src/openpmix/prrte/prrte-git -iquote/users/arcurtis/src/openpmix/prrte/build -iquote/users/arcurtis/src/openpmix/prrte/prrte-git/src/include -iquote/users/arcurtis/src/openpmix/prrte/build/src/include -iquote/users/arcurtis/src/openpmix/prrte/build/include  -I/users/arcurtis/opt/aarch64/libevent/2.1.11/include -I/users/arcurtis/opt/aarch64/openpmix/pmix/git/include -I/users/arcurtis/opt/aarch64/openpmix/pmix/git/include/pmix -I/users/arcurtis/opt/aarch64/hwloc/2.4.0/include  -O3 -DNDEBUG  -finline-functions -pthread -MT hostfile.lo -MD -MP -MF $depbase.Tpo -c -o hostfile.lo ../../../../prrte-git/src/util/hostfile/hostfile.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../../../prrte-git/src/util/hostfile -I../../../src/include -iquote/users/arcurtis/src/openpmix/prrte/prrte-git -iquote/users/arcurtis/src/openpmix/prrte/build -iquote/users/arcurtis/src/openpmix/prrte/prrte-git/src/include -iquote/users/arcurtis/src/openpmix/prrte/build/src/include -iquote/users/arcurtis/src/openpmix/prrte/build/include -I/users/arcurtis/opt/aarch64/libevent/2.1.11/include -I/users/arcurtis/opt/aarch64/openpmix/pmix/git/include -I/users/arcurtis/opt/aarch64/openpmix/pmix/git/include/pmix -I/users/arcurtis/opt/aarch64/hwloc/2.4.0/include -O3 -DNDEBUG -finline-functions -pthread -MT hostfile.lo -MD -MP -MF .deps/hostfile.Tpo -c ../../../../prrte-git/src/util/hostfile/hostfile.c  -fPIC -DPIC -o .libs/hostfile.o
In file included from /users/arcurtis/opt/aarch64/openpmix/pmix/git/include/pmix/src/threads/pmix_threads.h:34:0,
                 from /users/arcurtis/src/openpmix/prrte/prrte-git/src/pmix/pmix-internal.h:30,
                 from /users/arcurtis/src/openpmix/prrte/prrte-git/src/runtime/prte_globals.h:50,
                 from /users/arcurtis/src/openpmix/prrte/prrte-git/src/mca/errmgr/errmgr.h:63,
                 from ../../../../prrte-git/src/util/hostfile/hostfile.c:45:
/users/arcurtis/opt/aarch64/openpmix/pmix/git/include/pmix/src/include/pmix_atomic.h:62:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
make[3]: *** [hostfile.lo] Error 1
make[3]: Leaving directory `/users/arcurtis/src/openpmix/prrte/build/src/util/hostfile'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/users/arcurtis/src/openpmix/prrte/build/src/util'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/users/arcurtis/src/openpmix/prrte/build/src'
make: *** [all-recursive] Error 1
```

GCC 4.8.5

**Comment by rhc54** [comment]
Interesting - so they support C11 atomics, but don't have `stdatomic.h`? Can you do a quick `grep` for me and find out what include file defines `atomic_thread_fence`?

**Comment by tonycurtis** [comment]
The only place I see an inline def is in `/usr/include/c++/4.8.2/bits/atomic_base.h`

**Comment by rhc54** [comment]
Hmmm...this is weird. Can you post the `config.log` from the PMIx build? If you don't have `stdatomic.h`, we should have declared that you don't have C11 atomics and used a different code path.

**Comment by tonycurtis** [comment]
[config.log](https://github.com/openpmix/prrte/files/8226292/config.log)

**Comment by rhc54** [comment]
Errr...actually, I was asking for the PMIx config log, not PRRTE 😄

**Comment by tonycurtis** [comment]
[config.log](https://github.com/openpmix/prrte/files/8226340/config.log)


ah, sorry, misread what you wrote

Output during configure

```
*** Atomics
checking for 32-bit GCC built-in atomics... yes
checking for 64-bit GCC built-in atomics... yes
checking if 64-bit GCC built-in atomics are lock-free... yes
checking for x86_64 architecture... no
checking for atomics style... c11
```

and attached the whole thing

**Comment by tonycurtis** [comment]
Argh, wrong compiler, trying again

**Comment by rhc54** [comment]
Glad you said that, because that config.log said it found  `stdatomic.h` and all was fine!

**Comment by rhc54** [comment]
Just curious - is it possible that PMIx and PRRTE are being built by different compilers? I'm wondering if PMIx found `stdatomic.h` and therefore enabled C11 atomics, but PRRTE doesn't and therefore cannot find `stdatomic.h`.

**Comment by tonycurtis** [comment]
confirmed gcc 4.8.5 (standard) in environment, reinstalling both

**Comment by tonycurtis** [comment]
That's weird, both just compiled and installed.  I've been rejigging my environment as a different arch cluster was added, maybe I messed something up.  Closing.

**Comment by rhc54** [comment]
Huh - weird. Let us know if it shows up again!

**Comment by tonycurtis** [comment]
Will do.  I also rm-rf'ed both install directories, maybe something got added that shouldn't have been there
