### ISSUE TITLE
publishing multiple keys to same scope allowed by PRRTE

### ISSUE THREAD

**Issue by dsolt** [openpmix/prrte#1320]
Thank you for taking the time to submit an issue!

## Background information

It appears that publishing the same key multiple times does not result in an error, but the PMIx standard says:

"Publishing duplicate keys is permitted provided they are published to different ranges. Duplicate 
 keys being published on the same data range shall return the PMIX_ERR_DUPLICATE_KEY error."

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

master

### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware:
* Network type: single node

-----------------------------

## Details of the problem

What do you think the intended behavior should be?  Should we change PRRTE or change the standard?  The later may be quite possible since I don't think anyone is depending on return value that cannot possibly be returned currently unless some other host environment sets it (JSM does not... JSM has the same behavior and uses the most recently published value.)

Also, the text in the standard is unclear about when exactly PMIX_ERR_DUPLICATE_KEY would get returned.  If we want to specify that implementations should return PMIX_ERR_DUPLICATE_KEY, then should they return it if a key is published to two custom ranges (PMIX_RANGE_CUSTOM) that do not overlap?  What if they overlap but are not identical?  What if they are identical but are described differently (e.g. one uses wildcards the other lists all the ranks individually)?

**Comment by dsolt** [comment]
So it sounds to me like the standard is correct then about returning PMIX_ERR_DUPLICATE_KEY?  Any interest in me changing the PRRTE code to make sure it detects duplicate keys?

**Comment by dsolt** [comment]
One more thing... you can publish to the range PMIX_RANGE_CUSTOM, but the standard does not say how to specify that range.  For events, there is a PMIX_EVENT_CUSTOM_RANGE, but publish doesn't seem to have an analogous key.   

It seems like there should be something like:  PMIX_PUBLISH_LOOKUP_CUSTOM_RANGE  (thought that is a really long name!)   It would be used for both publish and lookup though, so I'm not sure what better name to use.  We could just have a single info like:  PMIX_CUSTOM_RANGE_DESCRIPTION but then we would have to probably deprecate PMIX_EVENT_CUSTOM_RANGE.  

I'll take a stab at detecting the duplicate keys in PRRTE.

**Comment by rhc54** [comment]
Hmmm...let's just create a `PMIX_CUSTOM_DATA_RANGE` attribute and leave the event one alone. Should be clear as the range data type is `pmix_data_range_t`.

**Comment by dsolt** [comment]
Another question...  Regarding:  

"Publishing duplicate keys is permitted provided they are published to different ranges. Duplicate
keys being published on the same data range shall return the PMIX_ERR_DUPLICATE_KEY error."

Namespace X contains processes A and B.
Process A publishes "foo" at the namespace range.
Process B publishes "foo" at the namespace range.
Should one of those calls return PMIX_ERR_DUPLICATE_KEY?    (or it only an error if process A attempted to publish "foo" a the namespace range twice)

**Comment by rhc54** [comment]
If any process publishes the same key on the same namespace range, then that should return the error. Which process gets the error will depend on which one is received first at the data server (the loser gets the error).

**Comment by rhc54** [comment]
If you really want to get a headache, consider the following:

Namespace X contains processes A and B.
Namespace Y contains process C.
Process A publishes "foo" at the namespace range.
Process C publishes "foo" with a custom range of `[X, wildcard]`.

Should that generate an error? Would certainly seem so, otherwise if process B does a lookup we won't know which value to return. We can't use the argument that there is a difference in how the range was specified as both publish commands will look exactly the same.

**Comment by dsolt** [comment]
Agreed.  If we use your proposed definition of "I think that the correct behavior is to simply say the range is literally identical", then whichever publish operation gets processed second should return an error in your last example.

**Comment by rhc54** [comment]
This part of the code probably needs a revamp, but I think it unlikely it will happen anytime soon.
