### ISSUE TITLE
How to output "prte_output" vs "show_help"

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#1326]
We need to ensure that tools have access to all the output generated by PRRTE as well as any apps PRRTE is running. We currently use the PMIx IOF subsystem for this purpose, which allows a tool to not only select which streams to see (stdout, stderr, stddiag), but also to control whether PRRTE continues to output the stream to the screen in addition to providing it to the tool.

Besides the output streams PRRTE captures from each app proc, there are two sources of output from PRRTE itself:

* prte_output (verbose or otherwise) - these messages go to stderr by default.
* prte_show_help - also output to stderr

I recently committed a change to "show_help" so that stream gets processed by the PMIx IOF subsystem. Thus, tools that "pull" the stddiag channel will receive them.

However, this begged the question I now pose to the community:

* should the "show_help" stream go to stddiag, or to stderr? It obviously will always go to stderr when printed to the screen - this question pertains to the stream that a tool would have to subscribe to in order to receive the message. Do we consider "show_help" messages to be diagnostic? Or are they reporting a user-level error?

* similar question for prte_output messages. Should these messages be provided to tools? If so, on what stream (stderr or stddiag or stdout)?

FWIW: in the past, we always output "show_help" and "prte_output" messages on the stddiag IOF channel, which is why I put "show_help" on IOF_STDDIAG for now. Just not sure that is what we want to do going forward.

**Comment by rhc54** [comment]
@jsquyres Since you have always been one of the main proponents of "show_help", I'm flagging you in case you have an opinion.

**Comment by jsquyres** [comment]
Forgive me, it's been a while: the primary purpose of stddiag is for de-duplication, right?  E.g., we have the app send show_help messages to stdiag so that the entire help message can be slurped up by the local PMIx agent (along with a little metadata about the message), and then the entire bundle -- metadata + content -- is sent back to the tool (e.g., prtertun), and the tool can decide to display it or not.

Is my memory correct?

If so, I'm still a proponent of this scheme -- at least for Open MPI.  I'd also think that non-show_help messages (e.g., prte_output/pmix_output) should still just go to stderr.

That being said, can schitzo components change these defaults if they want to?  That would then allow any tool to do whatever it wants, regardless of the PMIx / PRTE defaults.

**Comment by rhc54** [comment]
Okay, that's pretty much what we have now. The "show_help" messages are available on the `stddiag` IOF channel, and a tool can request that we forward that channel to them if they want it. My point was that they need to understand that they have to pull that channel to receive the PRRTE "show_help" messages, but that's okay - the documentation clearly states it, so it is their problem.

I'm also okay with leaving `prte_output` just printing to the screen (i.e., a tool cannot get it). Shouldn't be a problem as it only really pertains to developers.

I'm not sure what to do with "show_help" messages flowing from PMIx (or the OMPI layers, for that matter) as it is challenging for PRRTE to aggregate them. PRRTE doesn't necessarily know how the "show_help" works in other code bases, so it seems a pretty big abstraction break for us to assume there is a "filename/topic/message" trio. Besides, PRRTE doesn't necessarily have access to the helpfile nor know where it should be located.

I imagine we could document a "PMIx show help subsystem" that 3rd party packages could use - would look like what we have today, but would require that someone initialize it with the location of their files. Would have to be in the PMIx layer as apps don't link against PRRTE (and we don't want them to do so). Probably put it under the `PMIx_Log` API - have to think about it a bit.

**Comment by jsquyres** [comment]
I'm not knowledgeable on the division of layers between PMIx and PRTE -- does show_help exist in both places?  ... taking a quick look in OMPI, PMIX, and PRTE, I guess it exists in all 3 places.

Perhaps it would be worth separating the functionality of:

1. Rendering a show_help message (which I think we already have in `opal_show_help_string()` -- I don't know if that carried over to PMIX / PRTE).
2. Multiplexing the emission of messages (e.g., stdout, stderr, files, etc.).
3. De-duplicating the emission of messages.

PMIX/PRTE/whatever could potentially only have to provide the de-duplication part, and not have to grok the de-duplication token (e.g., a string) and the message that it is emitting.  Perhaps something like (off the top of my head, and completely ignorant of PMIX/PRTE API conventions):

```c
// Emit the message to stdout or stderr if we have never emitted a message
// with the same string value of unique_id_string during this run.
// The enum arg is just for flexibility, in case this functionality is used for
// things other than error/help messages.
void PMI_Emit_once(const char* unique_id_string, const char* message, enum stout_or_stderr);
```

This would keep all the details of show_help files / messages / rendering local to OMPI.  PMIX (or PRTE?) only handles the de-duplication and actual emission of the message to stdout or stderr.  

Just a thought.

**Comment by awlauria** [comment]
Would it make sense then for all show-help (prte/pmix/opal) to use the `PMIx_Log()` api then so we don't have to duplicate code? Prrte already has a method of de-duplicating and reporting, that could just be ported to open pmix so all three components can 'share' the same de-duping mechanism.

**Comment by rhc54** [comment]
Yeah, that's the plan - need to define 1-2 new attributes for that purpose (so "log" knows when to dedup and has the necessary `<filename>-<topic>` ID tag for the topic) and add a little infrastructure (moving the dedup code for starters) to PMIx (and maybe a bit to PRRTE, though I think the log support is already there).

**Comment by awlauria** [comment]
Yup makes sense. If nobody else has started I can probably PR a proposed solution by the end of the week.

**Comment by rhc54** [comment]
Would be much appreciated!

**Comment by awlauria** [comment]
PMIx side changes are here: https://github.com/openpmix/openpmix/pull/2569

The prrte changes are close to being ready to PR to allow the above to work with pmix/prrte_show_help(). opal will require some changes as well, but those are relatively small.

**Comment by awlauria** [comment]
prrte master: https://github.com/openpmix/prrte/pull/1350 + https://github.com/openpmix/prrte/pull/1353 + https://github.com/openpmix/prrte/pull/1355
prrte v2.1: https://github.com/openpmix/prrte/pull/1354

pmix master: https://github.com/openpmix/openpmix/pull/2571
pmix v4.1: https://github.com/openpmix/openpmix/pull/2582
pmix v4.2: https://github.com/openpmix/openpmix/pull/2576

ompi main (pmix + prrte master update): https://github.com/open-mpi/ompi/pull/10348 + https://github.com/open-mpi/ompi/pull/10355

ompi v5.0.x: https://github.com/open-mpi/ompi/pull/10366

Since everything is merged I think we can close this.
