### ISSUE TITLE
Failed to build prrte SRPM/RPM

### ISSUE THREAD

**Issue by acgoldma** [openpmix/prrte#1332]
Thank you for taking the time to submit an issue!

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

https://github.com/open-mpi/ompi/pull/10224
[openpmix @ 6692c28](https://github.com/openpmix/openpmix/tree/6692c28a4daed5e99443eb724231d7300287fb2c)
[prrte @ 7ae2c08](https://github.com/openpmix/prrte/tree/7ae2c083189db0881d2eff29d71bd507be02bad3)
### Please describe the system on which you are running

* Operating system/version: **RHEL 8.4**
* Computer hardware: **Intel E5-2699 v3**
* Network type: **N/A**

-----------------------------

## Details of the problem

I am working with @jsquyres on https://github.com/open-mpi/ompi/pull/10224 to build openmpi v5.x RPMs, but to do this I need PMIx and PRRTE RPMS installed. PMIx seems to build correctly, but PRRTE seems to have some issues:

```
# contrib/dist/make_dist_tarball --no-greek --highok --no-git-update
...
=============================================
prrte-3.0.0 archives ready for distribution:
prrte-3.0.0.tar.gz
prrte-3.0.0.tar.bz2
=============================================

#  ./contrib/dist/linux/buildrpm.sh -s ../prrte-3.0.0.tar.bz2
...
--> Created destination specfile: /root/RPMBUILD/SPECS/prte-3.0.0.spec
--> Building the PRTE SRPM
--> rpmbuild --define 'mflags -j4' --define '_source_filedigest_algorithm md5'  --define '_binary_filedigest_algorithm md5' --define '_topdir /root/RPMBUILD' --define 'dist %{nil}' -bs /root/RPMBUILD/SPECS/prte-3.0.0.spec
error: Bad source: /root/RPMBUILD/SOURCES/prte-3.0.0.tar.bz2: No such file or directory
*** FAILURE BUILDING SRPM!
```

SRPM is building now with this patch to spec file:
```
rpmbuild --define "_name prrte" -bs /root/rpmbuild/SPECS/prte-3.0.0.spec
```
```diff
@@ -355,7 +355,7 @@
 # there that are not meant to be packaged.
 rm -rf $RPM_BUILD_ROOT

-%setup -q -n prte-%{version}
+%setup -q -n %{name}-%{version}

 #############################################################################
 #
```

RPM is failing with unpackaged files.
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/prrte-3.0.0-1.el8.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/include/prte.h
   /usr/include/prte_version.h


RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/include/prte.h
   /usr/include/prte_version.h
```

**Comment by rhc54** [comment]
Odd - I have at least two other orgs that successfully build RPMs today, though I don't know if they use our spec file (pretty sure one does, but can't say for certain). I can poke at it a bit when time permits.

**Comment by rhc54** [comment]
Took a quick peek at this so we don't hold you back too much - this spec file clearly needs a complete overhaul. Lots of spurious references to OMPI in the comments, for one, as we based it off of that file.

Try adding this change:
```diff
@@ -678,6 +678,7 @@ test "x$RPM_BUILD_ROOT" != "x" && rm -rf $RPM_BUILD_ROOT
 %{_bindir}/*
 %{_libdir}/*
 %{_datadir}
+%{_includedir}
 %else
 %{_prefix}
 %endif
```
I think that should get you over the hump.

**Comment by acgoldma** [comment]
Build command:
```
./contrib/dist/make_dist_tarball --no-greek --highok --no-git-update --dirtyok
cd ./contrib/dist/linux
./buildrpm.sh -n prrte ../../../../prrte-3.0.0.tar.bz2
```
I can build the single rpm with these:
```diff
diff --git a/contrib/dist/linux/buildrpm.sh b/contrib/dist/linux/buildrpm.sh
index 36a9db52cf..9869c864ea 100755
--- a/contrib/dist/linux/buildrpm.sh
+++ b/contrib/dist/linux/buildrpm.sh
@@ -267,7 +267,7 @@ fi
 # Find where the top RPM-building directory is
 #

-rpmtopdir=$HOME/RPMBUILD
+rpmtopdir=$HOME/rpmbuild
 if test "$rpmtopdir" != ""; then
         rpmbuild_options="$rpmbuild_options --define '_topdir $rpmtopdir'"
     if test ! -d "$rpmtopdir"; then
diff --git a/contrib/dist/linux/prte.spec b/contrib/dist/linux/prte.spec
index 42d9353213..01df30f338 100644
--- a/contrib/dist/linux/prte.spec
+++ b/contrib/dist/linux/prte.spec
@@ -211,7 +211,7 @@ Version: $VERSION
 Release: 1%{?dist}
 License: BSD
 Group: Development/Libraries
-Source: prte-%{version}.tar.$EXTENSION
+Source: %{name}-%{version}.tar.$EXTENSION
 Packager: %{?_packager:%{_packager}}%{!?_packager:%{_vendor}}
 Vendor: %{?_vendorinfo:%{_vendorinfo}}%{!?_vendorinfo:%{_vendor}}
 Distribution: %{?_distribution:%{_distribution}}%{!?_distribution:%{_vendor}}
@@ -355,7 +355,7 @@ This subpackage provides the documentation for Open MPI/OpenSHMEM.
 # there that are not meant to be packaged.
 rm -rf $RPM_BUILD_ROOT

-%setup -q -n prte-%{version}
+%setup -q -n %{name}-%{version}

 #############################################################################
 #
@@ -678,6 +678,7 @@ test "x$RPM_BUILD_ROOT" != "x" && rm -rf $RPM_BUILD_ROOT
 %{_bindir}/*
 %{_libdir}/*
 %{_datadir}
+%{_includedir}
 %else
 %{_prefix}
 %endif
@@ -727,7 +728,7 @@ test "x$RPM_BUILD_ROOT" != "x" && rm -rf $RPM_BUILD_ROOT
 %if !%{sysconfdir_in_prefix}
 %{_sysconfdir}
 %endif
-# If %{install_in_opt}, then we're instaling OMPI to
+# If %%{install_in_opt}, then we're instaling OMPI to
 # /opt/prte/<version>.  But be sure to also explicitly mention
 # /opt/prte so that it can be removed by RPM when everything under
 # there is also removed.  Also list /opt/prte/<version>/share so
```

building the multiple rpms does not work for some reason: (no errors above)
```
+ grep -v /usr/share/man docs.files
error: Bad exit status from /var/tmp/rpm-tmp.jir1Li (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.jir1Li (%install)
*** FAILURE BUILDING MULTIPLE RPM!
Aborting
```

**Comment by rhc54** [comment]
This change
```diff
-rpmtopdir=$HOME/RPMBUILD
+rpmtopdir=$HOME/rpmbuild
```
is just a reflection of your personal setup. I believe the convention is to use the capitalized name. Other changes look reasonable - you are welcome to submit a PR for those.

Some of the remaining problems are due to a global search/replace of `prrte` with `prte` that was unfortunately done a while back - still causing problems, though I think I've weeded most of them out. The package is supposed to be named `prrte` as are the tarballs.

**Comment by acgoldma** [comment]
> This change
> 
> ```diff
> -rpmtopdir=$HOME/RPMBUILD
> +rpmtopdir=$HOME/rpmbuild
> ```
> 
> is just a reflection of your personal setup. I believe the convention is to use the capitalized name. Other changes look reasonable - you are welcome to submit a PR for those.

From what I see the convention elsewhere is lowercase, but either way, it should match pmix and ompi, which take in value as arg or env.
```shell
rpmtopdir=${rpmtopdir:-$HOME/rpmbuild}
```

I can submit an patch.

**Comment by acgoldma** [comment]
PR: https://github.com/openpmix/prrte/pull/1333

**Comment by rhc54** [comment]
> but either way, it should match pmix and ompi, which take in value as arg or env.

Just to be clear, it doesn't _have_ to match those other projects - it is a completely separate project on its own. However, there certainly is no harm in doing so, and it makes things more usable by others.

**Comment by rhc54** [comment]
Given that the all-in-one rpm build has now been fixed, do you intend to deal with the separate rpm builds as well? Or shall we close this ticket?

**Comment by acgoldma** [comment]
> Given that the all-in-one rpm build has now been fixed, do you intend to deal with the separate rpm builds as well? Or shall we close this ticket?

For me, I believe I am done.

Only possible reason to keep this open is, since OMPI no longer includes this internally in SRPM/RPM distros might need this working to build off of?

**Comment by rhc54** [comment]
I actually had been thinking of removing it entirely as the distros use their own spec files - AFAIK, I was the only one using it, and I use it solely to generate an SRPM for releases. I doubt anyone would miss those much, and I could easily just maintain it locally instead of in the repo.

🤷‍♂️ I'll close this for now. We'll probably keep the file in the repo, at least for the moment, and I'll cleanup the comments in it.
