### ISSUE TITLE
issue with direct launch using slurm's srun

### ISSUE THREAD

**Issue by wzamazon** [openpmix/prrte#1343]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

```
7ae2c083189db0881d2eff29d71bd507be02bad3 3rd-party/prrte (psrvr-v2.0.0rc1-4340-g7ae2c08318)
```

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

```
6692c28a4daed5e99443eb724231d7300287fb2c 3rd-party/openpmix (v1.1.3-3495-g6692c28a)
```

### Please describe the system on which you are running

* Operating system/version: amazon linux 2
* Computer hardware: intel
* Network type: EFA

-----------------------------

## Details of the problem

I tried to use `srun` (from slurm 20.11.8) with the executable from open-mpi main branch, and encountered issue.

I used the following testing code:
```
#include <mpi.h>
#include <stdio.h>

int main(int argc, char **argv)
{
	int myrank, numprc;


	MPI_Init(&argc, &argv);

	MPI_Comm_size(MPI_COMM_WORLD, &numprc);
	MPI_Comm_rank(MPI_COMM_WORLD, &myrank);

	printf("Hello from proc %d of %d\n", myrank, numprc);
	
	MPI_Finalize();
}
```
Used the following command to compile:
```
mpicc -o test_mpi_main test_mpi.c
```
I used the following command to run:
```
srun -n 4 ./test_mpi_main
```
The output  I got was:
```
[ec2-user@ip-172-31-82-82 openmpi]$ srun -n 4  ./test_mpi_main 
Hello from proc 0 of 1
Hello from proc 0 of 1
Hello from proc 0 of 1
Hello from proc 0 of 1
```
As can be seen, the rank and wordsize is not right in the output.

Meanwhile, If I use the following command:
```
srun -n 4 --mpi=pmix ./test_mpi_main
```
I got the correct result. 
```
[ec2-user@ip-172-31-82-82 openmpi]$ srun -n 4 --mpi=pmix ./test_mpi_main 
Hello from proc 1 of 4
Hello from proc 2 of 4
Hello from proc 3 of 4
Hello from proc 0 of 4
```

FYI, the behavior with open-mpi 4.1.2 is different from main branch.
If I use `srun` with an executable from open-mpi 4.1.2, I got the following warning message:
```
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```
I did some investigation and found the error message in v4.1.x was emitted from `orte/mca/ess/pmi/ess_pmi_module.c`, when opal_pmix.init() failed and the job was directly launched. Because orte is  replaced by prrte in ompi, I think this is more of a prrte issue than ompi issue.

I wonder  what is the expected behavior with `srun`?

should the command just work (no need to specify `--mpi=pmix`) or should it emit an error (like ompi v4.1.2)?

**Comment by rhc54** [comment]
I'm afraid that is something for the OMPI folks. The way the integration is currently written assumes that the failure to connect to a PMIx server means that the process is acting as a singleton. I'm afraid there is no way to determine if the process _should_ have found a server, so you either have to declare that any inability to find a server is an error (and not a singleton), or you have to assume you are a singleton and proceed accordingly.

Either way, it has nothing to do with PRRTE or PMIx.
