### ISSUE TITLE
Indirect slurm launch fails (5.0.0rc6)

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1345]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Open MPI 5.0.0rc6

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Open MPI 5.0.0rc6

### Please describe the system on which you are running

* Operating system/version: RHEL 7.9
* Computer hardware: x86_64 cluster
* WLM: slurm 21.08.5

-----------------------------

## Details of the problem

Similar to #1251.  Using 3rd-party/prrte/examples:

```shell
shell$ salloc -N 1
shell$ debugger/indirect mpirun -n 2 hello
```
gives output ending
```
WAITING FOR APPLICATION LAUNCH
terminate_fn called with status LOST_CONNECTION
Error: Launcher failed
```
Changing the command to use
```shell
shell$ salloc -N 1
shell$ debugger/indirect mpirun --mca plm ssh -n 2 hello
```
allows the application to be launched.

**Comment by rhc54** [comment]
Okay, release branch has been updated - you'll need to poke the OMPI folks to update their submodule pointer.
