### ISSUE TITLE
prterun v2.1 mistaken error message

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1356]
The `prterun` on v2.1 provides a mistaken error message (missing executable) due to single-option flag, and fails to locate the help files.  Note, the default `mpirun` works fine, only the `prterun` command.

### Version info

 - NOTE: Based on build of prrte/pmix within openmpi-5.0.0-nightly tarball
 - prrte v2.1 with openmpi-5.0.x (prte @ [f75647a](https://github.com/openpmix/prrte/tree/f75647a0518b5a476011f543200fca1cf8600cb8))
 - pmix v4.x with openmpi-5.0.x (pmix [8c39d8e](https://github.com/openpmix/openpmix/tree/8c39d8e6a95d6fa78e765b5e86c324bd8a4ecd56))

### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware: x86-64
* Network type:

-----------------------------

## Details of the problem

 - The `prterun` command with `-np 1` (single dash) fails to parse properly and leads to an error about the executable file being missing.
 - Additionally the `search_dirs[]` are not populated so the error message does not locate helpfile.

Things do not hang, just return incorrect error msg.  Since the focus in ompi is to use `mpirun` this may be a non-issue and something we want to ignore for the v2.1 branch.

```shell
node0:$ prterun -np 1 /usr/bin/hostname
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    prun:exe-not-found
But I couldn't open the help file:
    (null).  Sorry!
--------------------------------------------------------------------------
node0:$ which hostname
/usr/bin/hostname
node0:$ prterun -np 1 /usr/bin/hostname
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    prun:exe-not-found
But I couldn't open the help file:
    (null).  Sorry!
--------------------------------------------------------------------------
node0:$ prterun --np 1 /usr/bin/hostname
node0
node0:$ mpirun -np 1 hostname
node0
node0:$ mpirun --np 1 hostname
node0
node0:$
```

**Comment by rhc54** [comment]
> Since the focus in ompi is to use mpirun this may be a non-issue and something we want to ignore for the v2.1 branch.

Last I checked, this wasn't an OMPI project 😄 We'll need to fix it before release.

**Comment by awlauria** [comment]
Isn't this due to `prterun` requiring double-dash on the command line? The error condition hits with `-np 1`.

The reason it won't hit with `mpirun` is that schizo/ompi will convert that single-dash to a double.

**Comment by rhc54** [comment]
Yes - we "fixed" that problem in the master branches with a patch in the PMIx cmd line processor. This is an example of the refactoring issue - we fix things on the PMIx side, but since neither release branch has a corresponding landing spot for that change, the fix never makes it back to the release branches. Generating custom fixes for the release branches for every bug fix just isn't tenable.

**Comment by rhc54** [comment]
Verified now fixed.
