### ISSUE TITLE
mpirun: prterun cannot start daemon

### ISSUE THREAD

**Issue by wckzhang** [openpmix/prrte#1392]
PMIx and PRRTE are both Open MPI main branch submodules.

```
ompi wilzhang$ git submodule
+26ff1684378e1c5859e377249a3e78f287b04216 3rd-party/openpmix (v1.1.3-3523-g26ff1684)
+47b5ad1653123e984a644ef84b9a7aaf4e9b5fb3 3rd-party/prrte (psrvr-v2.0.0rc1-4355-g47b5ad1653)
```

We run on Amazon Linux 2 AMI on c5n.18xlarge instance types
-----------------------------

We are seeing fairly frequently on Open MPI main, prterun not being able to start daemons.

```
==== starting mpirun --prefix /fsx/ompi/install --wdir results/omb/collective/osu_igather -n 576 --map-by ppr:36:node --output tag  --rank-by slot --hostfile /fsx/hosts.file -x PATH -x LD_LIBRARY_PATH -x FI_LOG_LEVEL /fsx/SubspaceBenchmarksRepo-ompi/spack/opt/spack/linux-amzn2-x86_64/gcc-7.3.1/osu-micro-benchmarks-5.6-465dcncsvzqciysioksqv2vkc2whrieg/libexec/osu-micro-benchmarks/mpi/collective/osu_igather -x 10 -i 10 : Mon May 16 09:22:40 UTC 2022 ====
--------------------------------------------------------------------------
prterun was unable to reliably start one or more daemons.
This usually is caused by:

* the inability to resolve specified hostnames - please check
  above for any output regarding this possibility

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-prun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/prte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
return status: 1
```

This doesn't happen all the time but happens fairly frequently in our CI. These scripts don't run into issues with earlier versions of Open MPI (4.1.2), so I don't think any of the suggested issues are applicable. (Also this should be changed: compilation of the orted -> compilation of the prted).

This problem typically occurs in some of our scale up OSU micro benchmark tests from 1-16 nodes (36 ppn -> 576 ppn) at random proc counts.

For example:

```
==== starting mpirun --prefix /fsx/ompi/install --wdir results/omb/collective/osu_igather -n 3 --map-by ppr:36:node --output tag  --rank-by slot --hostfile /fsx/hosts.file -x PATH -x LD_LIBRARY_PATH -x FI_LOG_LEVEL /fsx/SubspaceBenchmarksRepo-ompi/spack/opt/spack/linux-amzn2-x86_64/gcc-7.3.1/osu-micro-benchmarks-5.6-465dcncsvzqciysioksqv2vkc2whrieg/libexec/osu-micro-benchmarks/mpi/collective/osu_igather  -x 1 -i 1  : Sun Jul 24 09:21:49 UTC 2022 ====
--------------------------------------------------------------------------
prterun was unable to reliably start one or more daemons.
This usually is caused by:

* the inability to resolve specified hostnames - please check
  above for any output regarding this possibility

* not finding the required libraries and/or binaries 
* ```

**Comment by rhc54** [comment]
Well, let's try to narrow things down. First, drop the OSU test apps and just run `/bin/true`. Then, since it is the daemon startup that seems to be failing, try adding `--leave-session-attached` to the cmd line to see if the daemon reports anything. You can then add `--prtemca plm_base_verbose 5` to see the launch sequence.

Let's see if any of those work, and what they have to say.

**Comment by rhc54** [comment]
One thing you should do first is go to each of those submodules and do:
```text
$ git checkout master
$ git pull
```
to ensure you are at the head of their respective master branches. I don't see those hashes anywhere recent in the repo, so let's ensure we aren't working with stale code.

**Comment by rhc54** [comment]
Ah, I found them - and they are indeed very stale. Please update and retry.

**Comment by jjhursey** [comment]
IBM's Open MPI CI and MTT see this type of thing with Open MPI testing. It's infrequent, which makes it hard to reproduce. Hopefully the submodule update will help.

**Comment by rhc54** [comment]
The updates will include a fix for a bug I found in the OOB wireup - hence my thought that it might just solve this problem. I believe @awlauria has a PR to update the submodule pointers as well - but easy enough to check manually for now.

**Comment by awlauria** [comment]
The Pr to update the submodules hit another snag that I can't reproduce - @rhc54 any ideas?

https://github.com/open-mpi/ompi/pull/10611

https://github.com/open-mpi/ompi/pull/10611#issuecomment-1196712029 - the specific failure CI is hitting.

**Comment by wckzhang** [comment]
I was able to reproduce this issue with ompi main (before submodule pointers were updated), albeit very rarely (Maybe once every hundred runs). However, after the submodules were updated (and disregarding the topology issue #1400), it seems like this issue has been fixed. I will resolve the issue.
