### ISSUE TITLE
Oversubscribing via hostfile will fail to bind

### ISSUE THREAD

**Issue by awlauria** [openpmix/prrte#1395]
Creating a hostfile, for example as follows:

```
localhost slots=45
```
on a 44 core node and launching with:

```
prterun --hostfile=./hostfile hello_world
```
will fail with:

```
--------------------------------------------------------------------------
Either there are not enough slots available in the system to launch
the 45 processes that were requested by the application, or there are
not enough CPUs to bind them as requested:

  App: ./examples/hello_c
  Mapping: BYCORE
  Binding: CORE

Either request fewer processes for your application, make more slots
available for use by expanding the allocation, or do not bind the
processes so that the number of CPUs is no longer a limiting factor.

A "slot" is the PRRTE term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which PRRTE processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, PRRTE defaults to the number of processor cores

In all the above cases, if you want PRRTE to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --map-by :OVERSUBSCRIBE option to ignore the
number of available slots when deciding the number of processes to
launch. Similarly, you can use the --bind-to :OVERLOAD option to bind
more than one process to a CPU, if desired, or --bind-to NONE to avoid
binding altogether.
--------------------------------------------------------------------------
```

This is a change in behavior from prte (and orte) prior to: https://github.com/openpmix/prrte/commit/4b41c8e0a30befd21298b93c1aa12fcd6ac69b30

The old behavior would just not bind the procs but still launch them.

@rhc54 should a check be added to enable oversubscribe (or just not bind) in this case?

Refs: https://github.com/open-mpi/ompi/pull/10611

**Comment by rhc54** [comment]
Oversubscribe will turn off binding, so that should be okay. It shouldn't have errored out in this scenario - unless you are in a managed allocation. So it is either a bug or this was running inside an RM-managed allocation. Can you confirm the latter isn't the case?

**Comment by awlauria** [comment]
Hey, I am not running in a a managed allocation, just mpirun/prterun needed to reproduce.

**Comment by rhc54** [comment]
okay, I'll take a look

**Comment by rhc54** [comment]
Actually, I think I know what the problem is - it isn't really a "not enough slots" problem, despite the error output. It isn't finding enough cores to bind the procs to that is the issue. This isn't really an oversubscribe problem as you specified the number of slots and we simply filled them.

Let me ponder how to address this scenario. Ultimately, we need to wind up turning off the binding, but I need to figure out where/how to determine that this is the case.

**Comment by awlauria** [comment]
Thanks, yeah that is how I understand the issue to be as well, sorry if I worded it incorrectly or unclearly.

**Comment by rhc54** [comment]
Got it - see #1397

**Comment by awlauria** [comment]
Thanks! I can confirm that the above patch works in my setup.
