### ISSUE TITLE
Wrong string in --output tag

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#1405]
## Background information

I'm using the last embedded OpenPMIx/PRRTE inside Open MPI master (hashes below).

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

https://github.com/openpmix/prrte/commit/0b580da7c8952a95a39a2cdb5d13b3453fb934ce

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

https://github.com/openpmix/openpmix/commit/41f4225d6fb806ff218eb229a9a25baf5a97c5fa

### Please describe the system on which you are running

* Operating system/version: RHEL 8.4
* Computer hardware: ppc64le
* Network type: Ethernet, Infiniband

-----------------------------

## Details of the problem

The `--output tag` is reporting the hostname and IP of the `prterun` process not that of the individual processes.

```shell
shell$ prterun  --map-by ppr:2:node --host f5n18:20,f5n17:20 --output tag hostname
[prterun-f5n18-100629@1,0]<stdout>: f5n18
[prterun-f5n18-100629@1,2]<stdout>: f5n18
[prterun-f5n18-100629@1,1]<stdout>: f5n17
[prterun-f5n18-100629@1,3]<stdout>: f5n17
```

**Comment by rhc54** [comment]
No, it actually isn't, though it might look that way. What it is reporting is the "nspace" and "rank" of the individual processes. The "nspace" is composed as the "session" name and the "local jobid". The "session name" is defined by `prterun` as `hostname-pid`. So the result looks like:

`<hostname-pid-of-prterun>@<local jobid>,<rank>`

Hope that helps

**Comment by jjhursey** [comment]
Yeah you are correct. I thought it printed the pid/hostname of the process reporting the stdout. Below is the behavior of OMPI 4.1.x:
```
shell$ mpirun --npernode 2 --host f5n18:20,f5n17:20 --tag-output hostname
[1,0]<stdout>:f5n18
[1,1]<stdout>:f5n18
[1,2]<stdout>:f5n17
[1,3]<stdout>:f5n17
```
First digit is essentially the 'namespace', second is the rank.
```
   -tag-output|--tag-output 
                         Tag all output with [job,rank]
```

It would be useful if we had an output option that listed `[namespace,rank][host_of_rank:pid_of_rank]<stream>`

**Comment by rhc54** [comment]
> First digit is essentially the 'namespace', second is the rank.
> 
> ```
>    -tag-output|--tag-output 
>                          Tag all output with [job,rank]
> ```

Yeah, I think that would be less confusing - I can make that change easily enough. Good suggestion!

> It would be useful if we had an output option that listed [namespace,rank][host_of_rank:pid_of_rank]<stream>

Easy enough to do - what do you think we should call that option?

**Comment by jjhursey** [comment]
The existing output for `--output tag` is fine. No need to change if you don't want.

Maybe `--output tag-detailed` or `--output tag-with-host` or something for that option. I don't have a strong preference.

**Comment by rhc54** [comment]
Hmmm...well, how about we do this?

`--output tag` will work the same as before - `[local jobid,rank]<stream>:`
`--output tag-detailed` will output `[local jobid,rank][host:pid]<stream>:`
`--output tag-fullname` will output `[full jobid,rank]<stream>:`
` --output tag-detailed,tag-fullname` will output `[full jobid,rank][host:pid]<stream>:`

Should help with backward compatibility. Make sense?

**Comment by jjhursey** [comment]
Sounds good to me. Thanks!

**Comment by rhc54** [comment]
Okay, all done - https://github.com/openpmix/openpmix/pull/2669
