### ISSUE TITLE
SLURM: "--cpu-bind=none" unrecognized option

### ISSUE THREAD

**Issue by jsquyres** [openpmix/prrte#1419]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Open MPI main submodule pointer, which is currently 154b42b6c292f965987ed994e42f9ea4b4e8e072, and appears to be prte master HEAD.

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

Open MPI main submodule pointer, which is currently https://github.com/openpmix/openpmix/commit/73aff171cb53659643c2a341a627f4ce1178df60, and appears to be pmix master HEAD.

### Please describe the system on which you are running

* Operating system/version: RHEL 6 (I know, I know...)
* Computer hardware: x86 + ethernet
* Network type: usNIC

-----------------------------

## Details of the problem

I built Open MPI main HEAD (https://github.com/open-mpi/ompi/commit/9f953673d3f57ecd028a593b8c97078a6487890b), with the git submodules as listed above, and am just trying to run a non-MPI executable via `mpirun`:

```
$ srun hostname
mpi016
mpi014
$ mpirun hostname
--------------------------------------------------------------------------
An PRTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
<...hang...>
```

If I run with `mpirun --mca plm_base_verbose 100 hostname`, I can see the exact `srun` command that was fork/exec'ed from `mpirun`.  Trying to run that `srun` command manually, I see:

```
$ srun --ntasks-per-node=1 --kill-on-bad-exit --mpi=none --cpu-bind=none --ntasks=2 prted --prtemca ess "slurm" --prtemca ess_base_nspace "prterun-mpi005-15163@0" --prtemca ess_base_vpid "1" --prtemca ess_base_num_procs "3" --prtemca prte_hnp_uri "prterun-mpi005-15163@0.0;tcp://127.0.0.1,10.0.8.5,10.10.0.5,10.2.0.5,10.3.0.5:36214:8,16,16,16,16" --prtemca plm_base_verbose "100" --prtemca pmix_session_server "1"
srun: unrecognized option '--cpu-bind=none'
Try "srun --help" for more information
```

Granted, I have a pretty ancient version of SLURM:

```
$ srun --version
slurm 14.03.0
```

"But it works with Open MPI v4.1.x!" 😄

**Comment by rhc54** [comment]
The SchedMD folks "own" that module and made that change - the "old" version causes problems for newer versions of Slurm. I believe their response is that such old versions are not supported.

See the discussion here: https://github.com/openpmix/prrte/pull/1312

**Comment by gpaulsen** [comment]
Any way for Prrte to detect a non-pmix enabled SLURM and exit with an error message?

**Comment by rhc54** [comment]
It has nothing to do with PMIx - this is simply a question of the `srun` cmd line used to start the `prted` daemons. The cmd line syntax changed in Slurm 17.11, and SchedMD updated the plm/slurm module to support it. This breaks support for versions older than 17.11.

What I probably should do is have configure check the Slurm version and error out if older than 17.11 as PRRTE won't work there anyway - at least, it can't use the Slurm launcher. It will work fine with `ssh`, so it is only the launcher that is impacted.

**Comment by rhc54** [comment]
So here are the options I've identified:

1. you can argue with SchedMD about supporting the older Slurm versions. I know that our old workaround causes problems for newer Slurm, so some configure support would likely be required. I don't know if they are willing to entertain this method - it is up to you to convince them.
2. I can add configure logic to disable the Slurm launcher on older systems, but still allow the Slurm allocation to be detected. This would automatically default over to the ssh launcher, which will usually work. Issue here is that the jobs launched this way would not be under the Slurm accounting system. They still get accounted for, but only at the aggregated allocation level (and not per-job). I don't know if a warning should be emitted, or where such a warning should be done to ensure it is seen.
3. I can add configure logic to simply error out if Slurm older than 17.11 is detected.

Any preferences?

**Comment by rhc54** [comment]
Having heard only crickets, I have put together a solution that should minimize impact on users. I chose to go with a fourth approach where we check the Slurm version level at runtime: https://github.com/openpmix/prrte/pull/1434

Rationale: I can see SchedMD's point about matching their official support policies. However, not everyone can easily update and we would like to provide a seamless transition from our past support. Doing the check at configure time isn't really a solution as

(a) PRRTE could easily have been built with a supported version of Slurm present and then installed in an older Slurm environment (e.g., from a packager)
(b) we really only check if fork and exec are present, not requiring Slurm to actually be installed for the Slurm components to build. So adding something that checked Slurm version at configure would be a significant change in build behavior.

Obviously, invoking "sinfo" each time one executes an application would be annoying (though it doesn't really seem to hurt that much), so I provided an MCA parameter for turning off the check. Hopefully, the first time the user failed they would either get the system admin to upgrade Slurm, or set the MCA param to avoid the Slurm launcher. People in environs where they know they meet the minimum requirement can just set the param to skip the test.

**Comment by wickberg** [comment]
Versions of Slurm prior to 21.08.8 and 20.11.9 are [inherently insecure](https://lists.schedmd.com/pipermail/slurm-announce/2022/000072.html), and are unsupported by SchedMD.
Versions prior to 17.11 - over five years old - have not been supported for years, and I would strongly encourage any site running such an old version to upgrade immediately.
I would discourage other modern HPC tooling from trying to adapt to such old versions, and would recommend against any changes here.

**Comment by rhc54** [comment]
Fair enough - like I said, I feel this is up to you. Would it make sense for us to output a message explaining why the launcher doesn't work and recommending upgrade? I'm just trying to find a middle ground so we avoid getting hit with "bug" reports. Since we will fail out-of-the-box in those environments, perhaps a message indicating why and recommending upgrade would avoid the bug report - and might encourage upgrade.

Would that be acceptable?

**Comment by rhc54** [comment]
Okay, I have modified #1434 so we fail on the pre-17.11 versions (due to the `--cpu-bind=none` problem). When we fail, I check the version number to verify it is in fact the pre-17.11 situation, and then emit a warning prior to aborting:
```text
The Slurm process starter requires a minimum Slurm version level
of v17.11. The detected version being used here is:

  Major: xx
  Minor: x

SchedMD strongly recommends that you upgrade your Slurm version.
Versions of Slurm prior to 21.08.8 and 20.11.9 have been found
to have a security issue and are not supported - therefore, it
is recommended that you upgrade to a level at or above those
versions.

It is recognized that upgrades can take some time to complete.
In the interim, you can execute your job by ignoring the Slurm
process starter via the following MCA parameter:

  Environment: PRTE_MCA_plm=^slurm
  Cmd line: --prtemca plm ^slurm
  Default MCA param file: plm = ^slurm

This will result in use of the ssh process starter. This will have
no impact on your application, but will result in any accounting
being done solely at the allocation level instead of per-job.
```
I believe this will provide sufficient information to allow people
to move forward, hopefully with an upgrade as quickly as that
can be accomplished.
