### ISSUE TITLE
pmix_tool_basename not found during remote prte startup

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1435]
Issue with test using prrte-3.0.0rc1/pmix-4.2.0rc1 for missing symbol due to remote env propogation.

## Background information

Doing initial test and noticed undefined symbol `pmix_tool_basename` for `prte` in `libprrte.so.3`, which is true as that symbol is defined in `libpmix.so.2`.  

The problem is that we do not get env propagation during this bootstrap from ssh and therefore need a way to resolve `LD_LIBRARY_PATH` on remote machine.  We can not use `-x LD_LIBRARY_PATH` b/c this is during the actual bootstrap of remote daemon. 

Q: Could this be a typo: `pmix_tool_basename` vs. `prte_base_toolname`?

### Versions of PMIx Reference RTE (PRRTE) and PMIx library
 - pmix-4.2.0rc1 tarball
 - prrte-3.0.0rc1 tarball

### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem
- fail to resolve the `pmix_tool_basename` in prte

```shell
batch3: $ prte  --report-uri dvm.uri --hostfile hosts &
[1] 768113
batch3: $ /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/bin/prted: symbol lookup error: /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib/libprrte.so.3: undefined symbol: pmix_tool_basename

[1]+  Exit 127                prte --report-uri dvm.uri --hostfile hosts
batch3: $ nm /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib/libprrte.so.3 | grep _tool_basename
                 U pmix_tool_basename
00000000001bd698 B prte_tool_basename
batch3: $ nm /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/p | grep _tool_basename
batch3: $ ldd /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/bin/prted | grep pmix
        libpmix.so.2 => /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/pmix-4.2.0rc1/lib/libpmix.so.2 (0x0000200000240000)
batch3: $ nm /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/pmix-4.2.0rc1/lib/libpmix.so.2 | grep _tool_basename
00000000002c2318 B pmix_tool_basename
batch3: $
```

- above works fine if we add `LD_LIBRARY_PATH` to our shell rc file

- local run works fine b/c we have `LD_LIBRARY_PATH` defined

```shell
batch3: $ prte  --report-uri dvm.uri &
[1] 767561
batch3: $ DVM ready

batch3: $ prun --dvm-uri file:dvm.uri -np 1 hostname
batch3
batch3: $ pterm --dvm-uri file:dvm.uri
TERMINATING DVM...DONE
[1]+  Done                    prte --report-uri dvm.uri
batch3: $ 
```

**Comment by naughtont3** [comment]
@rhc54 Should the symbol name be the `prte_tool_basename` (so it is found in libprte.so)?  Otherwise, what's best way to have rpath or the like to ensure we find the required libpmix.so?

**Comment by rhc54** [comment]
No, that symbol name is correct. The problem is that the remote `prted` isn't finding the PMIx library it was built against - this is just the first symbol that would fail. What you should do is configure PRRTE with `--enable-prte-prefix-by-default` so it adds the `LD_LIBRARY_PATH` to the `prted` ssh line.

**Comment by naughtont3** [comment]
Ah, yes good point

Hmm,  looks like that was included in the prte configure.

```
[naughton@login1.summit test-new-prrte]$ prte_info -c | more
           Configured by: naughton
           Configured on: Mon Aug 15 19:30:02 UTC 2022
          Configure host: login1
  Configure command line: '--without-lsf' '--without-slurm'
                          '--prefix=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1'
                          '--enable-prte-prefix-by-default'
                          '--with-libevent=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/libevent-2.1.12-stable'
                          '--with-hwloc=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/hwloc-2.7.1'
                          '--with-pmix=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/pmix-4.2.0rc1'
...
```

**Comment by naughtont3** [comment]
hmm, i'll look at the argv to see what is actually getting placed in `ssh ... prte` lines

**Comment by rhc54** [comment]
Huh - is this using the ssh launcher? Or some other one?

**Comment by rhc54** [comment]
yeah, set `--prtemca plm_base_verbose 5` to see what is being used

**Comment by naughtont3** [comment]
yes, using ssh launcher.  and should have slurm/lsf bits disabled to avoid any confusions in rmaps/plm/etc.

**Comment by naughtont3** [comment]
```
batch2: $ prte   --prtemca plm_base_verbose 5     --hostfile hosts     --report-uri dvm.uri      
[batch2:1916005] [prte-batch2-1916005@0,0] plm:ssh: final template argv:
        /usr/bin/ssh <template> PRTE_PREFIX=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1;export PRTE_PREFIX;LD_LIBRARY_PATH=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;DYLD_LIBRARY_PATH=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib:$DYLD_LIBRARY_PATH;export DYLD_LIBRARY_PATH;/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/bin/prted --prtemca ess "env" --prtemca ess_base_nspace "prte-batch2-1916005@0" --prtemca ess_base_vpid "<template>" --prtemca ess_base_num_procs "3" --prtemca prte_hnp_uri "prte-batch2-1916005@0.0;tcp://127.0.0.1,10.134.0.42,10.41.0.42,128.219.134.82:37641:8,18,16,26" --prtemca prte_routed_radix "128" --prtemca plm_base_verbose "5" --prtemca pmix_session_server "1" --prtemca plm "ssh" --tree-spawn --prtemca prte_parent_uri "prte-batch2-1916005@0.0;tcp://127.0.0.1,10.134.0.42,10.41.0.42,128.219.134.82:37641:8,18,16,26"
/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/bin/prted: symbol lookup error: /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib/libprrte.so.3: undefined symbol: pmix_tool_basename
/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/bin/prted: symbol lookup error: /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib/libprrte.so.3: undefined symbol: pmix_tool_basename
batch2: $ echo $?
127
batch2: $
```

**Comment by rhc54** [comment]
Is the library out there and in the location pointed to?

**Comment by naughtont3** [comment]
Yes, as long as I set the `LD_LIBRARY_PATH` say via `$HOME/.bashrc` things startup ok.  This is a very fundamental/basic thing, so that's why i was surprised.

**Comment by naughtont3** [comment]
I wonder if its a path length?

**Comment by rhc54** [comment]
what does `ldd` show on `prted`?

**Comment by rhc54** [comment]
I guess you could also run that ssh command by hand and see if it works - you might get more error messages out of it that way

**Comment by naughtont3** [comment]
```
batch2: $ ldd /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/bin/prted 
        linux-vdso64.so.1 (0x0000200000050000)
        libprrte.so.3 => /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib/libprrte.so.3 (0x0000200000070000)
        libpmix.so.2 => /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/pmix-4.2.0rc1/lib/libpmix.so.2 (0x0000200000240000)
        libutil.so.1 => /lib64/libutil.so.1 (0x0000200000530000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000200000560000)
        libevent_core-2.1.so.7 => /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/libevent-2.1.12-stable/lib/libevent_core-2.1.so.7 (0x0000200000590000)
        libevent_pthreads-2.1.so.7 => /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/libevent-2.1.12-stable/lib/libevent_pthreads-2.1.so.7 (0x0000200000600000)
        libhwloc.so.15 => /sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/hwloc-2.7.1/lib/libhwloc.so.15 (0x0000200000630000)
        libm.so.6 => /lib64/power9/libm.so.6 (0x00002000006d0000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x0000200000800000)
        libpthread.so.0 => /lib64/power9/libpthread.so.0 (0x0000200000a00000)
        libc.so.6 => /lib64/power9/libc.so.6 (0x0000200000a50000)
        /lib64/ld64.so.2 (0x0000200000000000)
        libz.so.1 => /lib64/libz.so.1 (0x0000200000c60000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x0000200000ca0000)
batch2: $ 
```

**Comment by rhc54** [comment]
Ah, I see the problem!! PRRTE is adding it's library path, but NOT that of PMIx. So `libpmix` won't be found. Have to ponder how to solve that one.

**Comment by naughtont3** [comment]
But it includes the `$LD_LIBRARY_PATH` at end, does that not get expanded there and shipped over?

From the PLM "ssh template" output
```
    LD_LIBRARY_PATH=/sw/summit/ums/ompix/DEVELOP/gcc/9.1.0/install/prrte-3.0.0rc1/lib:$LD_LIBRARY_PATH;
```

**Comment by rhc54** [comment]
No - remember, that is being evaluated on the backend. So what we are doing is effectively editing the backend `LD_LIBRARY_PATH` and inserting fixed values - we are _not_ exporting your local `LD_LIBRARY_PATH` in its entirety to the backend.

**Comment by naughtont3** [comment]
Okay, yes.  That's the point of inserting the ...prrte-3.0.0rc1/lib:... in the first place.  Duh.

**Comment by naughtont3** [comment]
So back to earlier thought, would it be better avoid using the `pmix_tool_basename` and instead use the `prte_tool_basename` symbol in prte lib?

**Comment by naughtont3** [comment]
Ah, but we're using all the pmix bits now so we'll fail on next symbol.  nevermind

**Comment by rhc54** [comment]
i'm working on it - hopefully this evening. gotta run for a minute.

**Comment by rhc54** [comment]
@naughtont3 Can you please confirm that https://github.com/openpmix/prrte/pull/1438 fixes the problem? You'll need to update to PMIx master as well.

**Comment by naughtont3** [comment]
@rhc54 yes fixed the ssh/env issue. Thanks!
