### ISSUE TITLE
Issue with multiple app contexts and PMIX_LOCAL_RANK confused with PMIX_APP_RANK

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#1445]
I was investigating an issue in Open MPI with `MPI_Comm_spawn_multiple` and I think the core issue is in PRRTE. See the comment [here](https://github.com/open-mpi/ompi/issues/10631#issuecomment-1219968893) for details.

It seems that `PMIX_LOCAL_RANK == PMIX_APP_RANK` in this scenario, where they should be different.

I only have an MPI reproducer [here](https://gist.github.com/jjhursey/707fe04d164f93707933b8a619106ab8) at the moment.

**Comment by jjhursey** [comment]
Best I can tell there is something [here in rmaps_base_ranking.c](https://github.com/openpmix/prrte/blob/master/src/mca/rmaps/base/rmaps_base_ranking.c#L103) that needs adjusting, but I can't see how to do it easily.

The `options->last_rank` is the last global rank, but the `lrank` needs to start at `1` for the second app context instead of `0`. So we need to know the last local rank for this job on this node. Right?

**Comment by rhc54** [comment]
Agreed, this is a bug in PRRTE ranking - I'll take a look at it. As I said over there, though, sm components should really be looking at node rank, not local rank. Nathan and I had that discussion and settled on that solution long ago.

**Comment by rhc54** [comment]
BTW: the rationale behind node rank lies in the fault tolerance area. If a proc from a given app dies on a node, and then a proc from that app (either the one that died or some migration) is restarted on that node, then the local rank gets reused - but the node rank does not. If you are using local rank, the app will crash on that node as the conflict will take down all the procs that were "connected" to that local rank. Before you had FT, it didn't really make much difference - now that OMPI is supporting FT, it is critical.

**Comment by jjhursey** [comment]
Thanks for the quick fix. I'll test it out this morning.

Thanks for the note about the node_local for FT. That makes sense. I'm hesitant to make the change since I cannot test it - I don't want to accidentally break something. Maybe @abouteiller would be in a better position to try the change.

**Comment by jjhursey** [comment]
Pr https://github.com/open-mpi/ompi/issues/10631#issuecomment-1220741113 this patch fixed the issue. I also filed a PR on the OMPI side for the node_local item.

Thanks!
