### ISSUE TITLE
Error in pmix_mca_base_component_path, stack smashing detected

### ISSUE THREAD

**Issue by anderbubble** [openpmix/prrte#1521]
### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)

[v3.0.0rc1](https://github.com/openpmix/prrte/releases/tag/v3.0.0rc1)

##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)

```
pmix-4.2.1-1.el9.aarch64
```

### Please describe the system on which you are running

* Operating system/version: Tried on Rocky Linux 8 and 9
* Computer hardware: Tried on aarch64 and x86_64 virtual machines
* Network type: Ethernet only

-----------------------------

## Details of the problem

I've tried building prrte in various permutations of

- manual cofigure / make / make install
- rpmbuild
- mock
- aarch64
- x86_64
- rocky linux 8
- rocky linux 9
- inside an apptainer
- no containerization

In all cases I've seen so far, I get output like this immediately on execution of the `prte` binary:

```console
$ ~/opt/prrte-3.0.0rc1/bin/prte
--------------------------------------------------------------------------
The pmix_mca_base_component_path MCA variable was used to add paths to
search for PMIx components.  At least one directory failed to add
properly:

    e?

Check to make sure that this directory exists, is readable, etc.
--------------------------------------------------------------------------
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

The value presented is random, implying to me that something is reading memory it shouldn't be reading.

Please advise.

**Comment by rhc54** [comment]
Most likely reason would be some missing cherry-pick commit from upstream - let me take a peek.

**Comment by rhc54** [comment]
Hmmm...I just rebuilt with the HEAD of the PMIx v4.2 and PRRTE v3.0 branches, and everything ran just fine. I'm guessing that perhaps you didn't pickup today's HEAD of those branches?

Mind you, I am not building from srpm's but rather directly from a git checkout. Still, barring something still wrong with the spec files, I should think them equivalent. The error, however, is something I recall seeing earlier - and was fixed in a09d82aa on Sept 9th.

**Comment by rhc54** [comment]
Ohhhh...I see the problem! I had forgotten I had actually tagged an rc1 and posted it. I shall change the version in the branch to rc2 and correct my announcement message.

**Comment by rhc54** [comment]
I have posted both PMIx v4.2.2rc1 and PRRTE v3.0.0rc2 - please update to those and they will fix the problem.

**Comment by anderbubble** [comment]
@rhc54 I'm doing this now. I noticed that PMIx v4.2.2rc1 doesn't include the new BuildRequires in its specfile, and PRRTE v3.0.0rc2 doesn't include the latest change. Can those be included before final?

**Comment by rhc54** [comment]
They don't??? I'll take another look - thought I had all up-to-date commits backported, and I know I saw BuildRequires in the list (and mentioned in the NEWS). Definitely want them there.

**Comment by anderbubble** [comment]
Yeah, weird. I checked the tag for PRRTE v3.0.0rc2, and _some_ of it is in there; but now I'm seeing that _none_ of them appear in the spec that I got from the SRPM in assets.

**Comment by rhc54** [comment]
Maybe? Certainly not intentionally. I'll double-check the rpm build.

Can you tell me what you think is missing from PRRTE v3.0.0rc2?

**Comment by anderbubble** [comment]
@rhc54 if I pull down and install fresh copies of the srpms:

```console
# curl -LO https://github.com/openpmix/prrte/releases/download/v3.0.0rc2/prrte-3.0.0rc2-1.src.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1319k  100 1319k    0     0  6945k      0 --:--:-- --:--:-- --:--:-- 6945k
[root@janderson-wwctl1 tmp]# curl -LO https://github.com/openpmix/openpmix/releases/download/v4.2.2rc1/pmix-4.2.2rc1-1.src.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1620k  100 1620k    0     0  5977k      0 --:--:-- --:--:-- --:--:-- 5977k
[root@janderson-wwctl1 tmp]# rpm -i pmix-4.2.2rc1-1.src.rpm prrte-3.0.0rc2-1.src.rpm 
warning: user mpiuser does not exist - using root
warning: group mpiuser does not exist - using root
warning: user mpiuser does not exist - using root
warning: group mpiuser does not exist - using root
warning: user mpiuser does not exist - using root
warning: group mpiuser does not exist - using root
warning: user mpiuser does not exist - using root
warning: group mpiuser does not exist - using root
```

I only see the original BuildRequires in the contained spec for pmix, and none for prrte.

```console
# grep BuildRequires ~/rpmbuild/SPECS/pmix-4.2.2rc1.spec 
BuildRequires: libevent-devel
# grep BuildRequires ~/rpmbuild/SPECS/prrte-3.0.0rc2.spec
```

Further, it looks like PRRTE v3.0.0rc2 doesn't contain e44125c23f9277bd52528fc5f938842933571eaf.

**Comment by rhc54** [comment]
Weird - okay, let me try to chase it down.

**Comment by rhc54** [comment]
I did some digging and found that there were some updates that didn't get into PRRTE v3.0.0rc2 for some reason - seems I simply missed them. This includes the one you cite. I see all the BuildRequires there now.

I'll take a look at PMIx tomorrow. Probably need to post new release candidates, but let's wait a little and see what else comes back.

**Comment by rhc54** [comment]
When I check the PMIx v4.2.2 spec file, it looks like all the BuildRequires are present:
```shell
$ cat contrib/pmix.spec | grep Build
BuildRoot: /var/tmp/%{name}-%{version}-%{release}-root
BuildRequires: gcc
BuildRequires: make
BuildRequires: libevent-devel
BuildRequires: hwloc-devel
BuildRequires: python3-devel
BuildRequires: zlib-devel
# Build Section
```
and I see the relevant commits as having been ported. I wonder why you didn't find them in the srpm itself?

**Comment by rhc54** [comment]
Aha - I found the problem! I did indeed create the srpm from a location that didn't have the updated spec file. Will have to keep that in mind going forward.
