### ISSUE TITLE
prun - add qualifier for namespace arg

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1587]
## Background information

Currently with `prun`, all arguments for the DVM take a qualifier (prefix) with the exception of passing a namespace. Should this case be made to match other cases and have a qualifier, e.g., "`ns:<namespace>`?

### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)
 - v3.0.x

##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)
 - v4.2.x (and previous)
 
### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

When making a change for the ompi schizo options, we included a `--dvm XXX` to allow for using a DVM with `mpirun`.  To simplify the user options, to more closely align w/ `prun` we decided to make the option required so that you must provide a URI file, pid, etc. for the target DVM.  In the case you want to "search" for an existing DVM (instead of providing specific URI) we chose to use `--dvm search`.  This is not perfect b/c this eliminates the  ability to have a namespace (`--dvm <namespace>`) that is called "search". 

This is unlikely, but raised the point as to why not just include a prefix to avoid this issue like all other options, e.g., "file:dvm.uri", "pid:1234", "pid:file:mypid.txt".  

Proposed change would be to require namespaces to have "ns:<namespace>".  This would avoid conflict with "search" mentioned above, but also allow for things like reading a namespace from a file, etc.

```shell
shell$ prte --report-uri dvm.uri &
shell$ prun --dvm-uri file:dvm.uri --np 2 ./hello_world
shell$ mpirun --dvm file:dvm.uri --np  2 ./hello_mpi

shell$ prun --dvm-uri namespaceA --np 2 ./hello_world
  # changed to
shell$ prun --dvm-uri ns:namespaceA --np 2 ./hello_world

shell$ mpirun --dvm namespaceA --np  2 ./hello_mpi
  # changed to
shell$ mpirun --dvm ns:namespaceA --np  2 ./hello_mpi
```

**Comment by rhc54** [comment]
Where did we land on this?

**Comment by naughtont3** [comment]
i believe it is done, but i'll give it one more test now to make sure

**Comment by naughtont3** [comment]
yep, works.

tested with ompi main (1456f84ff3) and latest openpmix (db28a417) / prte master (a61e7bee8b)

```
beaker: (main)$ mpirun --dvm ns:prte-beaker-1407713 --np 1 hostname
beaker
beaker: (main)$
```

```
beaker: (main)$ prte --report-uri dvm.uri &
DVM ready

beaker: (main)$ cat dvm.uri 
prte-beaker-1408861@0.0;tcp4://127.0.0.1:34181
v5.0.0a1
beaker: (main)$ head -1 dvm.uri | awk -F@ '{print $1}'
prte-beaker-1408861

beaker: (main)$ prun --namespace prte-beaker-1408861 --np 1 hostname
beaker
beaker: (main)$ prun --dvm-uri file:dvm.uri --np 1 hostname
beaker
beaker: (main)$ prun --namespace prte-beaker-1408861 --np 1 hostname
beaker
beaker: (main)$ mpirun --dvm file:dvm.uri --np 1 hostname
beaker
beaker: (main)$ mpirun --dvm ns:prte-beaker-1408861 --np 1 hostname
beaker
beaker: (main)$ pterm --dvm-uri file:dvm.uri
TERMINATING DVM...DONE
[3]-  Done                    prte --report-uri dvm.uri
beaker: (main)$
```

**Comment by rhc54** [comment]
Thanks!
