### ISSUE TITLE
Commit "Fix hetero topology operations" caused random hang and segfault

### ISSUE THREAD

**Issue by wzamazon** [openpmix/prrte#1592]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)

Commit adc8fd769d3808f8f0f33ffbdf198111f4f12e43

##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)

Commit 1f0b53f482a659e3a19e20983fc1b0637b52bb14

### Please describe the system on which you are running

* Operating system/version: amazon linux  2
* Computer hardware: Intel XPU
* Network type: EFA 

-----------------------------

## Details of the problem

Our CI has been randomly hang or segfault, I was able to associate the hang with commit adc8fd769d3808f8f0f33ffbdf198111f4f12e43 in prrte, whose comment says

```
    Fix hetero topology operations
    
    Resolve some race conditions that resulted in hangs
    and potentially incorrect topology assignments.
```

When hang happens, it was always when waiting for DVM to be alive. code is:

https://github.com/openpmix/prrte/blob/f99fe3ff03b6169175155389777b71dec01c2044/src/tools/prte/prte.c#L804

When segfault happens, it was in `bind_generic` , code is:

https://github.com/openpmix/prrte/blob/f99fe3ff03b6169175155389777b71dec01c2044/src/mca/rmaps/base/rmaps_base_binding.c#L96

and the reason for the segfault is `node->available` is NULL.

**Comment by wzamazon** [comment]
@rhc54 I would like to keep working on the issue, but I am not familiar with the code base.

Can you give some suggestion about how to look into this?

**Comment by rhc54** [comment]
That must be a _very_ old hash - I'm searching and can't find it on the first page or two of the commit history. Why don't you try updating both PRRTE and PMIx - I'm pretty sure this will disappear.

**Comment by wzamazon** [comment]
Indeed. After I update to latest master branch of prrte. the issue went away.

Open MPI main branch is impacted by this still. I think OMPI need to update PRRTE pointer.

**Comment by wzamazon** [comment]
@rhc54 

After I upgrade to latest master for prrte and openpmix. Though the original random hang was fixed, I now encounter a different hang. The hang happens consistently for certain executable, and happens at a different place:

https://github.com/openpmix/prrte/blob/f99fe3ff03b6169175155389777b71dec01c2044/src/tools/prte/prte.c#L1149

I am not sure whether the two hangs are related.

**Comment by rhc54** [comment]
Not enough info to know. All you are citing is the event loop where the DVM waits for job completion. It means that we have successfully started all the PRRTE daemons and launched the job, so the question would be (a) is it your application that is hanging and not completing, or (b) is PRRTE not realizing that your application completed?

First thing to look at is: is your application completing, or is it hanging?

**Comment by rhc54** [comment]
Or do you have some evidence to indicate that PRRTE itself is hanging, perhaps in some intermediate state?

**Comment by wzamazon** [comment]
Sorry, my bad. The application was started, and this is a problem with the application itself. Not prrte issue.
