### ISSUE TITLE
MCA parameter `no_tree_spawn` is not passed correctly

### ISSUE THREAD

**Issue by s417-lama** [openpmix/prrte#1611]
### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)

Built the main branch of Open MPI:
https://github.com/open-mpi/ompi/commit/1dd8dc43b05564941a8570fbec36055aa82ed701

So, this version of PRRTE should be installed together:
https://github.com/openpmix/prrte/commit/ca2bf3aeab38261ae7c88cea64bc782c949bd76e

##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)

https://github.com/openpmix/openpmix/commit/250004266bc046c6303c8531ababdff4e1237525

### Please describe the system on which you are running

* Operating system/version: RHEL 8.4 (4.18.0-305.25.1.el8_4.x86_64)

-----------------------------

## Details of the problem

The `plm_rsh_no_tree_spawn` MCA param was supported in previous versions, but it seems to have no effect in the current version.
I see that the option is still in the current source code, but I could not pass the commandline MCA option to the runtime.

I checked the behavior by specifying `dummy` as the hostname and `echo` as the `ssh/rsh` command to see what params were passed to `ssh/rsh`.
```shell
shell$ mpirun --host dummy --prtemca prte_ssh_agent echo --prtemca prte_ssh_no_tree_spawn true -n 1 hostname
dummy PRTE_PREFIX=<...>;export PRTE_PREFIX;LD_LIBRARY_PATH=<...>:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;DYLD_LIBRARY_PATH=<...>:$DYLD_LIBRARY_PATH;export DYLD_LIBRARY_PATH;/path/to/prted --prtemca ess "env" --prtemca ess_base_nspace "prterun-<host>-3853651@0" --prtemca ess_base_vpid 1 --prtemca ess_base_num_procs "2" --prtemca prte_hnp_uri "prterun-<host>-3853651@0.0;tcp://<...>" --prtemca prte_ssh_agent "echo" --prtemca prte_ssh_no_tree_spawn "true" --prtemca pmix_session_server "1" --prtemca plm "ssh" --tree-spawn --prtemca prte_parent_uri "prterun-<host>-3853651@0.0;tcp://<...>
```

The `prte_ssh_agent` option was correctly passed, but the `prte_ssh_no_tree_spawn` option was not correctly passed, as the `--tree-spawn` option was set for `prted`.

Has the `no_tree_spawn` option been disabled, or am I specifying the MCA param in a wrong form?

**Comment by rhc54** [comment]
This `--prtemca prte_ssh_no_tree_spawn` isn't correct - try `--prtemca plm_ssh_no_tree_spawn`

**Comment by s417-lama** [comment]
Tried, but `--tree-spawn` is still there:
```shell
shell$ mpirun --host dummy --prtemca prte_ssh_agent echo --prtemca plm_ssh_no_tree_spawn true -n 1 hostname
dummy PRTE_PREFIX=<...>;export PRTE_PREFIX;LD_LIBRARY_PATH=<...>:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;DYLD_LIBRARY_PATH=<...>:$DYLD_LIBRARY_PATH;export DYLD_LIBRARY_PATH;/path/to/prted --prtemca ess "env" --prtemca ess_base_nspace "prterun-<host>-3600123@0" --prtemca ess_base_vpid 1 --prtemca ess_base_num_procs "2" --prtemca prte_hnp_uri "prterun-<host>-3600123@0.0;tcp://<...>" --prtemca prte_ssh_agent "echo" --prtemca plm_ssh_no_tree_spawn "true" --prtemca pmix_session_server "1" --prtemca plm "ssh" --tree-spawn --prtemca prte_parent_uri "prterun-<host>-3600123@0.0;tcp://<...>"
```

**Comment by rhc54** [comment]
Combination of two things: an issue in the framework designation, and we didn't accept "true" or "false" as values (had to be an integer). I've corrected the first and extended support for bool values to include the second.

See https://github.com/openpmix/prrte/pull/1612 and https://github.com/openpmix/openpmix/pull/2856
