### ISSUE TITLE
PLM: need a HPE PALS component

### ISSUE THREAD

**Issue by hppritcha** [openpmix/prrte#1628]
Need for ANL Aurora system.  We will need this as its the simplest way to acquire SS11 VNI info.

**Comment by rhc54** [comment]
I believe you need to complete/extend the `pnet/sshot` component per our exchange with HPE.

**Comment by hppritcha** [comment]
Turns out that the vendor simplified things somewhat starting with an updated CXI provider.  As long as a process is a child of slurmstepd or the pals equivalent of slurmstepd that the env. is set up such that the CXI provider will use the right VNI credentials under the covers if the application doesn't explicitly provide them in the call to ```fi_domain``` and ```fi_endpoint```.  But, for the general case we would want to modify pnet/sshot to crack these env. variables and pass them along in a PMIx way to the application processes.

**Comment by hppritcha** [comment]
closed via #1648
