### ISSUE TITLE
showing rml params with prte_info 

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1676]
The `prte_info` tool does not show the registered RML params when using `prte_info --all`, but the params can be shown using `prte_info --param rml`. 

low-priority item, but adding issue to capture details for later review

### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)

 - prte main @ 10496e38a0
 - openpmix main @ 4557af99
 
### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

The RML code is not under the `src/mca/` tree, instead it is in `src/rml/`.  The function `prte_rml_register()` in `rml.c` registers the params and this function is called at the tail end of `prte_register_params()`, which is called at `src/tools/prte_info/components.c:146`.  So it should be getting registered during the init of the `prte_info` tool.  And the fact that we can see it with `prte_info --param rml` proves it gets slurped up.

But seems we are treating this slightly different from the MCA component dirs.  I didn't see it with `prte_info --internal` either.

Example command-line to show behavior.

```shell
shell$ prte_info --all | grep rml_base_radix
```

```shell
shell$ prte_info --param rml 
```

**Comment by rhc54** [comment]
The command `prte_info --internal` just returns the components that are available in each framework. Sine the `rml` is no longer a framework, it won't appear in that list.

Rest is fixed by #1677
