### ISSUE TITLE
XML mapping utility

### ISSUE THREAD

**Issue by mshanthagit** [openpmix/prrte#1708]
Thank you for taking the time to submit an issue!

## Background information
prrte has a feature to use hwloc info and display process bindings and mappings for a given system in a text format. Presenting this output in a human-readable format such as XML would be useful.

### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)
git master @ 4725d89abe53c52343eeb49c90986c4d407d6392

##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)
git master @ bb348161d8bf929dd46acb7b0e3026dbe473c933
### Please describe the system on which you are running

* Operating system/version: CentOS Linux release 8.3.2011
* Computer hardware: AMD EPYC 7763 64-Core Processor
* Network type: N/A

-----------------------------

## Details of the problem
The XML mapping utility will use already exising "display map" capability within prrte to display the output in an XML format.

Here is an output from a simple test example:
```text
prterun --prtemca hwloc_use_topo_file topo.xml --prtemca ras_simulator_num_nodes 2 --map-by node:span:corecpu -n 2  --display map,cpu:parsable --personality ompi hostname
<?xml version="1.0" ?>
<map>
    <host name="nodeA0" slots="128" max_slots="128">
        <processors>
            <package id="0" cpus="0-63"/>
            <package id="1" cpus="64-127"/>
        </processors>

        <rank id="0" appid="0">
            <binding>
                <package id="0">
                    <core>0</core>

                </package>
            </binding>
        </rank>
    </host>
    <host name="nodeA1" slots="128" max_slots="128">
        <processors>
            <package id="0" cpus="0-63"/>
            <package id="1" cpus="64-127"/>
        </processors>

        <rank id="1" appid="0">
            <binding>
                <package id="0">
                    <core>0</core>

                </package>
            </binding>
        </rank>
    </host>
<!--
        Warning: This map has been generated with the DONOTLAUNCH option;
        The compute node architecture has not been probed, and the displayed
        map reflects the HEADNODE ARCHITECTURE. On systems with a different
        architecture between headnode and compute nodes, the map can be
        displayed using prterun's display `map /bin/true`, which will launch
        enough of the DVM to probe the compute node architecture.
 -->
</map>
```

**Comment by mshanthagit** [comment]
Note - I am not seeing the entire output I pasted in the "Details of the problem" section.

**Comment by rhc54** [comment]
> Note - I am not seeing the entire output I pasted in the "Details of the problem" section.

I fixed it - you just needed to enclose the output in literal text markers so GitHub doesn't eat the greater-than sign as designating something.

**Comment by rhc54** [comment]
Completed
