### ISSUE TITLE
OMPI cmd line processing converts all single-dash options to double-dash

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#1864]
### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)

PRRTE v3.0.x as well as master branches - OMPI v5.0.0 and main branches

## Details of the problem
The `schizo/ompi` component is promoting all single-dash command line options to double-dash prior to parsing the command line. The code is here:

https://github.com/openpmix/prrte/blob/27b5ff01fb20363474cde7e982014d30c52cd295/src/mca/schizo/ompi/schizo_ompi.c#L451-L482

The code doesn't discriminate between OMPI-owned command line options versus the application's command line options, which means that the app may get options that are not understood.

Please take a look more closely at the code. It may be that the app's options get restored after processing of the command line in this code snippet:

https://github.com/openpmix/prrte/blob/27b5ff01fb20363474cde7e982014d30c52cd295/src/mca/schizo/ompi/schizo_ompi.c#L597-L608

**Comment by rhc54** [comment]
@wenduwan

**Comment by wenduwan** [comment]
@rhc54 I did confirm that the `-` -> `--` conversion does **not** apply to application arguments. You pointed out the right place.

`parse_cli` makes a copy of the arguments, and converts `-` to `--` in the copied arguments. Then it is passed to
```
    rc = pmix_cmd_line_parse(pargv, ompishorts, ompioptions, NULL,
                             results, "help-schizo-ompi.txt");
```
This will find out where the user provided executable is in the arg list and stop there.

At the end the args after the executable are restored to the original value
```
    if (NULL != results->tail) {
        /* search for the leader of the tail */
        for (n=0; NULL != argv[n]; n++) {
            if (0 == strcmp(results->tail[0], argv[n])) {
                /* this starts the tail - replace the rest of the
                 * tail with the original argv */
                PMIX_ARGV_FREE_COMPAT(results->tail);
                results->tail = PMIX_ARGV_COPY_COMPAT(&argv[n]);
                break;
            }
        }
    }
```

**Comment by rhc54** [comment]
Very good - will close!
