### ISSUE TITLE
Problems dealing with shared TMPDIRs

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#1866]
I've been contacted about very long startup times for `mpirun` and `prte` on machines where `TMPDIR` points to a shared location:

> launching a single node/two process takes at least a full minute (seems to spend a lot of time stat()ing things in $TMPDIR, which we, arguably incorrectly, have on shared storage)

We used to detect this situation and at least emit a warning about it - and IIRC, we had perhaps included code to avoid hammering the shared file system?

Regardless, it appears at least some people still operate their clusters this way, so we are going to have to update PRRTE to recognize it and handle it better.

**Comment by rhc54** [comment]
@wenduwan I'm not sure this should be a blocker for PRRTE v3.0.3, but we should at least provide the warning in that release. Is this something you could help me out with? The shared TMPDIR detection code may be in OPAL - might not have made it across to PRRTE from there.

**Comment by wenduwan** [comment]
@rhc54 If you could provide some pointers to get me started, yes. I did a quick search in ompi and only saw this reference:


https://github.com/open-mpi/ompi/blob/55b295a19e5ce6580979c80c1555e218b3b58b09/ompi/runtime/ompi_rte.c#L1162-L1173


Is this what we are talking about here?

**Comment by jsquyres** [comment]
The code in question is here: https://github.com/open-mpi/ompi/blob/55b295a19e5ce6580979c80c1555e218b3b58b09/opal/util/path.c#L503

It's currently invoked by the shmem mmap component here: https://github.com/open-mpi/ompi/blob/55b295a19e5ce6580979c80c1555e218b3b58b09/opal/mca/shmem/mmap/shmem_mmap_module.c#L323

The back-end function may or may not be reliable in all the types of shared filesystems these days.  It might need some testing here.

Also, do we need to check this in more than just the shmem mmap component?

**Comment by rhc54** [comment]
Yeah, PMIx at least needs to check since we use shmem to pass info to the local clients. PRRTE itself doesn't care.

**Comment by rhc54** [comment]
Well, what do you know - PMIx already has the required function!

`bool pmix_path_nfs(char *fname, char **ret_fstype)`

in src/util/pmix_path.c. It's available to PRRTE as well. Just need to use it!

>  PRRTE itself doesn't care.

I have to take that back - PRRTE doesn't use the TMPDIR itself, but PRRTE _does_ set the head of the session directory tree and pass that to PMIx as well as OMPI. So PRRTE is the one effectively setting the TMPDIR for all three of our packages (at least, when `mpirun` is invoked), and therefore PRRTE needs to know and warn about shared filesystems.

**Comment by wenduwan** [comment]
@rhc54 So does this mean we need to change all 3 of ompi/prrte/pmix?

Also so far I'm taking it as "we should warn the user if TEMPDIR is on a shared filesystem", correct?

**Comment by rhc54** [comment]
We should definitely warn from PRRTE and OMPI - probably not PMIx. PRRTE should set an envar indicating that it has warned about this so that OMPI procs started by mpirun don't warn a second time - that could get annoying. I would leave the current OMPI warnings as they are (they come from the shmem component, I believe), just adding the "if this envar is present, then ignore it".

Make sense?

**Comment by jsquyres** [comment]
Aren't the shared memory files placed in the session directory, which will be in `$TMPDIR` (if `TMPDIR` is set)?

**Comment by jsquyres** [comment]
My prior comment wasn't clear at all, so I deleted it.

I agree with @rhc54 that we shouldn't double-warn (e.g., if PRTE warns about the session directory, OMPI doesn't need to warn again if we put shared memory files in the session directory, which PRTE already warned is on a network filesystem).  But shouldn't we see a warning from OMPI if it's placing shared memory files in the session directory (which is in a network filesystem)?  From the initial report, it sounds like that is not happening -- is that correct?

Do we know if the current network-filesystem-detecting code works properly in the user's environment who initially submitted the report?  It's pretty old code.

**Comment by rhc54** [comment]
I now have access to the user's machine and am investigating.

**Comment by rhc54** [comment]
I tried our current detection code and it didn't appear to work on their system. The shared filesystem is Lustre, so I'm a tad surprised by the result. I'm going to add some print statements and try to gather more info on why it didn't correctly identify it.

And FWIW: they were indeed trying to run Cray-MPICH, and not OMPI - so the OPAL detection code wasn't involved. It was doomed anyway as Cray-MPICH doesn't support PMIx.

**Comment by hppritcha** [comment]
Okay, if they are using cray-mpich why did they file an issue against PRRTE?  

File systems are a big issue in general on these SS11 systems (esp. when DVS is involved) and I'd suggest we stay out of it unless we determine that this is a more generic issue for systems where TMPDIR is pointing to a shared file system.

**Comment by bosilca** [comment]
1. they are doomed anyway if they expect any scalability with a TMPDIR mounted on a remote file system
2. I tried on our cluster to put OMPI files in a NFS mounted directory and it went OK (slow but not 1 minute to start two processes).
3. our detection mechanism is linear in the number of hierarchies in the $TMPDIR, and will execute an fstat on each one.  So if the TMPDIR is '/tmp/a/b/c/d' you have 5 stats per process, multiplied by the total number of process, so clearly not very scalable. Maybe you can try the following code instead:
```c
//#define MOUNT_FILE "/etc/mtab"
#define MOUNT_FILE "/proc/mounts"

int mountpoint(char *filename, char **fstype)
{
    struct stat s;
    struct mntent mnt;
    FILE *      fp;
    dev_t       dev;
    char buf[1024];

    if (stat(filename, &s) != 0) {
        return EINVAL;
    }

    dev = s.st_dev;

    if ((fp = setmntent(MOUNT_FILE, "r")) == NULL) {
	return EINVAL;
    }

    while (getmntent_r(fp, &mnt, buf, sizeof(buf))) {
        if (stat(mnt.mnt_dir, &s) != 0) {
            continue;
        }

        if (s.st_dev == dev) {
            endmntent(fp);
            *fstype = strdup(mnt.mnt_type);
            return 0;
	}
    }

    endmntent(fp);

    // Should never reach here.
    return EINVAL;
}
```

**Comment by rhc54** [comment]
> Okay, if they are using cray-mpich why did they file an issue against PRRTE?

Because the long start time was observed in PRRTE - when starting `prte` itself. Had nothing to do with what they were trying to run. I was only answering @jsquyres question about why we didn't see the OPAL warnings.

> Maybe you can try the following code instead

You make a good point - I'll give it a shot.

When launched by `mpirun` or `prun`, we can just check it once on each node and then tell the client procs to not perform the check. Would resolve the scaling question even more. If launched via `srun`, I guess there isn't much more we can do...

**Comment by rhc54** [comment]
Well, it turns out that PMIx/PRRTE are not checking TMPDIR for a shared file system - we just use it. We have a function for checking but it was never called. In the reported case, the problem was that we repeatedly call "stat" on the session directory tree and a few other locations, all of which were sitting on Lustre. Hence the long startup time.

I removed the unused function and am working to remove all those "stat" calls (pretty much done on PMIx, still have to do PRRTE itself). Partly done to alleviate this situation, mostly because the security scan being done on PMIx (so it can be used at privilege) is flagging the "stat" calls anyway.

I didn't get a chance to try the new code from @bosilca - probably will trip the security scan since it has that "stat" call in it. You folks might want to give it a try in OMPI, perhaps?

Closing this as PMIx/PRRTE isn't going to worry about this scenario. If people complain about slow start times, we will simply recommend they move to a non-shared TMPDIR - for a lot of reasons.

**Comment by bosilca** [comment]
I don't think this is a good design decision. You eliminate a simple detection for a known issue, a detection that could have pointed the sysadmin/users to the right [easy] fix and save them a lot of troubles. Instead, PMIX/PRRTE provides us with an `job_session_dir` that we now have to test at least once per process (because we are not using $TMPDIR, but instead stash everything in the `job_session_dir`). 

There is also a performance implication, because this detection done once per host in the daemon could have provided a leaner startup. 

I am also curious about the tool that is flagging stat as a security risk, especially with the usage we are doing.

**Comment by rhc54** [comment]
Let me be clear - I have no issue with doing the detection from PRRTE. However, it is my understanding that OMPI continues to do its own detection from the shared memory component - though I imagine we could modify that code to avoid duplication, as mentioned above.

What I'm concerned about is (a) ensuring we actually are accurately detecting shared file systems, since there were concerns raised here about the effectiveness of what we have done, (b) avoiding the security flags for use of "stat", and (c) doing it in a manner that doesn't get PRRTE blamed for slow startup. If we can come up with something that meets those criteria, then I'm happy to adopt it.

It seems we would at least need people to test your proposed code on a variety of file systems. I don't have access to such a range, so perhaps you folks could do that over on the OMPI side?

There are multiple security scanners flagging "stat" (including Coverity) due to the time-of-check vs time-of-use issue, which is considered a security risk. Your code could easily skip that problem by simply removing the initial "stat" - this is in keeping with what the security scanners are recommending - i.e., just operate on the file and deal with the returned errors instead of doing a "stat" since the latter leaves open the possibility of the file changing between the "stat" and the next operation.

**Comment by rhc54** [comment]
I have created a slightly revised version of the above code (so it passes the security scanners) and tested it on a couple of places that I can access. It seems to correctly identify "lustre" and "gpfs" (which I believe we consider equivalent to "nfs", yes?) file systems. Also found lots of other file system types that are not ones of interest (e.g., "cgroup").

Which means we have to create a list of file system type names that we decide merit a warning. We have something in the old code that we could use, assuming we believe those values are correct. Need to review to see if we consider that complete as well.

I committed this test code to PRRTE as `test/chkfs.c`. Note that it cannot build/run on the Mac as the `setmntent` and `getmntent` functions do not exist there. Here is the code:
```c
#define _GNU_SOURCE
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
#include <mntent.h>
#include <string.h>
 #include <fcntl.h>

//#define MOUNT_FILE "/etc/mtab"
#define MOUNT_FILE "/proc/mounts"

static int mountpoint(char *filename, char **fstype)
{
    struct stat s;
    struct mntent mnt;
    FILE *fp;
    dev_t dev;
    char buf[1024];
    int fd;

    fd = open(filename, O_RDONLY);
    if (0 > fd) {
        fprintf(stderr, "CANNOT OPEN %s\n", filename);
        return EINVAL;
    }
    if (fstat(fd, &s) != 0) {
        return EINVAL;
    }
    close(fd);

    dev = s.st_dev;

    if ((fp = setmntent(MOUNT_FILE, "r")) == NULL) {
        return EINVAL;
    }

    while (getmntent_r(fp, &mnt, buf, sizeof(buf))) {
        fd = open(mnt.mnt_dir, O_RDONLY);
        if (0 > fd) {
            // probably lack permissions
            continue;
        }
        if (fstat(fd, &s) != 0) {
            close(fd);
            continue;
        }

        if (s.st_dev == dev) {
            *fstype = strdup(mnt.mnt_type);
            close(fd);
            return 0;
        }
        close(fd);
    }

    endmntent(fp);

    // Should never reach here.
    return EINVAL;
}

int main(int argc, char **argv)
{
    int n, rc;
    char *fstype;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s file1 file2 ...\n", argv[0]);
        return 1;
    }

    for (n=1; NULL != argv[n]; n++) {
        rc = mountpoint(argv[n], &fstype);
        if (0 == rc) {
            fprintf(stdout, "Return: %d File: %s FStype: %s\n", rc, argv[n], fstype);
            free(fstype);
        } else {
            fprintf(stdout, "File: %s Unknown type\n", argv[n]);
        }
    }

    return 0;
}
```
