### ISSUE TITLE
mpirun --report-bindings segfault

### ISSUE THREAD

**Issue by wenduwan** [openpmix/prrte#1874]
### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)

066b56055c4f9017a581dc472864c9e2d8c189cc

##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)

9095457b2c5b2370178a9a0ffaff7a6918af632e

### Please describe the system on which you are running

* Operating system/version: Amazon Linux 2
* Computer hardware: EC2
* Network type: EFA

-----------------------------

## Details of the problem

`mpirun --report-bindings ...` segfaults

Related to https://github.com/open-mpi/ompi/issues/12143

**Comment by wenduwan** [comment]
I was able to narrow it down to this commit:
https://github.com/openpmix/prrte/commit/0bae0b4ea30508a50151ad3cf43951d5a389b8a7

**Comment by rhc54** [comment]
FWIW: I don't see this problem on either PRRTE master or head of PRRTE v3.0 branch:
```shell
$ prterun --personality ompi --report-bindings -n 1 hostname
Ralphs-iMac-2.local
$
```
same output for both cases.

**Comment by wenduwan** [comment]
@rhc54 Thank you for the quick fix. I can confirmed that the segfault is gone!
