### ISSUE TITLE
Enabling debugging options for prrte

### ISSUE THREAD

**Issue by darbyShaw** [openpmix/prrte#1916]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)
v4.0.0

##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)
v5.0.0

-----------------------------

## Details of the problem
Hello,
I am a bit confused about enabling debugging options for the implementations of the host server functions by prrte.
For example, if I want to enable the following output:
pmix_output_verbose(2, prte_pmix_server_globals.output, "%s connect called with %d procs",
                        PRTE_NAME_PRINT(PRTE_PROC_MY_NAME), (int) nprocs);

What should I pass as an mca parameter? For eg., I tried to use -prtemca prte_pmix_server_verbose 10 with prte, but the above output is not enabled.
Is there any documentation about the different debugging mca parameters that can be used?
Thank you!

```shell
shell$ prte --hostfile ${pmix_hosts}                                   \
     --report-pid ${pidfile}                                    \
     --mca gds hash                                             \
     --debug-daemons                                            \
     --prtemca plm_base_verbose 20                              \
     --prtemca prte_allowed_exit_without_sync 1                 \
     --prtemca prte_pmix_server_verbose 10 \
     -x PATH=/scratch/bin \
     --prtemca plm slurm                                        \
     > server_${SLURM_JOB_ID}.log 2>&1 &
```

**Comment by rhc54** [comment]
The correct option is `--prtemca pmix_server_verbose 10`. You can get the params using `prte_info`. Unfortunately, I'm between machines and cannot generate the output for you, but use `prte_info --help` to see how to get the params of interest.

**Comment by rhc54** [comment]
Please reopen if you have further questions.
