### ISSUE TITLE
Building for Fault Tolerance

### ISSUE THREAD

**Issue by efweber999** [openpmix/prrte#1969]
prte (PRRTE) 3.0.5
pmix_info (PMIx) 5.0.2

OS: Ubuntu 22.04.1
Hardware: AWS EC2 instances. Just 2 instances for initial testing.
Network: UCX (only TCP is available for these instances. Will eventually move to an HPC cluster with IB)

-----------------------------

I want to try utilizing fault tolerance as discussed in [chapter 12 "Resilience" in the latest documentation](https://docs.prrte.org/en/latest/resilience.html). The document says I need to build using configuration option "--enable-prte-ft". However configure reports that as an unrecognized option. Thanks.

**Comment by rhc54** [comment]
Hmmm...that document is unfortunately very out of date. There are no relevant configure or runtime options for PRRTE that relate to fault tolerance. You need to configure OMPI for it, and there is an mpirun cmd line option you need to provide - but neither of those have any impact on PRRTE.

You should look [here](https://docs.open-mpi.org/en/v5.0.x/features/ulfm.html) for required directions. Meantime, I'll remove that document from PRRTE to avoid future confusion. Thanks for pointing it out!

**Comment by efweber999** [comment]
Thanks. Allow me to explain what I'm trying to accomplish as I'm sure you can provide insight and save me from going down dead end paths. The application I'm working could potentially run for an extended period of time. Ideally if a node is lost during processing the application should handle this gracefully. For example give the user the option to read a check-pointed copy of the data that was on the failed node into the remaining nodes, and continue, or accept the data loss and continue.

In a trivial test case to see how a barrier reacted to the loss of a node the code simply had rank 0 sleep for five seconds prior to a barrier, and I rebooted rank 1. You obviously know what happens. PRRTE says: "PRTE has lost communication with a remote daemon. ..... "We cannot recover from this failure, and therefore will terminate the job."

I'm hoping I can intercept this error and handle it rather than allowing it to be fatal.
Thanks.

**Comment by rhc54** [comment]
No, we don't really support that at this time. If a daemon terminates, then the DVM will follow as we don't have a guaranteed communication path (e.g., to daemons sitting beyond the one that failed). We used to, and maybe we will again someday - but not at the moment.

OMPI will handle the case of a proc failing on a node, or even all the procs failing on a node - but not the loss of the daemon on that node. Best you could do is to checkpoint your data, and then execute a restart if mpirun reports a "daemon failed" error. Not much different than what you proposed - restarting the DVM is quick. You'd need something to edit the allocation so we don't attempt to start a daemon on it, but that shouldn't be too hard of a script to write.

**Comment by efweber999** [comment]
Glad I asked. That's too bad. While restarting DVM may be quick, reloading all data onto all nodes will not be. This is also a situation where the user may prefer not to checkpoint in order to gain runtime performance knowing they may lose a node or two of information. But that's not an option if loss of a node is fatal.

**Comment by rhc54** [comment]
Afraid I don't really see it that way. If you are using checkpointing, then you have to reload data on the nodes anyway. You generally don't want to keep the checkpoint on the node as it consumes so much space. This is pretty much considered a worse-case scenario nowadays as binary checkpoints are generally frowned upon - eat up a lot of space and very inefficient.

It is generally considered better practice to just maintain state info on the in-memory file system on each node.  Nobody is going to reset the node, so data will be persistent by default so long as you store it there. You then either direct the restart to ensure the same ranks are on those nodes, or have the restarted procs look at their location and take on the correct rank (which is probably easier). They then just read the local state info and go on their way. Again, that is fairly quick - been doing that for quite some time, and it works well.

Either way, failure recovery is never going to be fast or performant. On the other hand, faults should be relatively rare - or else you're better off spending the time fixing the problem 😄 Relying on a "failure-proof" DVM is a recipe for disappointment as there is no such thing, even with the best of effort 🤷‍♂️ You always need to be prepared to recover your app on a restored DVM.

Still, if someone wants to provide a patch to try and keep the DVM running, we'd certainly consider it. The main problem is ensuring the DVM properly shuts down when we want it to, without getting stuck in an endless recovery loop. Much harder than it sounds.

**Comment by efweber999** [comment]
Always trade-offs. Never just unicorns and rainbows. LOL. Your response was insightful and helpful. Thanks.
