### ISSUE TITLE
Restore code to ignore NUMA nodes with overlapping cpusets if heterogeneous memory

### ISSUE THREAD

**Issue by bgoglin** [openpmix/prrte#2025]
Putting back all the details here so that they don't get lost.

Commit d23ac62339ab2435c30ac8c83c33ce4bcdfb73c8 added the ability to handle heterogeneous memory by looking at which NUMA nodes have same or overlapping cpusets. We don't want to place one process per NUMA node if two nodes have a same CPUs. This was mostly done for POWER platforms with NVIDIA GPU memory exposed as NUMA nodes, but the code actually worked for all known heterogeneous memory platforms so far (KNL, Xeon Max, GraceHopper, DDR+NVM, DDR+CXL).
That code was removed in 4b41c8e0a30befd21298b93c1aa12fcd6ac69b30

In the first case, NVIDIA GPU nodes on Power are hardwired at NUMA os_index starting from 255 and going down. Hence we may cutoff at 150  at only look at nodes before that. Earlier versions (2.0.1 for instance) did this (commits 5bc6079f6127e6bed6378acb22f9558ba198e9a6 and c414df039efd950b776e5aead5bf81602b6dc866) changed the cutoff os_index from 200 to 150 for instance).

In the second case, "default" memory nodes (e.g. DRAM in the vast majority of cases, HBM is there's no DRAM, etc) are listed first in ACPI tables and thus first by os_index too. Those first default nodes cannot have intersecting cpusets either (in ACPI and Linux kernel). So the idea of d23ac62339ab2435c30ac8c83c33ce4bcdfb73c8 was to iterate over NUMA nodes starting from os_index 0 until we find an intersecting cpuset ones, and stooping before it.

Recent hwloc versions may also help since they are able to detect the kind of NUMA nodes. Starting with 2.8, they may have a "DRAM" subtype (or "HBM", etc). The detection was improved in 2.10 which also provides a "MemoryTier" info attribute to identify similar nodes. Tiers are sorted by performance, so you would get HBM first, DRAM then, GPU then, ... Taking the first tier should be fine since it's unlikely we'll get a machine with HBM only near a subpart of the CPUs.

**Comment by rhc54** [comment]
Like I said, all getting very complicated - may be beyond the time I have left. Perhaps beyond what we can reasonably expect an RTE to do. Could be we are getting to the point where automatic placement algorithms are reaching their limit and users are going to just have to start manually placing things...sigh.

**Comment by rhc54** [comment]
@bgoglin Can you provide a topo file with an example I can use for testing?

**Comment by bgoglin** [comment]
Here are the 3 most common cases:
- DDR+HBM (Intel Xeon Max in Flat mode, similar to KNL) where nodes 0-7 are DDR and nodes 8-16 are HBM (one of each for SubNUMA cluster) [ddr+hbm.xml.gz](https://github.com/user-attachments/files/17395338/ddr%2Bhbm.xml.gz)
- DDR+NVM (Intel Xeon with NVDIMM in Flat mode too) where nodes 0-3 are DDR (one per SNC) and nodes 4-5 are NVDIMM (one per package) [ddr+nvm.xml.gz](https://github.com/user-attachments/files/17395339/ddr%2Bnvm.xml.gz)
- POWER9+6 NVIDIA GPUs over NVLink where nodes 0-1 are DDR (one per package) and 250-255 are GPU memory (3 per package) [power9+nvidiagpus.xml.gz](https://github.com/user-attachments/files/17395340/power9%2Bnvidiagpus.xml.gz)

**Comment by rhc54** [comment]
Hmmm...well, I think I've got the first two cases correct, but I'm not sure about the third. Here's what I'm getting when I map one proc/NUMA:

For DDR+HBM (found 8 non-overlapping NUMA):
```shell
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 0 Bound: package[0][core:0-9]
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 1 Bound: package[0][core:10-19]
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 2 Bound: package[0][core:20-29]
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 3 Bound: package[0][core:30-39]
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 4 Bound: package[1][core:40-49]
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 5 Bound: package[1][core:50-59]
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 6 Bound: package[1][core:60-69]
        Process jobid: prterun-Ralphs-iMac-24811@1 App: 0 Process rank: 7 Bound: package[1][core:70-79]
```

For DDR+NVM (found 4 non-overlapping NUMA):
```shell
        Process jobid: prterun-Ralphs-iMac-24834@1 App: 0 Process rank: 0 Bound: package[0][core:0-9]
        Process jobid: prterun-Ralphs-iMac-24834@1 App: 0 Process rank: 1 Bound: package[1][core:20-29]
        Process jobid: prterun-Ralphs-iMac-24834@1 App: 0 Process rank: 2 Bound: package[0][core:10-19]
        Process jobid: prterun-Ralphs-iMac-24834@1 App: 0 Process rank: 3 Bound: package[1][core:30-39]
```

For Power9 (found 9 non-overlapping NUMA):
```shell
        Process jobid: prterun-Ralphs-iMac-24845@1 App: 0 Process rank: 0 Bound: package[0][core:0-21]
        Process jobid: prterun-Ralphs-iMac-24845@1 App: 0 Process rank: 1 Bound: package[1][core:22-43]
```

I'm not sure why I only got two procs for the last case. Any thoughts on these results?

**Comment by rhc54** [comment]
For the Power9 case, I'm computing a NUMA cutoff of 9 - that's where the overlap starts. When I then loop across `hwloc_get_numanode_obj_by_os_index`, I only count two non-NULL returned objects before hitting that cutoff. Hence mapping only two procs.

Does that sound right?
