### ISSUE TITLE
Bad source tarball for release 3.0.7

### ISSUE THREAD

**Issue by lahwaacz** [openpmix/prrte#2072]
There are two source archives for the [prrte 3.0.7 release](https://github.com/openpmix/prrte/releases/tag/v3.0.7):

- [prrte-3.0.7.zip](https://github.com/openpmix/prrte/archive/refs/tags/v3.0.7.zip)
- [prrte-3.0.7.tar.gz](https://github.com/openpmix/prrte/archive/refs/tags/v3.0.7.tar.gz)

The problem is that these archives are very different: the former contains the `prrte-3.0.7` directory, but the latter contains `prrte-gitclone`. There are also major differences between the contents of files in these directories, as can be seen here (generated with diffoscope after extracting both archives):

[prrte-3.0.7-release-diff.txt](https://github.com/user-attachments/files/17778473/prrte-3.0.7-release-diff.txt)

I hope this was just a mistake during the release process and not intentional discrepancy. In any case, please make a new release with proper source archives.

**Comment by rhc54** [comment]
We know the zipfile is "bad" because it is generated by GitHub, as we have documented multiple times. I'll take a look at the other as it is probably some trivial thing.

**Comment by rhc54** [comment]
Tarballs have been updated - thx!
