### ISSUE TITLE
getenv() now always returns NULL in client code

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/prrte#304]
Thank you for taking the time to submit an issue!

## Background information

I use getenv() in my OpenSHMEM library which launches through PMIx.  now with PRRTE as launcher getenv() always returns NULL despite environment variables being set.

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ 164ab7fdc1dc36f94372ed24b47ec4b7cf612b32

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

git master @ aa6fb1e3b2b5a340c427960b02d06c6ffa01bdc4

### Please describe the system on which you are running

* Operating system/version: CentOS 7.5
* Computer hardware: x86_64
* Network type: Ib

-----------------------------

## Details of the problem

MWE below.  When called through prte/prun, getenv() returns NULL despite VERBOSITY=1 in environment.  Open-MPI as launcher picks up a string for "VERBOSITY".

```C
#include <stdio.h>
#include <stdlib.h>

#include <pmix.h>

int
main()
{
    pmix_proc_t p;

    PMIx_Init(&p, NULL, 0);

    char *v = getenv("VERBOSITY");

    printf("%d: v = %p\n", p.rank, v);

    PMIx_Finalize(NULL, 0);

    return 0;
}
```

**Comment by rhc54** [comment]
OMPI forwards a plain "VERBOSITY" envar??? Wow - it didn't used to do that and definitely shouldn't without specifically being told to do so. We never forward your environment except for envars prefixed with "PRRTE_" or "PMIX_" - or if you set the "prun" personality to include "ompi", then we also pickup "OMPI_". Anything else has to be directed to be forwarded using the "-x" cmd line option - e.g., ```-x VERBOSITY``` or ```-x VERBOSITY=3```.

I have been revamping the PRRTE cmd line to meet OMPI's requirements as we are merging our efforts - i.e., OMPI is going to replace ORTE with PRRTE and the two communities will jointly support PRRTE going forward. So there will be some instability over the next few weeks, particularly in the cmd line parsing. I'm running some tests on it now to see where we stand, but I believe it follows the behavior described above.

**Comment by tonycurtis** [comment]
> On Jan 21, 2020, at 5:00 PM, Ralph Castain <notifications@github.com> wrote:
> 
> OMPI forwards a plain "VERBOSITY" envar??? Wow - it didn't used to do that and definitely shouldn't without specifically being told to do so. We never forward your environment except for envars prefixed with "PRRTE_" or "PMIX_" - or if you set the "prun" personality to include "ompi", then we also pickup "OMPI_". Anything else has to be directed to be forwarded using the "-x" cmd line option - e.g., -x VERBOSITY or -x VERBOSITY=3.
> 

This has been working fine for me for ages (years I suspect) with OMPI and since I started using PRRTE.  I just set any SHMEM_/SMA_ envvars for my OpenSHMEM and (possibly indirectly) mpirun or launch a prte/prun pair.  OMPI = 4.0.2 in this instance.
> I have been revamping the PRRTE cmd line to meet OMPI's requirements as we are merging our efforts - i.e., OMPI is going to replace ORTE with PRRTE and the two communities will jointly support PRRTE going forward. So there will be some instability over the next few weeks, particularly in the cmd line parsing. I'm running some tests on it now to see where we stand, but I believe it follows the behavior described above.
> 
> 

OK.  I might stick with OMPI for a while to see how things shake out.  If I have to e(x)plicitly forward I guess I can do that.

Did a quick test:

Start prte

Then prun -x VERBOSITY -n 1 prog gives

[login2:27751] PRRTE ERROR:  in file ../../../../prrte-git/src/tools/prun/prun.c at line 698

**Comment by rhc54** [comment]
I'll check OMPI - we never forward arbitrary envars as it is too easy to break the backend (e.g., forward DISPLAY). I can't believe we actually are doing that, but could be a bug crept into the system and needs to be squashed.

**Comment by rhc54** [comment]
Oh, I bet I know what might be fooling you. If you are running on a single node (where VERBOSITY has been defined in the environment), then yes - that envar will be present for any procs we start on that node. However, I'm certain that we don't _forward_ that envar to a remote node for procs started there.

Are your tests running on a single node? If so, I can check that prun/prrte aren't somehow failing to pickup the local environment. They won't forward it to another node, but they should reflect it in their locally started children.

**Comment by tonycurtis** [comment]
> On Jan 21, 2020, at 5:44 PM, Ralph Castain <notifications@github.com> wrote:
> 
> Oh, I bet I know what might be fooling you. If you are running on a single node (where VERBOSITY has been defined in the environment), then yes - that envar will be present for any procs we start on that node. However, I'm certain that we don't forward that envar to a remote node for procs started there.
> 
> Are your tests running on a single node? If so, I can check that prun/prrte aren't somehow failing to pickup the local environment. They won't forward it to another node, but they should reflect it in their locally started children.
> 

Ah, that could be it with PRRTE (simple test, thought it didn’t warrant a SLURM job).  Looks like misc envvars do make it to other nodes with OMPI from a quick test.

Will look at again in the morning.

Tony

**Comment by tonycurtis** [comment]
> On Jan 21, 2020, at 5:58 PM, Tony Curtis <anthony.curtis@stonybrook.edu> wrote:
> 
> 
> 
>> On Jan 21, 2020, at 5:44 PM, Ralph Castain <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> Oh, I bet I know what might be fooling you. If you are running on a single node (where VERBOSITY has been defined in the environment), then yes - that envar will be present for any procs we start on that node. However, I'm certain that we don't forward that envar to a remote node for procs started there.
>> 
>> Are your tests running on a single node? If so, I can check that prun/prrte aren't somehow failing to pickup the local environment. They won't forward it to another node, but they should reflect it in their locally started children.
>> 
> 
> Ah, that could be it with PRRTE (simple test, thought it didn’t warrant a SLURM job).  Looks like misc envvars do make it to other nodes with OMPI from a quick test.
> 

Verified on another cluster with OMPI 3.1.3.  Picking up arbitrary envvars on compute nodes.

So how could I tell prun to also forward e.g. all SHMEM_ envvars?  Anything to do with —personality?

Tony

**Comment by rhc54** [comment]
Okay, here is what I think is going on. When our daemons (including mpirun) start up, they take a snapshot of their local environ. They pass this to each local app proc when it is spawned, along with other variables the daemons define themselves.

We never have mpirun pickup its local environ and forward that to its daemons for delivery to their procs. However, Slurm does do this - so when mpirun/PRRTE use Slurm to start the daemons, the local environ will show up on the node prior to our daemon being started. Thus, the daemons "see" the same local environ that is present at mpirun.

This isn't the case when ssh is used to launch the daemons as ssh doesn't transfer the local environment (at least, not by default). So if you launch via ssh, you won't see the local environ being forwarded. This is my test environment, so I don't see it myself. However, you are using Slurm, and so you do.

I checked and verified this with OMPI master. It is possible that PRRTE's daemons aren't picking up their local environ correctly (given all the recent changes). I'll take a look at that soon.

**Comment by rhc54** [comment]
> So how could I tell prun to also forward e.g. all SHMEM_ envvars?  Anything to do with —personality?

We could create a "shmem" personality, if you like. Or (once it is working properly) you could forward all ```SHMEM_*``` variables by using ```-x SHMEM_*```, though you might have to quote that asterisk on the cmd line. I'll try to look and see if/how that works.

**Comment by tonycurtis** [comment]
> On Jan 23, 2020, at 9:24 AM, Ralph Castain <notifications@github.com> wrote:
> 
> So how could I tell prun to also forward e.g. all SHMEM_ envvars? Anything to do with —personality?
> 
> We could create a "shmem" personality, if you like. Or (once it is working properly) you could forward all SHMEM_* variables by using -x SHMEM_*, though you might have to quote that asterisk on the cmd line. I'll try to look and see if/how that works.
> 

That -x wildcard solution could be handy.
Tony
