### ISSUE TITLE
Read failure message on job termination

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#345]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

PRRTE master at https://github.com/openpmix/prrte/commit/a9ef1f5e6164976f607445f388dcad07e23f405f

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

PMIx master at https://github.com/openpmix/openpmix/commit/a3cfa97da6983a33411e367f6a250964cff1dc55

### Please describe the system on which you are running

* Operating system/version: RHEL 7.6
* Computer hardware: Power8
* Network type: TCP

-----------------------------

## Details of the problem

On job completion sometimes I see a message like the below repeated over and over again until the job is killed:
```
[node01:33166] Read -1, expected 1048576, errno = 14
[node01:33166] Read -1, expected 1048576, errno = 14
[node01:33166] Read -1, expected 1048576, errno = 14
```

I suspect that this is a race between the `prte` daemon closing the channel to the `prun` process and the `prun` process deregistering it from libevent.

It is a difficult timing window to hit in the wild, but regressing testing in Open MPI via MTT hits this nightly due to the large volume of tests being run.

**Comment by jjhursey** [comment]
I've had trouble re-creating the `Read -1` failure outside of the MTT harness. However, I have been able to encounter the following which should be a similar problem:
```
[warn] Epoll MOD(1) on fd 15 failed. Old events were 6; read change was 0 (none); write change was 2 (del); close change was 0 (none): Bad file descriptor
```

**Comment by rhc54** [comment]
I believe this has been fixed

**Comment by rhc54** [comment]
Not seeing this even on MTT any more, so closing for now - please reopen if you see it again.
