### ISSUE TITLE
prte: prefix environment not propogated properly

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#371]
### What version of the PMIx Reference Server are you using? 

git prrte fc30acb (via latest  master of open-mpi/ompi@960c5f7)

##### What version of PMIx are you using? 

pmix4x (via latest ompi master)

### Please describe the system on which you are running

* Operating system/version: Linux
* Computer hardware: x86_64
* Network type: TCP

-----------------------------

## Details of the problem

Environment is not propagated to remote hosts during the SSH launch.  This appears to be an issue with the `--enable-orterun-prefix-by-default` at compile time or when using `--prefix` at runtime.

Configured with VPATH (via ompi build)

```shell
./autogen.pl
cd BUILD-master/
../configure \
    --enable-orterun-prefix-by-default \
    --prefix=${OMPI_INSTALL_DIR} \
    --enable-debug \
&& make -j 4 \
&& make install
```

Example to reproduce problem

```shell
[3t4@node0 BUILD-master]$ hostname
node0
[3t4@node0 BUILD-master]$ more hosts 
node1
node2
[3t4@node0 BUILD-master]$ prte --hostfile hosts &
[1] 9107
[3t4@node0 BUILD-master]$ bash: prted: command not found
bash: prted: command not found
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/rml/oob/rml_oob_send.c at line 202
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../prrte/src/mca/plm/base/plm_base_launch_support.c at line 632
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/errmgr/dvm/errmgr_dvm.c at line 418
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/rml/oob/rml_oob_send.c at line 202
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/errmgr/dvm/errmgr_dvm.c at line 563
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/rml/oob/rml_oob_send.c at line 202
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../prrte/src/mca/plm/base/plm_base_launch_support.c at line 632
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/errmgr/dvm/errmgr_dvm.c at line 418
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/rml/oob/rml_oob_send.c at line 202
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../prrte/src/mca/plm/base/plm_base_launch_support.c at line 632
[node0:09107] PRRTE ERROR: Bad parameter in file ../../../../../../prrte/src/mca/errmgr/dvm/errmgr_dvm.c at line 418

[1]+  Exit 127                prte --hostfile hosts
[3t4@node0 BUILD-master]$
```

**Comment by naughtont3** [comment]
I'm tracking this now.  I can not assign issue to myself.

**Comment by naughtont3** [comment]
Doh!  Should be `--enable-prte-prefix-by-default` now.

**Comment by naughtont3** [comment]
The following works fine `prte --prefix $OMPI_INSTALL_DIR`.  But this does not make it down when started via `mpirun --prefix $OMPI_INSTALL_DIR`.

**Comment by naughtont3** [comment]
So looks like this is not a PRRTE issue at all. :-)

**Comment by naughtont3** [comment]
Reopen as the issue relates to running `prun` and `mpirun`.

**Comment by naughtont3** [comment]
OK, found it.  Need to propagate `--prefix` down from `prun` (`mpirun`) to the argv we create for `prte`.  I'll file PR in a bit.

**Comment by naughtont3** [comment]
works for me now.

**Comment by roblatham00** [comment]
Are you sure this is fixed?  Sure seems a lot like the problem I'm seeing.
- I'm using pmix@master and prrte@master, both built from spack
- I start up the prrte daemons like this:
```shell
jsrun -r 1 hostname > hostfile
prte --pmixmca pmix_client_get_verbose 50 -x LD_LIBRARY_PATH --prefix $(spack location -i prrte) --hostfile hostfile -n 4  &
```
Then I run a little shell script that tells me the value of LD_LIBRARY_PATH.   I won't paste it here but trust me it's long:  
```shell
$ echo $LD_LIBRARY_PATH | wc -c
3660
```

despite 25 years working in shell scripts I still get tripped up by escape rules so I just wrote a shell script that reports LD_LIBRARY_PATH to me:

```shell
$ cat libs.sh
#!/bin/sh
echo $LD_LIBRARY_PATH
```
The only member of LD_LIBRARY_PATH is the prefix:
```shell
$ prun -np 1 -x LD_LIBRARY_PATH ./libs.sh
/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel7-power9le/gcc-9.1.0/prrte-develop-bolcnur2trdqfs4hvdsjzrn6yd5it6uc/lib:
```

**Comment by naughtont3** [comment]
@roblatham00 Yep would certainly look like it.  I'll take a look again and check things.
