### ISSUE TITLE
few option for prun missing/not working

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#388]
### Background information

A few CLI options are either entirely gone or not working with `prun`.

### What version of the PMIx Reference Server are you using? 

- prrte master at 8bc2749

##### What version of PMIx are you using? 

 - openpmix master at 01f31d7

 -  hwloc-2.0.3  
 - libevent-2.1.8-stable

### Please describe the system on which you are running

* Operating system/version: Linux
* Computer hardware: x86_64
* Network type: TCP

-----------------------------

## Details of the problem

The following options are reported but not functional in current master of prrte.
  - [x] `prun --report-bindings ...`
  - [x] `prun --display-map ...`
  - [x] `prun --map-by ppr:X:node:NOLOCAL ...` (think this is correct syntax for `:NOLOCAL` attribute)
 - [x] `--nolocal` option removed (see above for `:NOLOCAL` attribute too)

**Comment by naughtont3** [comment]
we also need to update prun.1 manpage with CLI changes (may want to create a new ticket for this point)

**Comment by rhc54** [comment]
All completed except for manpage update - moved that to its own issue
