### ISSUE TITLE
Map-by ppr:*:node with daemon co-launch on HNP

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#390]
Whenever I try to use --map-by ppr:*:node with --mca ras_base_launch_orted_on_hn true, I get the following error:

$> mpirun --map-by ppr:1:node --mca ras_base_launch_orted_on_hn true hostname 
--------------------------------------------------------------------------
Your job has requested more processes than the ppr for
this topology can support:

  App: hostname
  Number of procs:  3
  PPR: 1:node

Please revise the conflict and try again.
--------------------------------------------------------------------------
If I set ras_base_launch_orted_on_hn to false, mpirun works fine. I am using ras_base_launch_orted_on_hn so that signals from slurm are properly caught by the application, so I would really like to be able to keep it. Is there something else that needs to be done to get --map-by ppr:*:node working?

For reference, this works in 3.1.4.

Cross-reference: https://github.com/open-mpi/ompi/issues/7199

**Comment by rhc54** [comment]
Note: may not be true under PRRTE, but should be checked and fixed if found

**Comment by hppritcha** [comment]
this is now working for me at prrte sha 284d15d7
