### ISSUE TITLE
Output to stderr/out broken for daemon co-launch on HNP

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#392]
By default, the mpirun now in master following the orted removal no longer forwards stdout/stderr from MPI processes in a job if the PRRTE launch_orted_on_hn mca parameter is set to true.

Cross-reference: https://github.com/open-mpi/ompi/issues/7399

**Comment by hppritcha** [comment]
I tested with head of Open MPI master on the cori system and now I get stdout/stderr.  Not sure when this got fixed.  Closing this issue.
