### ISSUE TITLE
PRRTE SIGHUP

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#404]
When the process/tool that spawned a job goes away, PRRTE needs to terminate the job it spawned along with any descendants of that job. However, there are two conditions under which that should not be true:

1. the `PMIX_NOHUP` attribute is included in the job-level directives provided in the call to `PMIx_Spawn`

1. a call to `PMIx_Job_control` has been made by the tool that included the `PMIX_NOHUP` attribute prior to the tool going away. If the list of attributes does not specify the job that is to continue after disconnect, then all descendants of the caller are to continue. Otherwise, only the specified jobs and any descendants of those jobs should continue.

**Comment by jjhursey** [comment]
Any update on this issue? or is it up for grabs?

**Comment by rhc54** [comment]
anyone is welcome to grab it - not sure why I self-assigned it. probably just reflex
