### ISSUE TITLE
Persistent DVM mixup

### ISSUE THREAD

**Issue by jsquyres** [openpmix/prrte#406]
If I run 2 `salloc` jobs on my SLURM cluster simultaneously:

## Job 1:

```sh
$ salloc -N 2 -p jenkins
salloc: Granted job allocation 3116845

# Let's find out what nodes SLURM gave me
$ srun hostname
mpi002
mpi008

# Setup a persistent DVM and verify that we got the same nodes
$ prte --daemonize
$ prun hostname | sort | uniq
mpi002
mpi008
```

## Job 2

(the `salloc` allocations are simultaneous)

```sh
$ salloc -N 2 -p jenkins
salloc: Granted job allocation 3116846

# Let's find out what nodes SLURM gave me
$ srun hostname
mpi024
mpi025

# Don't run a new pdvm
$ prun hostname | sort | uniq
mpi002
mpi008
```

Notice that I get the same DVM as is in the other SLURM job.

I.e., this `prun` in one SLURM job is not "preferring" its own SLURM job -- it's just seeing a pdvm and using it.

## Still in job 2

Alternatively, if I *do* fire up a pvdm in job 2, things work as expected for job 2 -- i.e., I get the nodes that SLURM allocated to job 2:

```sh
# Still in job 2
$ prte --daemonize
$ prun hostname | sort | uniq
mpi024
mpi025
```

## Back in job 1

But now if I switch back to job 1, it can't seem to find its own pdvm any more:

```sh
# Back in job 1
$ prun hostname | sort | uniq
mpi024
mpi025
```

**Comment by rhc54** [comment]
Yeah, this is an issue with `prte` automatically taking the "system daemon" role and `prun` defaulting to looking for that daemon. I'll fix this. Also need to ensure that `prun` picks the `prte` it started when run as `mpirun` - the tools folks have raised that one with me.

**Comment by jsquyres** [comment]
Looks like there have been some updates, but I'm still getting mixups.

```sh
# SLURM head node, not in a salloc job
$ prun hostname | sort | uniq
prun failed to initialize, likely due to no DVM being available
# ^^ Huh.  Not sure why that's happening.

# SLURM salloc job 1, before prte --daemonize
$ srun hostname
mpi029
mpi030
$ prun hostname | sort | uniq
mpi029
mpi030

# SLURM salloc job 2, before prte --daemonize
$ srun hostname
mpi018
mpi019
$ prun hostname | sort | uniq
mpi018
mpi019

# SLURM job 1
$ prte --daemonize
$ prun hostname | sort | uniq
mpi029
mpi030

# SLURM job 2 (after daemonizing in job 1)
$ prun hostname | sort | uniq
mpi018
mpi019
$ prte --daemonize
$ prun hostname | sort | uniq
mpi018
mpi019

# Back in SLURM job 1, just to make sure it's still ok
$ prun hostname | sort | uniq
mpi029
mpi030

# All good so far.

# Now let's check the head node -- outside of SLURM jobs
$ prun hostname | sort | uniq
mpi029
mpi030
# ^^ That's the nodes from SLURM job 1
```

Meaning:

1. It looks like prun pdvdm's inside SLURM jobs are ok
2. The prun behavior outside of SLURM jobs has gotten wonky

I also note that `prun --terminate` has gotten wonky in some situations.

```
# In SLURM job 1
$ prun --terminate
--------------------------------------------------------------------------
No executable was specified on the prun command line.

Aborting.
--------------------------------------------------------------------------

# In SLURM job 2
$ prun --terminate
--------------------------------------------------------------------------
No executable was specified on the prun command line.

Aborting.
--------------------------------------------------------------------------

# On head node (outside of SLURM jobs)
$ prun --terminate
TERMINATING DVM...DONE
$ prun --terminate
TERMINATING DVM...DONE
$ prun --terminate
TERMINATING DVM...DONE
$ prun --terminate
TERMINATING DVM...DONE
$ prun --terminate
prun failed to initialize, likely due to no DVM being available
# ^^ Not sure why it let me terminate 4 times before failing...?
```

**Comment by jsquyres** [comment]
I also note that somewhere along the way, prun started opening directories under my CWD (i.e., not in TMPDIR, etc.).  For example:

```
$ pwd
/home/jsquyres/git/ompi
$ ls -ld prun*
drwxr-xr-x 2 jsquyres named 4096 Feb 29 04:29 prun.session.3127405/
drwxr-xr-x 2 jsquyres named 4096 Feb 29 04:47 prun.session.3127409/
drwxr-xr-x 2 jsquyres named 4096 Feb 29 04:47 prun.session.3127410/

**Comment by rhc54** [comment]
> I also note that prun --terminate has gotten wonky in some situations.

Try using `pterm` instead - it should be a little more reliable

> # ^^ Not sure why it let me terminate 4 times before failing...?

Since `prun --terminate` failed several times, you had leftover `prte` executions still running - it found them and cleaned them up one at a time.

**Comment by rhc54** [comment]
> I also note that somewhere along the way, prun started opening directories under my CWD (i.e., not in TMPDIR, etc.).

I'll fix that - should also clean them up when it terminates

**Comment by rhc54** [comment]
@jsquyres Are you still seeing this problem with head of PRRTE/PMIx?
