### ISSUE TITLE
Deprecation warnings for deprecated cmd line options

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#411]
A host of deprecated cmd line options were identified for OMPI. These need to be supported for now but with a deprecation warning shown when used.

A list of to-be-included command line options (so we can track when they are done):

- [x] oversubscribe

**Comment by jjhursey** [comment]
Ref PR #409

**Comment by jjhursey** [comment]
Doc: https://github.com/open-mpi/ompi/wiki/Webex-affinity-discussions-2019-09#deprecated-options-that-likely-will-not-be-supported-in-prrte--open-mpi-v50

- [ ] `--oversubscribe`
- [ ] `--nooversubscribe`
- [ ] `--nolocal`
- [ ] `--use-hwthread-cpus`
- [ ] `--cpu-set` and `--cpu-list`
- [ ] `--bind-to-core`
- [ ] `--bind-to-socket`
- [ ] `--bynode`
- [ ] `--bycore`
- [ ] `--byslot`
- [ ] `--cpus-per-proc`
- [ ] `--cpus-per-rank`
- [ ] `--npernode` and `--pernode`
- [ ] `--npersocket`
- [ ] `--ppr`

**Comment by rhc54** [comment]
There are a bunch of others - I'll try to add them as I have time. FWIW: I'm working on a solution to the general problem of options (e.g., `--display-map`) that don't intersect with existing options (e.g., `--map-by`). It unearthed a bunch of other buglets, but I'm hoping to stomp them all out over the weekend.

**Comment by jjhursey** [comment]
Ok. I may push up my PR that lists the ones I know of. I've found a few places so far where the backend doesn't exist (or a least not in the same form) anymore. So more work is needed there too. For example `--map-by :NOOVERSUBSCRIBE` doesn't work, and `overload-allowed` doesn't seem to work either.

I need to remove `--nolocal` from that list, and it was not scheduled for deprecation, but is just missing from `prun`.

**Comment by rhc54** [comment]
`--nolocal` is moved to being a modifier to `--map-by`, so it is indeed deprecated.

I believe `overload-allowed` is supported by adding the `overload` modifier to the `--bind-to` option.

**Comment by rhc54** [comment]
IIRC, rationale behind not having `nooversubscribe` modifier was that it is the default, so you only need to tell us to allow oversubscription - makes no sense to tell us not to allow it. I can check to see if that is still the case.

**Comment by jjhursey** [comment]
PR #424 has a start on this. I mentioned some work still to do in that PR. I'll work on those next week.

A few more general notes from working on that PR:
 * There are a fair number of problems where the map/bin/rank of the prior job throws off the next job or become the defaults for the next job.
 * `--cpus-per-rank` issue
   - `--map-by :pe=X` works, and X becomes the default for the next job (even when not specified)
   - `--map-by core:pe=X` fails to map
 * `--nolocal` not implemented in the backend
 * `--use-hwthread-cpus`
   - Should we also set `--map-by hwthread`? Probably.
   - There is some investigation about intended behavior here


All of these CLI options are represented in that PR:
```
   -bind-to-core|--bind-to-core 
                         Bind processes to cores
   -bind-to-socket|--bind-to-socket 
                         Bind processes to sockets
   -bycore|--bycore      Whether to map and rank processes round-robin by
                         core
   -bynode|--bynode      Whether to map and rank processes round-robin by
                         node
   -byslot|--byslot      Whether to map and rank processes round-robin by
                         slot
   -cpu-list|--cpu-list <arg0>  
                         List of processor IDs to bind processes to
                         [default=NULL]
   -cpu-set|--cpu-set <arg0>  
                         Comma-separated list of ranges specifying logical
                         cpus allocated to this job [default: none]
   -cpus-per-proc|--cpus-per-proc <arg0>  
                         Number of cpus to use for each process [default=1]
   -cpus-per-rank|--cpus-per-rank <arg0>  
                         Synonym for cpus-per-proc
   -nolocal|--nolocal    Do not run any MPI applications on the local node
   -nooversubscribe|--nooversubscribe 
                         Nodes are not to be oversubscribed, even if the
                         system supports such operation
   -npernode|--npernode <arg0>  
                         Launch n processes per node on all allocated nodes
   -npersocket|--npersocket <arg0>  
                         Launch n processes per socket on all allocated
                         nodes
   -pernode|--pernode    Launch one process per available node
   --ppr <arg0>          Comma-separated list of number of processes on a
                         given resource type [default: none]
   -use-hwthread-cpus|--use-hwthread-cpus 
                         Use hardware threads as independent cpus
```

**Comment by rhc54** [comment]
The list here is now complete
