### ISSUE TITLE
Drop support for aggregated single char cmd line options

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#412]
No longer parse "-abc" as "-a -b -c" - instead treat it as "-abc"

This should be treated as a deprecated cmd line opion - warn and continue for now, reject in a later release

**Comment by markalle** [comment]
Where does this put cmdlines like "-mca var val"?  OMPI used to allow that, and I thought that syntax was going away so the parsing could be more standard where "-mca" would then become like saying "-m -c -a".

For commands like "ls" I like that, nobody wants to type "ls -l -a" for example.

But for mpirun we hardly have any single-char options, and even then "-n <number>" doesn't fit the mold.  So I agree with part of this, I don't think treating "-abc" as "-a -b -c" has any value in mpirun.  But if that decision is in place, then why not allow single dash in "-mca var val" etc?

**Comment by rhc54** [comment]
What it means is that we will treat "-abc" as a single cmd line option. If we recognize it, we will declare it as "deprecated" and continue for now. If we don't recognize it, then we will immediately error out with an "unknown option" error.

Deprecated options will be removed and treated as "unknown" in the next major release.

Bottom line: valid multi-char options must be preceded by double-dash.

**Comment by jjhursey** [comment]
I guess I have never tired. Does this work today?
I'm personally ok with getting rid of the aggregated single char options. We don't have that many of them to start with. And it confuses things when working on the deprecation patch.

I tried a couple of versions of `prun -vV hostname` and it does not seem to recognize the second short character option. So there is different behavior from `prun -vV hostname` and `prun -Vv hostname`. The former runs the program without printing the version, the latter just prints the version without running the program.

**Comment by rhc54** [comment]
No - it's why I put it as an issue. Still needs to be implemented

**Comment by markalle** [comment]
I'm fine with not supporting aggregation, I don't think it adds much value to mpirun/prun command lines.  But if we're not supporting aggregation then why deprecate the single dash options like -mca?  I think the only reason the double-dash convention exists is so you can be unambiguous when aggregated single-character options can be on the command line.

Eg you have to say --mca instead of -mca if -mca would be an aggregate of -m -c -a

I'll admit it's not hard to fix scripts if we do deprecate it.  But I'd bet that today -mca and all the other options get used with a single dash a lot

**Comment by rhc54** [comment]
It violates the Posix standard - see https://github.com/open-mpi/ompi/wiki/Webex-affinity-discussions-2019-09. You are welcome to argue it with them 😄

**Comment by rhc54** [comment]
Here is the warning:
```shell
$ prun -n 1 -mca schizo_base_verbose 1 hostname
--------------------------------------------------------------------------
WARNING: Multi-character cmd line options must be prefixed with double dashes,
not a single dash:

  Deprecated option:   -mca
  Corrected option:    --mca

We have updated this for you and will proceed. However, this will be treated
as an error in a future release. Please update your cmd line.
--------------------------------------------------------------------------
```
