### ISSUE TITLE
need to implement --display-allocation and other options that use to exist with orte

### ISSUE THREAD

**Issue by hppritcha** [openpmix/prrte#421]
We are trying to debug some problems we're seeing on a slurm cluster and prte not seeming to recognize our allocation.  In the course of trying to do this, noticed quite a few of the debug options available with the old orte aren't present.  Among these are

- display-allocation
- display-map
- debug-daemons

This list is probably not complete.

**Comment by jjhursey** [comment]
Mostly a duplicate of Issue #388 - we should combine these lists

**Comment by bosilca** [comment]
--display-topo
--do-not-launch

**Comment by rhc54** [comment]
These have all now been implemented and brought to OMPI in https://github.com/open-mpi/ompi/pull/7498
