### ISSUE TITLE
Occasional failures to rendezvous

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#448]
When running as a proxy, `prun` needs to spawn `prte` and then connect to it. We specify a rendezvous file for that purpose. However, every so often we see an error reported indicating that `prun` was unable to make the connection.

When it occurs, this tends to be in CI or MTT situations. I haven't been able to replicate it manually, so it could be something to do with lingering files or other "noise" in the system. Regardless, this rendezvous needs to be _very_ solid and so this bears some investigation.

**Comment by rhc54** [comment]
I may have addressed this with https://github.com/openpmix/prrte/pull/455 and https://github.com/openpmix/openpmix/pull/1676

**Comment by jjhursey** [comment]
Yeah I'm thinking the patch https://github.com/openpmix/openpmix/pull/1676/commits/f95ae80d1300838c7393955a166ac79577c6c204 probably got it. We can keep this open and watch CI to see if it stumbles again. Thanks!

**Comment by jjhursey** [comment]
We it another one with PR https://github.com/openpmix/openpmix/pull/1677 last night after the patch went in so maybe there is more work to do:
 * https://gist.github.com/ibm-ompi/719c2149c26653f882b023e44572fb69

I'll try to look into it today.

**Comment by rhc54** [comment]
I think that might be a different problem @jjhursey - it looks more like a hang and has a completely different signature. I'd check for a possible race condition between when the job-to-be-launched is submitted and cached vs the DVM being ready. Could be that the spawn request is getting cached but never processed.

**Comment by jjhursey** [comment]
With https://github.com/openpmix/prrte/pull/459 (using `prte` instead of `prun` for proxy launch) this issue might disappear. We can keep an eye on it.

**Comment by rhc54** [comment]
I think we are good now.
