### ISSUE TITLE
Need to update prun.1 manpage with CLI changes

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#450]

**Comment by jjhursey** [comment]
I'm working on a map/rank/bind manpage in PR #557 
It involves touching `prun.1` - so I'll try to tackle this at the same time.

**Comment by jjhursey** [comment]
Ref https://github.com/open-mpi/ompi/pull/8099

**Comment by abouteiller** [comment]
Issue #709 contains a bullet list of inconsistent behavior that relates to this issue discovered during a systematic testing of all mpiexec parameters.
