### ISSUE TITLE
Decide what to do about legacy ORTE MCA params.

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#483]
These probably need to be detected and converted to their PRRTE equivalent

**Comment by wckzhang** [comment]
Was the -N option something not converted over to prrte?

**Comment by rhc54** [comment]
I don't believe it was included in the original plan for conversion: https://github.com/open-mpi/ompi/wiki/Webex-affinity-discussions-2019-09

**Comment by jjhursey** [comment]
@wckzhang FYI: I have `-N` as a deprecated option in PRTE at the moment.
```
`-N <num>`

:   **(Deprecated: Use `--map-by prr:<num>:node`)**
    Launch `num` processes per node on all allocated nodes.
```
