### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by wckzhang** [openpmix/prrte#503]
Looks like the latest NUMA_RANK patches introduced an error:

```
prted/pmix/pmix_server_register_fns.c:505:43: error: 'PMIX_NUMA_RANK' undeclared (first use in this function); did you mean 'PMIX_NODE_RANK'?
                 PMIX_INFO_LOAD(&kv->info, PMIX_NUMA_RANK, &pptr->numa_rank, PMIX_UINT16);
```

**Comment by rhc54** [comment]
Are you using PMIx master? Or a v3.1.x version?

**Comment by rhc54** [comment]
If you are on OMPI master, then check that your pmix submodule actually updated.

**Comment by wckzhang** [comment]
Ah thanks I'll check

**Comment by wckzhang** [comment]
Closing issue, went away with git submodule update --recursive
