### ISSUE TITLE
oob tcp peer information

### ISSUE THREAD

**Issue by wckzhang** [openpmix/prrte#504]
I'm working on utilizing the prrte reachable framework. I'm currently lacking information that the prrte_oob_tcp_peer_t->addrs list does not contain (if_mask). Can you point to me how peers are sharing their information so I can properly add this information?

**Comment by rhc54** [comment]
It's a little complicated as it isn't in one place. If you look in src/mca/oob/tcp/oob_tcp_component.c, you will see where we obtain our available addresses (in component_available, beginning on line 456). We collect the address info to pass it back to the DVM master (who then broadcasts it) in component_get_addr (starting at line 698) - note that the address is constructed as a URI-like string.

When we get the URI's of our peers, the string is passed back to us in component_set_addr (starting at line 747).

We currently don't track the if_mask, so you would need to add that info somehow to the string and then parse it back out on the other end.

**Comment by wckzhang** [comment]
Ah got it, was there any reason we broadcast this information as a string instead of a struct (not sure if it's because of some API requirements)?

**Comment by rhc54** [comment]
The only reason is that we need to pass the connection information in two situations:

* the DVM master has to provide it to the daemons it launches so they can "phone home"

* when performing a tree-spawn pattern, each daemon has to pass it to the daemons it launches so they can "phone their parent"

Otherwise, the connection information passed back to the DVM by each daemon (and then broadcast back out) can be a binary blob. So if we can come up with something to pass on that cmd line for the initial connection, then the rest could be done as a blob.

**Comment by wckzhang** [comment]
Correct me if I'm wrong:

I think we're mangling the uri string - specifically the ports. It looks like this is a comma delimited list, and in component_set_addr, I tink we're treating it as a single item. For example, we directly pass it to parse_uri, in which it has the following line:

```
((struct sockaddr_in*) inaddr)->sin_port = htons(atoi(port)); 
```

I'm pretty sure that if there are multiple ports, this would break.

**Comment by rhc54** [comment]
Probably so. It has been a long time since I dug thru that code in any detail. I know it has gone thru multiple iterations, starting with a single port, then going multi-port, moving to multi-threaded, adding failover, and finally back to single port/single thread with no failover. So you may well be seeing inconsistencies in various parts of the code.

As far as I know, the code today only opens/uses a single port, which is why the parsing is fine at the moment. If you plan to extend that to multi-ports, then you would indeed have to revise the parsing.

**Comment by wckzhang** [comment]
As far as I can tell, in the "create_listen" function, if prrte_oob_tcp_component.tcp_static_ports or prrte_oob_tcp_component.tcp_dyn_ports are true with more than 1 port, the code will break. I'm guessing that people rarely if ever use these features which is why everything hasn't broken.

The code in the create_listen/create_listen6 function loops over the number of ports provided and adds them to a list, (prrte_oob_tcp_component.ipv4ports or prrte_oob_tcp_component.ipv6ports) This will then be turned into a comma delimited list in component_get_addr
```
tp = prrte_argv_join(prrte_oob_tcp_component.ipv4ports, ',');
```
When component_set_addr is called, we forget that this is a comma separated list and treat it as a single port. Seems like a bug to me hmm.

**Comment by rhc54** [comment]
I didn't say it wasn't a bug - I only explained that the code has morphed substantially over the years. The only time I have ever seen the ports specified (dyn or static) is when we specified a single port, not a range. Hence, bug or not, it has never been an issue. You are welcome to scrub it as desired 😄

**Comment by wckzhang** [comment]
I might add some sort of check temporarily so it at least tells the user what went wrong.

I'm having difficulties using the prtereachable framework - It looks like it's not getting initialized for some reason, do you have any idea why that is? (Was getting segfaults when I tried calling prrte_reachable_base_select...turns out that prrte_prtereachable_base_framework.framework_components is an empty list. I put a print in prrte_reachable_base_frame_open but I'm not seeing it before segfaulting.

Do you have any idea what's going on here?

**Comment by rhc54** [comment]
Yeah, I can fix that - just need to open the framework. I'll do that this evening.

If it would help, I can cleanup the oob code for you - wouldn't want that to become a stumbling block in your way, nor do I expect you to clean it all up.

**Comment by wckzhang** [comment]
It's alright, the oob stuff hasn't broken anyone yet...I'll fix it after I get the reachable patch up and running.

**Comment by rhc54** [comment]
https://github.com/openpmix/prrte/pull/507 should fix the initialization problem - once committed, you should be free to use the framework.

Let me know if there is anything else I can do to help.

**Comment by rhc54** [comment]
ok, you're good to go!

**Comment by wckzhang** [comment]
I finished the code with just a little bit more cleanup needed. Do you have any easy reproducers for some of the edge cases that the lack of reachability was causing (Want to make sure this patch is working/helps). I was planning on attaching multiple interfaces from different subnets to instances and seeing if it handles them correctly.

**Comment by rhc54** [comment]
> Do you have any easy reproducers for some of the edge cases

I'm afraid I don't - we just had users file problems where they had multiple NICs and the name of the NIC (e.g., eth0) was not consistently correlated with the same subnet across all nodes. So we couldn't just have them set `if_include=eth0` and have it work, and if we allowed all NICs to operate, then they wouldn't correctly select NICs that could reach each other.

**Comment by wckzhang** [comment]
Closing this issue, created a PR that adds missing peer information & uses it for the reachable component.
