### ISSUE TITLE
Possible standard incompatibility when registering a namespace.

### ISSUE THREAD

**Issue by artpol84** [openpmix/prrte#505]
According to the PMIx standart (v3.1 page 256, Figure 11.5 [[link](https://github.com/pmix/pmix-standard/releases/download/v3.1/pmix-standard-3.1.pdf)]):
![image](https://user-images.githubusercontent.com/7534910/78626984-2eb65800-7845-11ea-8794-8498df800518.png)

The key "PMIX_LOCAL_SIZE" should be located in the top level of the info array.

However, in PRRTE this is not the case. The key is packed as part of "PMIX_NODE_INFO_ARRAY" key [[link](https://github.com/openpmix/prrte/blob/master/src/prted/pmix/pmix_server_register_fns.c#L213)].

In the dstore v2.1, we rely on the info array to obtain the number of local processes [[link](https://github.com/openpmix/openpmix/blob/master/src/mca/common/dstore/dstore_base.c#L2411)]. And this causes ds21 to fail to initialize, so by default in OMPI master ds12 is selected.

**Comment by rhc54** [comment]
This is an error in the diagram, which was provided solely as an illustration of how info could be passed to "register_nspace". In truth, the "local size" is an attribute of the node, not the universe, as it differs across nodes. This is why it is included in the check for node-level info in PMIx_Get.

When we transfer information from the job cache to the dstore (upon connection from the first local client), we look for the node-level info of the local node. Those values are placed separately into the dstore so that a PMIx_Get of "local size" (for example) that doesn't include a specification for the node will return the value for the local node.

So the question is: is that piece of info not being correctly identified and separately stored when we transfer the info across to the dstore? PRRTE is doing the initial registration just fine - the issue may be in that PMIx transfer.

**Comment by rhc54** [comment]
> This is an error in the diagram

Actually, I should say that it isn't really an error in the diagram. One is allowed to pass the register_nspace info in the shown manner. PMIx is responsible for assuming that the node-level info outside of an info array refers to the local node by default.

Again, the diagram is an illustration and not intended to stipulate the _only_ way info can be passed. I believe the text tries to explain this, but perhaps not fully enough. Regardless, it is within the scope of the Standard for the local node-level info to be either contained in a node-info array, or to be outside of it.

**Comment by rhc54** [comment]
> In the dstore v2.1, we rely on the info array to obtain the number of local processes [link]. And this causes ds21 to fail to initialize, so by default in OMPI master ds12 is selected.

After sleeping on this, I confess I'm confused by this statement. The server initializes and selects all GDS components that can run. At some later point, it registers the nspace data for a job it is about to launch - this information is cached in the "hash" component as the server doesn't know what GDS component its local clients will select. When launching a local client, the server then passes in the environment the GDS components it has available.

The client then uses that envar to guide its own GDS component selection. It must use the "hash" for its own internal storage, but it can then choose which (if any) dstore component from the list of the ones the server has available it will use. It then communicates that selection back to the server, which in turn transfers the cached data to the specified GDS component for use by the client.

This is where I'm puzzled. At the time of GDS component selection in the client, there is no job-level information available to it. So how can the number of local processes influence the client's selection of GDS components and cause it to reject ds21?

**Comment by artpol84** [comment]
> This is where I'm puzzled. At the time of GDS component selection in the client, there is no job-level information available to it. So how can the number of local processes influence the client's selection of GDS components and cause it to reject ds21?

The logic I was describing happens on the server side at namespace register.

**Comment by artpol84** [comment]
> Again, the diagram is an illustration and not intended to stipulate the only way info can be passed.

What is the purpose of having multiple ways to describe the same thing? It seems to create a confusion without bringing anything useful.

**Comment by rhc54** [comment]
> The logic I was describing happens on the server side at namespace register.

This sounds like a bug in the ds21 selection logic, then - the server shouldn't be dictating what gds component the client will use. The client is supposed to make that determination. After all, the server cannot know what gds components are available to the client.

**Comment by artpol84** [comment]
This is not dictating.
In ds21 we need to know how many clients are going to be connected locally in order to prepare the corresponding number of locks.
If the server-side GDS doesn't know how many local clients will be connected, it is not able to properly initialize and thus fails to initialize.

**Comment by artpol84** [comment]
And this results in ds21 not being advertized to clients at all.

**Comment by rhc54** [comment]
If you need that info prior to the client contacting the server, then let's approach it a different way. We are explicitly told the number of local procs as a parameter to `PMIx_server_register_nspace` - it should be easy enough for us to pass that value explicitly in the `PMIX_GDS_ADD_NSPACE` macro, thus eliminating dependency on how data is registered.

**Comment by artpol84** [comment]
ok, I was thinking of doing that.
