### ISSUE TITLE
Add PRRTE to Spack

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#537]
@carsonwoods @adamjstewart

Not sure who is the right person(s) to contact about this, but the PMIx Reference RunTime Environment (PRRTE) is being picked up by folks like OpenHPC for general distribution. It is going to be the default RTE for OpenMPI starting with OMPI v5.0 in a couple of months, and it is seeing growing utilization by folks interested in high-thruput workflows.

Would it be possible to get it supported in Spack?

**Comment by adamjstewart** [comment]
PRs are always welcome 😄

**Comment by rhc54** [comment]
Oh my, this is rather embarrassing...I forgot that we already added it! Never mind...these aren't the droids we are seeking... 😄
