### ISSUE TITLE
PRRTE daemon has unexpectedly failed after launch when using multiple nodes (for indirect tool launch use case)

### ISSUE THREAD

**Issue by dirk-schubert-arm** [openpmix/prrte#540]
### What version of the PMIx Reference Server / PMIx are you using?

Latest master.

-----------------------------

## Details of the problem

Preparation:

```
# symlink mpirun to prte - for example with:
[mars] $ (cd $(dirname $(which prte)) && ln -s prte mpirun)
# queue allocation
[mars] $ salloc -N 1
```

NB: 
- The reproducer uses Slurm, maybe it also happens with a hostfile/SSH?
- The configuration: "mars" is the login/batch node, "node-1" is a compute node.

:heavy_check_mark: Expected behavior (as seen without mpir-shim):

```
[mars] $ mpirun -n 1 ./build/current/bin/hello
Hello from mpirun-mars33958.1:0 on node-1!
```

:exclamation: Actual Behavior (with mpir-shim):

```
[mars] $ mpir mpirun -n 1 ./build/current/bin/hello
--------------------------------------------------------------------------
An PRRTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
```

With additional debug logging using `PRRTE_MCA_plm_base_verbose=5`:

```
 [mars:34555] [[35540,1],0] plm:slurm: final top-level argv:
	srun --ntasks-per-node=1 --kill-on-bad-exit --ntasks=1 prted --prtemca ess "slurm" --prtemca ess_base_nspace "mpir.34552.1" --prtemca ess_base_vpid "1" --prtemca ess_base_num_procs "2" --prtemca prrte_hnp_uri "mpir.34552.1.0;tcp://10.1.122.151,192.168.0.1:56923:25,24"
[node-1:41882] Impossible to open the file /tmp/mpir.session.21058.34552/mpir.rndz.34552 in write mode
[node-1:41882] PMIX ERROR: PMIX_ERR_FILE_OPEN_FAILURE in file ptl_tcp_component.c at line 777
srun: error: node-1: task 0: Exited with exit code 213
srun: Terminating job step 9733.3
--------------------------------------------------------------------------
The PMIx server's listener thread failed to start. We cannot
continue.
--------------------------------------------------------------------------

--------------------------------------------------------------------------
It looks like prrte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during prrte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
PRRTE developer):

  pmix_server_init failed
  --> Returned value  (-43) instead of PRRTE_SUCCESS
--------------------------------------------------------------------------
[node-1:41882] PRRTE ERROR:  in file ess_slurm_module.c at line 79
[node-1:41882] PRRTE ERROR:  in file prted.c at line 426
--------------------------------------------------------------------------
```
An observation: mpirun is running on mars (login/batch node), so why would the rendezvous file be opened for writing on node-1 (compute node)? Maybe an environment variable is propagated which shouldn't?

Please note that I am reporting the bug against PRRTE, but it could also be a problem in PMIx or the MPIR-shim (although I can trigger the same bug independent of the MPIR-shim).

**Comment by dirk-schubert-arm** [comment]
@rhc54 : Can you have a look?

**Comment by rhc54** [comment]
Yeah, this is actually an issue with Slurm, in our opinion. They have `srun` forward the entire environment, which is what leads to quite a few problems (and not just this one). I'll have to unset all PMIX and PRRTE prefixed envars prior to calling `srun` to stop them from doing it.

**Comment by dirk-schubert-arm** [comment]
Thanks @rhc54.

With the fix I get this error:

```
[mars:37881] Error setting up application: TAKE-NEXT-OPTION
```
Any idea?

NB:
- This already happens in the single node case.
- `PRRTE_MCA_plm_base_verbose=5` does not produce any output.

**Comment by rhc54** [comment]
Is this still under a Slurm allocation?

**Comment by dirk-schubert-arm** [comment]
No, or it does not matter. I get the same error with and without Slurm. 

In fact I am getting the same error without the mpir-shim:

```
$ prte -n 1 $PWD/build/current/bin/hello # or mpirun
[mars:38901] Error setting up application: TAKE-NEXT-OPTION
```

Working with PRRTE cf8f7e61e2
Error with PRRTE 233c395d8d

It's possible I am doing something wrong, just don't know what ...

**Comment by rhc54** [comment]
Hmmm...it seems to be working for me. Of course, `prte -n 1 <app>` won't work and will return an error (not sure which one) as `prte` itself won't take an app as an argument. You can only get it to run an app if you use the `mpirun` symlink. I'm not seeing any trouble with PRRTE running as a DVM or with `mpirun`.

You might try deleting your install directory tree just to ensure you don't have any stale plugins laying around, and then re-installing. Do the same with the PMIx you are using, and ensure it also is at the tip of its master as well.

**Comment by dirk-schubert-arm** [comment]
Thanks, building with latest master of PMIx fixes `Error setting up application: TAKE-NEXT-OPTION`, but mpirun still doesn't launch the job inside Slurm:

```
PRRTE_MCA_plm_base_verbose=5 mpirun -n 1 hostname
[mars:01373] [[44078,0],0] plm:slurm: final top-level argv:
	srun --ntasks-per-node=1 --kill-on-bad-exit --ntasks=1 prted --prtemca ess "slurm" --prtemca ess_base_nspace "mpirun-mars1373" --prtemca ess_base_vpid "1" --prtemca ess_base_num_procs "2" --prtemca prrte_hnp_uri "mpirun-mars1373.0;tcp://10.1.122.151,192.168.0.1:45333:25,24"
srun: error: node-1: task 0: Exited with exit code 1
srun: Terminating job step 9756.0
--------------------------------------------------------------------------
An PRRTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. ...
--------------------------------------------------------------------------
```

When stripping the Slurm environment inside an allocation it works with SSH:

```
PRRTE_MCA_plm_base_verbose=5 mpirun --host node-1:1 -n 1 hostname
[mars:01484] [[56315,0],0] plm:rsh: final template argv:
	/usr/bin/ssh <template>        PATH=... .../bin/prted --prtemca ess "env" --prtemca ess_base_nspace "mpirun-mars1484" --prtemca ess_base_vpid "<template>" --prtemca ess_base_num_procs "2" --prtemca prrte_hnp_uri "mpirun-mars1484.0;tcp://10.1.122.151,192.168.0.1:49133:25,24" --prtemca plm "rsh" --tree-spawn --prtemca prrte_parent_uri "mpirun-mars1484.0;tcp://10.1.122.151,192.168.0.1:49133:25,24" --prtemca plm_base_verbose "5" --prtemca pmix_session_server "1" --prtemca prrte_base_help_aggregate "0"
[mars:01484] [[56315,0],0] complete_setup on job [56315,1]
[mars:01484] [[56315,0],0] plm:base:receive update proc state command from [[56315,0],1]
[mars:01484] [[56315,0],0] plm:base:receive got update_proc_state for job [56315,1]
node-1
[mars:01484] [[56315,0],0] plm:base:receive update proc state command from [[56315,0],1]
[mars:01484] [[56315,0],0] plm:base:receive got update_proc_state for job [56315,1]
```

Same behaviour with the mpir-shim in both case (Slurm not working, SSH working).

Any idea? Does mpirun inside Slurm work for you?

**Comment by rhc54** [comment]
let me take a look - i can borrow a friend's slurm box for a few minutes this morning

**Comment by rhc54** [comment]
okay, i can replicate the problem - looks like it has to do with a recent change in the encoding of the connection uri from the daemon to mpirun. will take me a bit to fix as this morning is rather busy, but i should get to it today.

**Comment by dirk-schubert-arm** [comment]
@rhc54: Thanks a lot (and great that you can reproduce)! 

Would you be able to quickly check with the MPIR-shim after your fix as well, and that the indirect launch works?

**Comment by dirk-schubert-arm** [comment]
Cheers @rhc54. Can confirm the issue is fixed.
