### ISSUE TITLE
PRRTE daemon exits in response to PMIx_tool_finalize()

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#545]
### What version of the PMIx Reference Server are you using?
git master @ f4d5bc8

##### What version of PMIx are you using?
git master @ a01e16a

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

A long-running job submitted to PRRTE is terminated early when a connecting tool calls PMIx_tool_finalize().

To reproduce using attached programs app.c and tool.c:
```shell
$ prte -n 1 ./app 60
```
Initializing and finalizing a tool in parallel with this before the job completes (within the time period on the above command line) results in the job / prte being terminated early:
```shell
$ ./tool
```
Expected behaviour:
```shell
$ prte -n 1 ./app 60
Hello
Bye
$
```
Actual behaviour:
```shell
$ prte -n 1 ./app 60
Hello
$
```
[app.c.txt](https://github.com/openpmix/prrte/files/4589484/app.c.txt)
[tool.c.txt](https://github.com/openpmix/prrte/files/4589486/tool.c.txt)

**Comment by david-edwards-arm** [comment]
Submitting a short-running job via prun can also be used instead of 'tool.c' to cause prte and the longer-running job to exit early

**Comment by rhc54** [comment]
Something is off here - `prte` itself should not allow you to run an application off of its cmd line. The `prte` command is solely for starting a DVM - when an application is included, it is supposed to exit with an error.

I can check that it is properly rejecting the stated use-case. I can then check about the tool connect/disconnect.

**Comment by david-edwards-arm** [comment]
@rhc54 thanks - the use case is mpirun sym-linked to prte

**Comment by rhc54** [comment]
Okay, thanks - that saves me chasing my tail! 😄
