### ISSUE TITLE
Diagnostic and error message output from prte must be forwarded to tools

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#556]
When PRRTE hits an error or needs to output diagnostic info (e.g., display a process/binding map), it currently just prints it to stdout or stderr. This won't work for systems where users may be using tools to start the jobs and are located remote from where the `prte` DVM master resides.

What we need to do is to redirect those output statements to flow thru the IOF and target them to the respective tool. For example, if I execute a `prun` from a window, I should get any output associated with the job spawned as a result of that `prun` cmd displayed on that window. It should be separated from any output resulting from a job started by a `prun` in a different window.

**Comment by jjhursey** [comment]
Notes from March 25, 2021 Teleconf:
 * This is likely going to be tricky to achieve but can happen in stages.
 * This might slip from v2.0.0

**Comment by rhc54** [comment]
Duplicate of #1326
