### ISSUE TITLE
--tune (ompi option) does not know the mca-param-sets directory

### ISSUE THREAD

**Issue by abouteiller** [openpmix/prrte#559]
When using `mpiexec --tune file` we get an error because `--tune` supports only absolute or relative paths, but does not account for the by-default directories in `opal_mca_param_base_file_path` (that should resolve to `$ompi-prefix/share/openmpi/amca-param-sets/`). 

Open MPI bug https://github.com/open-mpi/ompi/issues/7737 is possibly related. 

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Open MPI master 

## Details of the problem

```
 salloc -N 1 -Ccauchy  /home/bouteill/ompi/ulfm/ulfm2/debug.build/bin/mpiexec  -n 4  --tune ft-mpi  --omca mpi_show_mca_params env,file,api     02.err_handler
--------------------------------------------------------------------------
Unable to locate the variable file:
   ft-mpi
--------------------------------------------------------------------------

salloc -N 1 -Ccauchy  /home/bouteill/ompi/ulfm/ulfm2/debug.build/bin/mpiexec  -n 4  --tune /home/bouteill/ompi/ulfm/ulfm2/debug.build/share/openmpi/amca-param-sets/ft-mpi  --omca mpi_show_mca_params env,file,api  02.err_handler

(works as intended)
```

**Comment by rhc54** [comment]
That default path no longer exists as the amca parameters are no longer supported. There has been some discussion about providing a path for `tune` files, but that is sitting in a branch waiting for me to get back to it.
