### ISSUE TITLE
Errant "conflicting libevent" warning in configure

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#560]
Got this while configuring PRRTE from scratch this morning:
```text
configure: WARNING: ===================================================================
configure: WARNING: Conflicting libevent.so libraries detected on the system.
configure: WARNING: 
configure: WARNING: A system-installed Libevent library was detected and the PRRTE
configure: WARNING: build system chose to use the 'external' component expecting to
configure: WARNING: link against the Libevent in the linker search path.
configure: WARNING: LSF provides a libevent.so that is not from Libevent in its
configure: WARNING: library path. At this point the linker is attempting to resolve
configure: WARNING: Libevent symbols using the LSF library because of the lack of
configure: WARNING: an explicit linker path pointing to the system-installed Libevent.
configure: WARNING: 
configure: WARNING: To resolve this issue either (A) explicitly pass the Libevent
configure: WARNING: library path on the configure line (--with-libevent-libdir), or
configure: WARNING: (B) use the internal libevent by requesting it from configure 
configure: WARNING: with the --with-libevent=internal option.
configure: WARNING: ===================================================================
```
Note that PRRTE doesn't have an _internal_ libevent, and so we will always be using an external one. I explicitly point the configure at a particular version of libevent that I have installed in my home directory. I therefore assume this message is being emitted because there is also a system-installed version of libevent that includes `libevent.so`.

I'm wondering if it wouldn't be better to check `libevent.so` for some symbol that the LSF version includes so we can differentiate it more accurately? Having this appear just because there is a valid system version of libevent, but I choose to use a personal version, is annoying.

**Comment by rhc54** [comment]
Should note: I pass the `--with-libevent` flag, but not the `--with-libevent-dir` flag because the library is located in the correct place under the specified installation prefix. I don't believe I should have to further specify it.

If that proves impossible, and we cannot test for some LSF-specific function, then we at least need to correct the warning message. We should also `rpath-ify` the libevent linkage to ensure that we are indeed linked against the correct libevent version.

**Comment by jjhursey** [comment]
I'll take a look.

**Comment by rhc54** [comment]
At the least, we shouldn't perform this check unless LSF is detected on the system. I'm getting the output on my Mac, which definitely doesn't have LSF.
