### ISSUE TITLE
Fix heterogeneous node operations at WFU

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#570]
When we send topologies to backend nodes, the summary info doesn't get set properly. It is also likely that we are overwriting the daemon's own entry in the topology array. Probably need a better mechanism than sending topology indices to identify node-topology pairings - maybe use a hash of the signature?

**Comment by rhc54** [comment]
Correlates to https://github.com/open-mpi/ompi/issues/7660

**Comment by awlauria** [comment]
Time est: Easily a month for a dev not familiar with prrte.

**Comment by jjhursey** [comment]
Per teleconf on June 4, 2020:
 * The `--report-bindings` part of this should be complete now.
 * Ralph will push his WIP branch so that others can pick it up and finish off this effort, if they get a chance before he gets back to it.

**Comment by rhc54** [comment]
@jsquyres I believe this  has now been fixed with #808, which has been transferred to OMPI in https://github.com/open-mpi/ompi/pull/8558. If you still have contacts at WFU, can you perhaps have someone confirm?

**Comment by jjhursey** [comment]
We are waiting on Wake Forest University to confirm the fix before closing. If we don't hear anything before v2 is released then we may close and let them re-open if the issue persists.

**Comment by rhc54** [comment]
Let's close this for now - can always reopen if needed.

**Comment by jsquyres** [comment]
Just to close the loop on this: got confirmation from the folks at WFU -- the issue seems to be fixed; huzzah!
