### ISSUE TITLE
building prrte on 

### ISSUE THREAD

**Issue by roblatham00** [openpmix/prrte#583]
Thank you for taking the time to submit an issue!

## Background information

Unable to build prrte on Cray XC40

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

prrte-1.0

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

pmix-3.1.3

### Please describe the system on which you are running
 cat /etc/opt/cray/release/cle-release                                                                      
RELEASE=6.0.UP07
BUILD=6.0.7604
DATE=20200220
ARCH=noarch
NETWORK=ari
PATCHSET=42-202002201141

This is the Theta  Cray XC40 at Argonne

-----------------------------

## Details of the problem

When I configure and build prrte on this cray system, prrte finds some alps components and tries to build alps support but is unalble to.  Here are relevant lines from configure and build:

````
--- MCA component common:alps (m4 configuration macro)
checking for MCA component common:alps compile mode... static
checking for ALPS support cle level unknown... checking for CRAY_ALPSLLI... yes
checking for CRAY_ALPSUTIL... yes
checking for CRAY_ALPS... yes
checking for CRAY_WLM_DETECT... yes
opal_check_cray_alps_happy = yes
/tmp/robl/spack-stage/spack-stage-prrte-1.0.0-uvkepo4kfjufybqlvdf7re73ixcv2xbc/spack-src/configure: line 64731: CRAY_ALPSLLI_LIBS: command not found
/tmp/robl/spack-stage/spack-stage-prrte-1.0.0-uvkepo4kfjufybqlvdf7re73ixcv2xbc/spack-src/configure: line 64732: CRAY_ALPSUTIL_LIBS: command not found
checking if MCA component common:alps can compile... yes
````

despite the configure warnings (is there a missing .m4 file?) configure reports success.  building gets pretty far but stops here:

```
Making all in .
make[2]: Entering directory '/tmp/robl/spack-stage/spack-stage-prrte-1.0.0-uvkepo4kfjufybqlvdf7re73ixcv2xbc/spack-src/orte'
make[2]: *** No rule to make target 'mca/common/alps/libmca_common_alps.la', needed by 'libprteopen-rte.la'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/robl/spack-stage/spack-stage-prrte-1.0.0-uvkepo4kfjufybqlvdf7re73ixcv2xbc/spack-src/orte'
Makefile:1617: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/robl/spack-stage/spack-stage-prrte-1.0.0-uvkepo4kfjufybqlvdf7re73ixcv2xbc/spack-src/orte'
Makefile:896: recipe for target 'all-recursive' failed
```

**Comment by hppritcha** [comment]
I'll take a look at this.

**Comment by rhc54** [comment]
FWIW: keep in mind this is PRRTE v1.0 - which was "released" solely to meet the needs of an Intel early-on development team. I don't think it was ever actually deployed somewhere.

PRRTE v2.0 is a major code change and much more relevant to being used by someone.

**Comment by hppritcha** [comment]
I'm not seeing this problem using master.
```
PRTE configuration:
-----------------------
Version: 2.0.0a1
Debug build: no
Platform file: (none)

Required Packages
-----------------------
HWLOC: yes (/usr)
Libevent: yes (/home/howardp/libevent-2.1.8_install)
PMIx: yes (/home/howardp/prrte_install)
 
Resource Managers
-----------------------
Cray Alps: yes
Grid Engine: no
LSF: no
Slurm: yes
ssh/rsh: yes
Torque: no
 
External Packages
-----------------------
ZLIB: yes (standard)
 
Options
-----------------------
Manpages built: yes
 
howardp@thetalogin6:~/prrte> (master)
howardp@thetalogin6:~/prrte> (master)

```

**Comment by hppritcha** [comment]
@roblatham00 please try master.  Also note there's some work to be done to get OMPI master working okay with COBALT.  You can use master on the mom nodes, but it won't work on the compute nodes unless you manually generate a hostfile and feed it to mpirun.

**Comment by roblatham00** [comment]
I'm using pure pmi here. Trying to avoid an mpi dependency.  Will try
master.

**Comment by rhc54** [comment]
@roblatham00 There is no MPI dependency in PRRTE. I believe @hppritcha was referring to some recently reported issues with OMPI master (which has an embedded copy of PRRTE master in it) on Theta due to our lacking integrated support for Cobalt. However, PRRTE is building and running fine on Crays (both with Slurm and ALPS) - but it will probably require using the master version and not the out-of-date v1.0.0.

**Comment by roblatham00** [comment]
Confirmed that prrte master builds..  now I just have to figure out how to make it do something.   I'll close this issue.
