### ISSUE TITLE
update spack prrte defaults

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#591]
###  Background information

A recent ticket highlighted problem with `prrte@develop` version in spack.  It is using pmix-3.1.3 and should be updated to use pmix-3.1.5.   Note, checked and same issue exists for pmix-3.1.4.

Opening this ticket so I can track something in PRRTE repo.  Will update once I sync w/ spack upstream.

-----------------------------

## Details of the problem

The default version of spack's `prrte@develop` pulls pmix-3.1.3 and that has a problem when using prrte master b/c in some instances we pass `NULL` arg to `PMIX_LOAD_NSPACE()` that was not guarded in earlier version (fixed in pmix-3.1.5).

- spack package.py: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/prrte/package.py

**Comment by naughtont3** [comment]
I think this means we just need to update the pmix package in spack's develop tree to have the newer pmix-3.1.4 and pmix-3.1.5 in their recipe.
- https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/pmix/package.py

**Comment by rhc54** [comment]
Yeah, I'll add some protection in PRRTE for that situation - thx!
