### ISSUE TITLE
Document OpenPMIx version compatibility with PRRTE v2

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#595]
PRRTE v2 will require an OpenPMIx version of 3.1.1 or later. When using PRRTE with OpenPMIx v3.1.x the user might not get the full set of features versus running with OpenPMIx v4.x.

We should:
 * Setup CI to do a brief test with PRRTE v2 and the oldest supported OpenPMix to make sure we don't break those configurations (or update the docs when we do).
 * Add some documentation to the README about the feature matrix of PRRTE v2 vs OpenPMIx v3 or v4.

**Comment by gpaulsen** [comment]
Is this still true?  I thought that PRRTE v2 will require OpenPMIx v4.0 or later.

**Comment by rhc54** [comment]
We are trying to retain support for PMIx v3.x, but I'm becoming somewhat skeptical about it. We'll have to see just how much `#ifdef` crud we have to inject into the code base. If we can contain it and the feature loss isn't too great, then we'll support the older PMIx version.

**Comment by jjhursey** [comment]
Ref PR #848

**Comment by rhc54** [comment]
Configury now locks us to PMIx v4.1 or later, so we should be okay for now.
