### ISSUE TITLE
prun not propogating environment variables?

### ISSUE THREAD

**Issue by roblatham00** [openpmix/prrte#605]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

pmix@master

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

prrte@develop   -- both built from spack

### Please describe the system on which you are running

I added this to #371 a few days ago.  We can close this as a duplicate and discuss there if that makes more sense. 

I am on the ORNL  summit system
-----------------------------

## Details of the problem

LD_LIBRARY_PATH is not getting propagated to the hosts

- I start up the prrte daemons like this:
```shell
jsrun -r 1 hostname > hostfile
prte --pmixmca pmix_client_get_verbose 50 -x LD_LIBRARY_PATH --prefix $(spack location -i prrte) --hostfile hostfile -n 4  &
```
I won't paste the expected value for LD_LIBRARY_PATH  verbatim here but trust me it's long:  
```shell
$ echo $LD_LIBRARY_PATH | wc -c
3660
```

despite 25 years working in shell scripts I still get tripped up by escape rules so I just wrote a shell script that reports LD_LIBRARY_PATH to me:

```shell
$ cat libs.sh
#!/bin/sh
echo $LD_LIBRARY_PATH
```
The only member of LD_LIBRARY_PATH is the prefix:
```shell
$ prun -np 1 -x LD_LIBRARY_PATH ./libs.sh
/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel7-power9le/gcc-9.1.0/prrte-develop-bolcnur2trdqfs4hvdsjzrn6yd5it6uc/lib:
```

I see this if I pass -x, or not, or if i explicitly set -x e.g. `-x LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

**Comment by naughtont3** [comment]
@roblatham00 Yep would certainly look like it. I'll take a look again and check things.  Just new ticket, I'll use this to track things.

**Comment by naughtont3** [comment]
OK, this does appear to be a difference/regression of behavior from ORTE.  I did quick test to see how things behave in ompi-4.0.4 w/ `orterun` vs. prrte@master w/ `prterun` (easy combo single shot of prte+prun).

Briefly,
 - The contents of `LD_LIBRARY_PATH` is not propagated by default  in either `orterun` or `prterun`.
 - However, when passing `-x` explicitly to export a given env variable things differ: `orterun -x FOO` propogates `FOO`, but `prterun -x FOO` is not.

**Comment by rhc54** [comment]
> but prterun -x FOO is not.

Correct - the `-x` option is currently considered to be an OMPI-specific option. Thus, the `prte` schizo component does not process it. I've been considering whether we should redefine it to be a PRRTE option so `prun` and `prterun` will handle it.

If you feel it should be, then by all means move that code to the `prte` component.

**Comment by rhc54** [comment]
I should have noted - it is currently in the `ompi` component of schizo because there are defined conflicts between the use of `-x` and things like `--tuned` and `--mca`. So if we move it to `prte`, then we will also have to revise the handling of the precedence rules for those other options.

**Comment by rhc54** [comment]
For now, if you want to use `-x` with `prun` or `prterun`, just add `--personality ompi` to your cmd line.

**Comment by naughtont3** [comment]
OK, thanks for clarification Ralph.  This jogs loose details you mentioned previously.  Seems like above will let @roblatham00 get "unstuck", but also seems like I should better understand precedence rules before adding that to prte.  Thanks.

**Comment by roblatham00** [comment]
If '-x' is not supposed to work for prte, can prte not tell me about it? :smiley_cat:     What is the 'prrte way' to set up the enviroment for launched jobs?  Should I be constructing a custom `--personality` ?

**Comment by rhc54** [comment]
> If '-x' is not supposed to work for prte, can prte not tell me about it?

I'm actually surprised that it didn't - it should have error'd out with an "unknown option" response. I'll have to fix that.

> What is the 'prrte way' to set up the enviroment for launched jobs? Should I be constructing a custom --personality ?

No, the correct thing is for us to move `-x` over to the `prte` options. For now, just set the personality to `ompi` as a workaround.

**Comment by rhc54** [comment]
This has been fixed - the `prte` personality now supports the `-x` command line option.
