### ISSUE TITLE
Releasing items still in hash table during finalize

### ISSUE THREAD

**Issue by abouteiller** [openpmix/prrte#617]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

n/a

### Please describe the system on which you are running

Linux
-----------------------------

## Details of the problem

After an MPI job that had performed an MPI_Spawn, mpiexec, when compiled in debug mode, issues an assert.

Problem line is 

```c
#6  0x00007ffff7a79d78 in prte_finalize () at ../../../master/prrte/src/runtime/prte_finalize.c:79
79                  PRTE_RELEASE(jdata);
(gdb) list
74          PRTE_RELEASE(prte_cache);
75
76          /* release the job hash table */
77          PRTE_HASH_TABLE_FOREACH(key, uint32, jdata, prte_job_data) {
78              if (NULL != jdata) {
79                  PRTE_RELEASE(jdata);
80              }
81          }
82          PRTE_RELEASE(prte_job_data);
83
```

`PRTE_RELEASE(jdata)` calls the destructor on the list_item, however,  `jdata` is still at this point a member of `prte_job_data`, so it is incorrect to free the item as of yet. Note that calling remove from within a foreach is incorrect, so we can't escape easily.

The fix would be to use `hash_table_foreach` to chain the elements in a list, empty `prte_job_data` with `remove_all`, and only then pop the list items one by one from the list, and release them. Problem is that we need to create some intermediate list item container to store the `jdata` elements as their internal list-item is still in use during the foreach. This is very complicated to achieve something simple, is there a better way?

**Comment by rhc54** [comment]
Why not:
```diff
diff --git a/src/runtime/prte_finalize.c b/src/runtime/prte_finalize.c
index 0e87e9690f..08f73fe042 100644
--- a/src/runtime/prte_finalize.c
+++ b/src/runtime/prte_finalize.c
@@ -45,8 +45,9 @@
 int prte_finalize(void)
 {
     int rc;
-    uint32_t key;
-    prte_job_t *jdata;
+    uint32_t key, ky2;
+    prte_job_t *jdata, *j2;
+    void *ptr;
 
     --prte_initialized;
     if (0 != prte_initialized) {
@@ -74,9 +75,15 @@ int prte_finalize(void)
     PRTE_RELEASE(prte_cache);
 
     /* release the job hash table */
-    PRTE_HASH_TABLE_FOREACH(key, uint32, jdata, prte_job_data) {
+    ptr = NULL;
+    rc = prte_hash_table_get_next_key_uint32(prte_job_data, &key, (void**)&jdata, NULL, &ptr);
+    while (PRTE_SUCCESS == rc) {
         if (NULL != jdata) {
+            rc = prte_hash_table_get_next_key_uint32(prte_job_data, &ky2, (void**)&j2, ptr, &ptr);
+            prte_proc_table_remove_value(prte_job_data, key);
             PRTE_RELEASE(jdata);
+            key = ky2;
+            jdata = j2;
         }
     }
     PRTE_RELEASE(prte_job_data);
```

**Comment by rhc54** [comment]
Updated the proposed fix.
