### ISSUE TITLE
--bind-to affecting mapping

### ISSUE THREAD

**Issue by hjelmn** [openpmix/prrte#618]
Thank you for taking the time to submit an issue!

## Background information

Running multi-threaded one-sided performance tests with Open MPI master. Noticed unusual performance when running with --bind-to package.

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Running with Open MPI master with prrte hash 66c73f74cc4afd4ead5454771d98b5f199b7fe0e

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

openpmix/pmix@8283e81d1c0fd078e0f7fa85a383b633c328254b

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: Cray XC
* Network type: Aries

-----------------------------

## Details of the problem

When adding ```--bind-to package``` the mapping was not was expected. Example:

```
sn154:~/rma-mt/src hjelmn$ mpirun --bind-to package -n 2 -N 1 hostname
sn154.localdomain
sn154.localdomain
sn154:~/rma-mt/src hjelmn$ mpirun -n 2 -N 1 hostname
sn154.localdomain
sn200.localdomain
```

The output should have been the same both with and without the ```--bind-to``` option.

**Comment by rhc54** [comment]
This appears to have been fixed:
```text
$ prterun --bind-to package -n 2 -N 1 hostname
rhc-node01
rhc-node02
$ prterun -n 2 -N 1 hostname
rhc-node01
rhc-node02
$ 
```
