### ISSUE TITLE
error with test/double-put.c on summit

### ISSUE THREAD

**Issue by roblatham00** [openpmix/prrte#619]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

prrte@develop

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

pmix@master

### Please describe the system on which you are running

ORNL summit:

-----------------------------

## Details of the problem

I am running the `test/double-get.c` test from prrte .  it seems to behave ok for most cases, but I do see an error:

```shell
jsrun -r 1 hostname > hostfile
prte --prefix $(spack location -i prrte) --hostfile hostfile -N 1 &
sleep 10
prun -x LD_LIBRARY_PATH --personality ompi ./double-get --timeout
...
... (lots and lots of output omitted)
50: obtained data "SECOND TIME rank 0"
prte-batch261902.4:59 PMIx_get test-key-2 returned 256 bytes
59: obtained data "SECOND TIME rank 0"
prte-batch261902.4:69 PMIx_get test-key-2 returned 256 bytes
69: obtained data "SECOND TIME rank 0"
prte-batch261902.4:60 PMIx_get test-key-2 returned 256 bytes
60: obtained data "SECOND TIME rank 0"
prte-batch261902.4:64 PMIx_get test-key-2 returned 256 bytes
64: obtained data "SECOND TIME rank 0"
prte-batch261902.4:82 PMIx_get test-key-2 returned 256 bytes
82: obtained data "SECOND TIME rank 0"
Tue Jul  7 17:22:48 2020 ERROR: test/double-get.c:69  Client ns prte-batch274182.8 rank 0: PMIx_Get on rank 1 test-key-3: NOT-FOUND
```
Could you let me know if that is expected behavior?  Perhaps I am abusing PMIx/Prrte  if I have 96 processes doing this test?

**Comment by rhc54** [comment]
Gulp - that was intended to be run with just two ranks 😄 . I probably should have put a check in it to error out with more. I honestly have no idea what would happen with more than two, though it sounds like it gave a good old college try before collapsing!

**Comment by roblatham00** [comment]
OK, no problem, I can run this test with two ranks.  It still gives me a failure in the "timeout" case:

```shell
PMIx initialized
prte-batch597849.4:0 PMIx_Put on test-key-1
Execute fence
prte-batch597849.4:1 PMIx_Put on test-key-1
Execute fence
prte-batch597849.4:0 PMIx_Put on test-key-2
Wed Jul  8 17:17:35 2020 ERROR: test/double-get.c:69  Client ns prte-batch597849.4 rank 0: PMIx_Get on rank 1 test-key-3: NOT-FOUND

--------------------------------------------------------------------------
prte detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10300,4],0]
  Exit code:    1
--------------------------------------------------------------------------

```

I presume that is not supposed to happen?

**Comment by rhc54** [comment]
No, that's correct - the `PMIx_Get` call failed due to timeout, precisely as it should, thereby returning a "not-found" error instead of hanging forever.

**Comment by roblatham00** [comment]
If it's an expected error, the test should not return an error.  How do you automate testing?    I don't know the history of double-get.c so feel free to shred my proposed solution in  #620

**Comment by rhc54** [comment]
The codes in this directory aren't really "tests" in the way you might be thinking. Instead, they are just reproducers of problems that people have provided along the way and that I have found helpful when checking for things that creep into the system. We don't have a dedicated automated testing setup for PRRTE itself. We update the embedded version in OMPI every now and then, and utilize OMPI's rather extensive automated testing to exercise PRRTE. Errors found over there get reported over here.

Someday, it would be nice to have a more extensive testing system just for PRRTE - but that would require people to have time to build it, and that just doesn't seem likely any time soon.

I'll close the PR only because I don't really want that code to silently "succeed" - I want to see that it failed, and why.
