### ISSUE TITLE
prterun --map-by seq option does not recognize :OVERSUBSCRIBE keyword

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#670]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Master branch
### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

Master branch
### Please describe the system on which you are running

-    Operating system/version:
    RHEL 7.7

-    Computer hardware:

4 Power 8 nodes, 2 sockets each with 10 cores (20 total) and 8 hwthreads per core (160 total)

-    Network type:

Hostfile specifies 4 nodes, each with slots=320 keyword

### Details of the problem

I ran the command below, which failed as expected
```
prterun -n 320 --hostfile hostfile320 --map-by seq taskinfo
```
Then I ran the command below
```
prterun -n 320 --hostfile hostfile320 --map-by seq:OVERSUBSCRIBE taskinfo
```
This failed the same way with messages
```
A sequential map was requested, but not enough node entries
were given to support the requested number of processes:

  Num procs:  320
  Num nodes:  4

We cannot continue - please adjust either the number of processes
or provide more node locations in the file.
```
I expected this command to run to normal completion with no error messages

I tried this with a hostfile listing 4 nodes with 160 slots each and that also failed the same way

**Comment by rhc54** [comment]
I'm afraid that behavior is actually correct. The sequential mapper requires that you tell it the node upon which each rank is to be placed, in sequence from rank=0 to rank=N-1. In this case, you have asked for 320 procs, but you have only told the mapper the location for 4 of them - and the mapper has no idea where you want the other 316 placed.

You are welcome to update the help message if you think it could use additional clarification. However, the commands you provided should indeed fail.
