### ISSUE TITLE
prterun command with --map-by core and --bind-to hwthread options fails

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#671]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Master branch
### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

Master branch
### Please describe the system on which you are running

-    Operating system/version:
    RHEL 7.7

-    Computer hardware:

4 Power 8 nodes, 2 sockets each with 10 cores (20 total) and 8 hwthreads per core (160 total)

-    Network type:

Hostfile specifies 4 nodes, each with slots=8 keyword

### Details of the problem
I ran the command
```
prterun -n 8 --hostfile hostfile8 --map-by core --bind-to hwthread taskinfo
```
Where the hostfile lists 4 nodes with 8 slots each. The command fails with these messages
```

A request was made to bind to that would result in binding more
processes than cpus on a resource:

   Bind to:     HWTHREAD
   Node:        c712f6n01
   #processes:  1
   #cpus:       0

You can override this protection by adding the "overload-allowed"
option to your binding directive.
```
I added the :OVERLOAD-ALLOWED binding spec as stated
```
prterun -n 8 --hostfile hostfile8 --map-by core --bind-to hwthread:OVERLOAD-ALLOWED taskinfo
```
Then I got these messages
```

While computing bindings, we found no available cpus on
the following node:

  Node:  c712f6n01

Please check your allocation.
```
I expected at least the second case to complete successfully based on the first set of error messages

If I changed the **--map-by** option to **--map-by core:HWTCPUS** then both commands ran to successful completion.

**Comment by rhc54** [comment]
I don't have HTs on my Docker containers, but the command seems to run successfully there. Could you please recheck?

**Comment by drwootton** [comment]
I cloned new PMIx and PRRTE repositories today and rebuilt from those. I still see identical results today even with current source. Since all three issues you asked me to recheck are still failing the same way, I won't rule out that I did something wrong, but no idea what since a git clone followed by a git pull on the master branch says the code is up to date.

**Comment by rhc54** [comment]
See https://github.com/openpmix/prrte/issues/673#issuecomment-784399202 for an explanation. I'm implementing the check and error-out now.

**Comment by jjhursey** [comment]
I can confirm that PR #776 fixed the issue:
```
$ cat hostfile-8.txt 
c712f6n01 slots=8
c712f6n02 slots=8
c712f6n03 slots=8
$ prterun --np 8 --hostfile hostfile-8.txt --map-by core --bind-to hwthread:REPORT hostname
--------------------------------------------------------------------------
We cannot bind to hardware threads if we are not treating hardware
threads as independent CPUs since the lowest allocatable unit is
"core" by default. In order to bind to hardware threads, you must
therefore specify that we treat hardware threads as independent CPUs
by adding the "HWTCPUS" modifier to the "--map-by" directive.

The combination "--map-by core:hwtcpus --bind-to hwthread" or
"--map-by :hwtcpus --bind-to hwthread" will result in one process
being placed on each core, with the process bound to the first
hardware thread in that core.

In contrast, a case such as "--map-by package:hwtcpus --bind-to hwthread"
would result in each process being bound to successive hardware threads
on each package.
--------------------------------------------------------------------------

******* Cmd line: prterun --np 8 --hostfile hostfile-8.txt --map-by core --bind-to hwthread:REPORT hostname

$ prterun --np 8 --hostfile hostfile-8.txt --map-by core:hwtcpus --bind-to hwthread:REPORT hostname
[c712f6n01:84749] MCW rank 0 bound to package[0][hwt:0]
[c712f6n01:84749] MCW rank 1 bound to package[0][hwt:8]
[c712f6n01:84749] MCW rank 2 bound to package[0][hwt:16]
[c712f6n01:84749] MCW rank 3 bound to package[0][hwt:24]
[c712f6n01:84749] MCW rank 4 bound to package[0][hwt:32]
[c712f6n01:84749] MCW rank 5 bound to package[0][hwt:40]
[c712f6n01:84749] MCW rank 6 bound to package[0][hwt:48]
[c712f6n01:84749] MCW rank 7 bound to package[0][hwt:56]
c712f6n01
c712f6n01
c712f6n01
c712f6n01
c712f6n01
c712f6n01
c712f6n01
c712f6n01
```

8 processes each bound to the first hwthread on each core.
