### ISSUE TITLE
prterun --bind-to l1cache and --rank-by l1cache results in 'not supported' messages

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#676]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Master branch
### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

Master branch
### Please describe the system on which you are running

-    Operating system/version:
    RHEL 7.7

-    Computer hardware:

4 Power 8 nodes, 2 sockets each with 10 cores (20 total) and 8 hwthreads per core (160 total)

-    Network type:

Hostfile specifies 4 nodes, each with slots=16 keyword

### Details of the problem
I ran the command **prterun -n 20 --hostfile16 --bind-to l1cache --rank-by l1cache taskinfo** where the hostfile lists 4 nodes with 16 slots each, expecting normal completion.

The command failed with messages
```
[f8n07:10366] PRTE ERROR: Not supported in file base/rmaps_base_ranking.c at line 592
[f8n07:10366] PRTE ERROR: Not supported in file base/odls_base_default_fns.c at line 276
[f8n07:10366] PRTE ERROR: Not supported in file base/plm_base_launch_support.c at line 509
[f8n07:10366] FORCE TERMINATE ORDERED AT base/plm_base_launch_support.c:510 - error Unknown error(1)
```
This is also another case where there is a long wait after the messages are issued.

I tried **prterun -n 16 --hostfile hostfile16 --bind-to l1cache --rank-by l1cache taskinfo** and that failed the same way.

**Comment by rhc54** [comment]
Looks like this has been resolved - please reopen if you find otherwise.
