### ISSUE TITLE
prterun with --map-by core:PE=2 option fails, fewer CPUs available than requested

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#677]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Master branch
### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

Master branch
### Please describe the system on which you are running

-    Operating system/version:
    RHEL 7.7

-    Computer hardware:

4 Power 8 nodes, 2 sockets each with 10 cores (20 total) and 8 hwthreads per core (160 total)

-    Network type:

Hostfile specifies 4 nodes, each with slots=8 keyword

### Details of the problem
I ran the command **prterun -n 8 --hostfile hostfile8 --map-by core:PE=2 --bind-to:report** where the hostfile lists 4 nodes with 8 slots each, expecting normal completion since there are 20 cores on the node, 10 per package. The command failed with messages
```
A request for multiple cpus-per-proc was given, but a directive
was also given to map to an object level that has less cpus than
requested ones:

  #cpus-per-proc:  2
  number of cpus:  1
  map-by:          UNKNOWN

Please specify a mapping level that has more cpus, or else let us
define a default mapping that will allow multiple cpus-per-proc.
```
The message also reports map-by: UNKNOWN even though I specified **--map-by core**

If I add the **--bind-to core** option, I get the same error messages.

If I change the --map-by option to **--map-by :PE=2** or **--map-by package:PE=2** then the command completes normally.

**Comment by rhc54** [comment]
This is correct behavior. If you map-by core, then there is only one core "underneath" each process, so you cannot bind the process to two cores.
