### ISSUE TITLE
Unable to specify rankfile with prterun --map-by option

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#680]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Master branch
### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

Master branch
### Please describe the system on which you are running

-    Operating system/version:
    RHEL 7.7

-    Computer hardware:

4 Power 8 nodes, 2 sockets each with 10 cores (20 total) and 8 hwthreads per core (160 total)

-    Network type:

Hostfile specifies 4 nodes, each with slots=8 keyword

### Details of the problem
I tried to use a rankfile with prterun, where I ran the command **prterun -n 8 --hostfile hostfile8 --map-by rankfile taskinfo**

This failed with a message that the rankfile mapping policy was not recognized. **--map-by rf** and **--map-by rank_file** did not work either.

I looked at prrte code and did not see a way to specify rankfiles. I asked @jjhursey about this and he agreed that rankfile processing had been disabled.

**Comment by jjhursey** [comment]
We need to re-introduce the `--rankfile` command line option to prrte. I think this should be part of the general PRRTE personality (`schizo/prte`) not just ompi (`schizo/ompi`). The discussion from the Open MPI affinity is below:
 * https://github.com/open-mpi/ompi/wiki/Webex-affinity-discussions-2019-09#set-2---rankfile

Currently the `--mca prte_rankfile arf.txt` MCA option should work. So this might be as easy as connecting the `--rankfile` CLI option to that MCA parameter.

**Comment by jjhursey** [comment]
Per teleconf Jan. 14, 2021:
 * The `schizo/ompi` personality will need a `--rankfile` option per [this](https://github.com/open-mpi/ompi/wiki/Webex-affinity-discussions-2019-09#set-2---rankfile)
 * This should translate `--rankfile FILE` to `--map-by rankfile:FILE` where `rankfile` is the indicator and `FILE` is the path to the filename. The `--map-by rankfile:FILE` should be part of the `schizo/prte` core functionality (so `prun` users will use the `--map-by rankfile:FILE` on a per-job basis). This will be pushed to the `prte` server as a mapping directive.
 * The rankfile should be per-job. See issue #720
