### ISSUE TITLE
strcmp() in prte startup code causes SIGSEGV

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/prrte#705]
Thank you for taking the time to submit an issue!

## Background information

Latest version fails at startup with SIGSEGV

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

github master @ e6b8de5180696434fafc93df6280bbef7f8d574d

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

github master @ 318a75212aa5daed1ba97f57049b56afd26ef674

### Please describe the system on which you are running

* Operating system/version: CentOS 8
* Computer hardware: aarch64 (a64fx)
* Network type: IB

-----------------------------

## Details of the problem

```
$ prte -n 1 /bin/true
[fj-debug2:05569] *** Process received signal ***
[fj-debug2:05569] Signal: Segmentation fault (11)
[fj-debug2:05569] Signal code: Address not mapped (1)
[fj-debug2:05569] Failing at address: 0x10000
[fj-debug2:05569] [ 0] linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0x40000006066c]
[fj-debug2:05569] [ 1] /lib64/libc.so.6(strcmp+0x18)[0x40000084ba98]
[fj-debug2:05569] [ 2] /lustre/home/arcurtis/opt/prrte/git/lib/libprrte.so.2(+0x5a308)[0x4000000ca308]
[fj-debug2:05569] [ 3] /lib64/libevent_core-2.1.so.6(+0x1e620)[0x40000044e620]
[fj-debug2:05569] [ 4] /lib64/libevent_core-2.1.so.6(event_base_loop+0x530)[0x40000044f288]
[fj-debug2:05569] [ 5] prte[0x404bc8]
[fj-debug2:05569] [ 6] /lib64/libc.so.6(__libc_start_main+0xe4)[0x4000007f0be4]
[fj-debug2:05569] [ 7] prte[0x404d30]
[fj-debug2:05569] *** End of error message ***
Segmentation fault (core dumped)



$ gdb prte
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-11.el8
...
Reading symbols from prte...(no debugging symbols found)...done.
(gdb) r -n 1 /bin/true
Starting program: /lustre/home/arcurtis/opt/prrte/git/bin/prte -n 1 /bin/true
Missing separate debuginfos ...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x40000165f1e0 (LWP 5030)]
[New Thread 0x40000195f1e0 (LWP 5031)]
[New Thread 0x400001d0f1e0 (LWP 5032)]

Thread 1 "prte" received signal SIGSEGV, Segmentation fault.
0x000040000084ba98 in strcmp () from /lib64/libc.so.6
Missing separate debuginfos ...
(gdb) bt
#0  0x000040000084ba98 in strcmp () from /lib64/libc.so.6
#1  0x00004000000ca308 in interim ()
   from /lustre/home/arcurtis/opt/prrte/git/lib/libprrte.so.2
#2  0x000040000044e620 in event_process_active_single_queue ()
   from /lib64/libevent_core-2.1.so.6
#3  0x000040000044f288 in event_base_loop () from /lib64/libevent_core-2.1.so.6
#4  0x0000000000404bc8 in main ()
```

**Comment by rhc54** [comment]
I'm unable to replicate this. However, prte is not supposed to accept an application argument - it is solely for starting the DVM. I posted #706 to correct that issue - please see if it solves this problem.

**Comment by tonycurtis** [comment]
I'm confused.  You said (in email) that oshrun in OSHMEM just points to prte.  Was I just lucky for a while until something got tightened up?

Should I just symlink to a prterun if I find it?

**Comment by rhc54** [comment]
> Was I just lucky for a while until something got tightened up?

Afraid so

> Should I just symlink to a prterun if I find it?

Yes - I should have been more complete in my prior email. It is true that "oshrun" just symlinks to "prte". However, "prte" detects that it was invoked by a synonym and uses that to understand it should operate as a "one-shot" instead of a DVM. This is how we allow OMPI to dual-use that code base without modifying their "mpirun" cmd line.

My apologies for the confusion.

**Comment by tonycurtis** [comment]
OK, whatever works :). Thanks.

**Comment by tonycurtis** [comment]
Or can I pass --personality shmem to prterun reliabily?  Tests here seem to work...

**Comment by rhc54** [comment]
yes, that would be okay too

**Comment by tonycurtis** [comment]
Excellent, easiest change for me.  Thanks, closing.
