### ISSUE TITLE
Need more robust method for identifying prte proxy

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#765]
We currently assume that the OMPI personality should be used if the proxy for `prte` is `mpirun`, `mpiexec`, or `oshrun`. However, that is too generalized a method as other MPIs and OpenSHMEM implementations also use those commands, but with very different command line expectations.

@jsquyres and I discussed an alternative mechanism based on installation and parsing of .ini files. We need to document that here and then implement it prior to PRRTE v2.0 release.

**Comment by jjhursey** [comment]
For reference, this is currently determined in the `detect_proxy` function in `schizo_ompi.c` [here](https://github.com/openpmix/prrte/blob/ab4b1fc17409b3a8677d71851e3993e67cac650f/src/mca/schizo/ompi/schizo_ompi.c#L1208-L1226)

**Comment by rhc54** [comment]
The plan here is to define a standard location (`$prefix/etc`) where `.ini` files can be placed by 3rd-party packages such as OMPI and MPICH. The name of the file is based on the package: e.g., OMPI would install an `open-mpi.ini` or `ompi` file, while MPICH would install `mpich.ini`. Any number of packages can install files.

The content of the file would be the absolute paths of commands that are proxies for that package. For example, `ompi.ini` might contain:
```text
proxy: ompi
/opt/local/open-mpi/v3.1.0/bin/mpirun
/opt/local/open-mpi/v3.1.0/bin/mpiexec
/opt/local/open-mpi/v4.0.0/bin/mpirun
/opt/local/open-mpi/v4.0.0/bin/mpiexec

proxy: oshmem
/opt/local/open-mpi/v3.1.0/bin/oshmem
```
The 3rd party package is required to write their corresponding file, and so it should be relatively simple to put their prefix install location into these proxy strings.

PRRTE will determine the absolute path of its argv[0], and then scan the `.ini` files to determine a match. The "proxy" heading for that match indicates the schizo component that is to be used for that proxy.

This has the negative of requiring the 3rd party package to specify a PRRTE component to be used as its proxy. However, it allows them to ensure that their cmd line options and parsing meet their users expectations.

**Comment by rhc54** [comment]
Completed by series of commits ending in #827. Note that the .ini file for a specific personality no longer need be installed in the PRRTE location. For OMPI, the location is specified by the `OMPIHOME` envar that indicates where the OMPI installation resides. The OMPI .ini files are expected to be in the /etc subdirectory in that location.
