### ISSUE TITLE
--host X default number of slots

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#769]
Which is the expected default for the following command:
```
prterun --host node01 hostname
```

Should it:
 1. Launch 1 process on `node01`?
 2. Launch the number of processes equal to the number of cores on `node01`?

The current behavior is (1), but I found conflicting guidance in the man pages (which I'm cleaning up now) that imply both.

**Comment by rhc54** [comment]
It has been a constant argument over the years, and we have gone back/forth on behavior across releases. Some people say that `-host` is a filter that selects the host from within the allocation or hostfile, and thus that command should launch one proc/core. Others say it is indicating that they are allocating one slot to that host, and so the command should launch only one proc.

I added the `name:N` syntax to resolve the argument. `N` defaults to 1 if not given. So the correct answer is option 1.

**Comment by jjhursey** [comment]
Sounds good. That was my thinking too. I'll clean that up as I work on Issue #450
