### ISSUE TITLE
max_slots in hostfile

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#770]
I'm working on an example to show the behavior of `max_slots` in the hostfile.

We currently have documentation that looks like this:
```
Limits to oversubscription can also be specified in the hostfile itself:
% cat myhostfile
aa slots=4 max_slots=4
bb         max_slots=4
cc slots=4

The max_slots field specifies such a limit. When it does, the slots value defaults to the limit.

Now:

prterun --hostfile myhostfile --np 14 ./a.out

causes the first 12 processes to be launched as before, but the remaining two processes
will be forced onto node cc. The other two nodes are protected by the hostfile against
oversubscription by this job.
```

I note that this example throws an error because it would force oversubscription. So I added the `--map-by :OVERSUBSCRIBE` option
```
prterun --hostfile myhostfile --np 14 --map-by :OVERSUBSCRIBE ./a.out
```

In that case I got 6 processes on `aa`, 4 on `bb`, and 4 on `cc`. Which indicates that the max_slots is ignored in oversubscription. I tried the following hostfile and it yielded the same results:
```
c712f6n01 slots=4 max_slots=4
c712f6n02 slots=4 max_slots=4
c712f6n03 slots=4 max_slots=8
```

If the current behavior is the expected behavior then I need an example for the man page that shows how `max_slots` can be used. If the documented behavior is correct then we have a bug to fix.

**Comment by rhc54** [comment]
Yeah, that's a bug - max_slots should put a cap on oversubscription.

**Comment by jjhursey** [comment]
Fix in development: https://github.com/openpmix/prrte/pull/888

**Comment by jjhursey** [comment]
I am not able to keep pushing on this ticket. I added documentation on the PR:
 * https://github.com/openpmix/prrte/pull/888#issuecomment-818815571
