### ISSUE TITLE
Unexpected message with PMIx program in tight prun loop

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#787]
Occasionally we see the following error with the `cycle` test in CI:
```
20:30:29 [cffe4b8c5458:03719] UNEXPECTED MESSAGE tag = 39680 from source prte-3cd6154b28f4-346@0:9
20:30:29 --------------------------------------------------------------------------
20:30:29 A received msg header indicates a size that is too large:
20:30:29 
20:30:29   Requested size:  909194548
20:30:29   Size limit:      16777216
20:30:29 
20:30:29 If you believe this msg is legitimate, please increase the
20:30:29 max msg size via the ptl_base_max_msg_size parameter.
20:30:29 --------------------------------------------------------------------------
20:30:29 
```

The [cycle test](https://github.com/openpmix/pmix-tests/blob/663f174cea34b7dcdc66177f48893e2c1ddabe1d/prrte/cycle/run.sh#L85-L95) has a loop that runs `prun ./init_finalize_pmix` in a tight loop about 500 times against the same PRTE DVM. 

There is a bit of discussion about this [here](https://github.com/openpmix/prrte/pull/773#issuecomment-786764592).

**Comment by jjhursey** [comment]
Notes from March 25, 2021 Teleconf:
 * Ralph thinks that he has this fixed on a branch that he is working on.
 * General problem is that one side is sending some 'optional' data at the end of a handshake but the other side is not reading it letting it sit in the pipe. When the receiver tries to process the next message it gets what was left over confusing the unpacking code.

**Comment by awlauria** [comment]
Maybe this just needs re-testing?

**Comment by rhc54** [comment]
It actually gets tested with every PR since that cycle test runs in the CI. However, we haven't been seeing this problem for awhile now, so we may have "gotten" it. I'd say we can close it for now and reopen if we see the problem reappear.
