### ISSUE TITLE
PMIX_LAUNCH_COMPLETE event sent to wrong process when running indirect example

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#797]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
PRRTE master head

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
PMIx master head

### Please describe the system on which you are running

* Operating system/version:
RHEL 7.6

* Computer hardware:
Single Power 9 node 22 cores, 176 threads

* Network type:
localhost

-----------------------------

## Details of the problem

This is follow-on to PMIx issue openpmix/openpmix/#2084

Once I solved that problem, when I tried to run the indirect example as either **indirect prterun -n 2 hello 30** or **indirect prun -n 2 hello 30**, where the prun case had a prte system server running, both resulted in indirect looping indefinitely waitng for a PMIX_LAUNCH_COMPLETE event to be processed.

That appears to be caused by PRRTE code near line 610 of src/mca/plm/base/plm_base_launch_support.c.

The problem here appears to be that jdata->originator contains the namespace of the prterun process, not the tool (indirect) process. When I turn on PMIx client and server traces, it appears that the PMIX_LAUNCH_COMPLETE notification is sent to the prterun process.

I hacked plm_base_launch_support to specify the indirect process namespace as the target for the PMIx_Notify_event call and then the PMIX_LAUNCH_COMPLETE event is sent to the indirect process.

I'm not sure how to get the correct namespace to send the notification to.

While trying to track this down, I also noticed that jdata->nspace is set to  "(null)@1", maybe due to a sprintf call with NULL passed as one of the substitution parameters. I'm not sure if this is a problem, but it doesn't look right.

**Comment by rhc54** [comment]
The `PMIX_LAUNCH_COMPLETE` event is actually going to the correct place. The key here is that the intermediate launcher needs to relay that event to any tool connected to it. I thought I had that enabled, but I can take a look

**Comment by rhc54** [comment]
> I also noticed that jdata->nspace is set to "(null)@1",

Where did you see that, and which `jdata` had that problem? It definitely is a problem and needs to be tracked down.

**Comment by rhc54** [comment]
> > I also noticed that jdata->nspace is set to "(null)@1",
> 
> Where did you see that, and which `jdata` had that problem? It definitely is a problem and needs to be tracked down.

Never mind - I found the problem and fixed it
