### ISSUE TITLE
PMIX_LOCAL_PEERS setting seems incorrect

### ISSUE THREAD

**Issue by awlauria** [openpmix/prrte#863]
Checking `PMIX_LOCAL_PEERS` in ompi master, it doesn't seem quite right when running across more than one node.

For example, running 4 processes across 2 nodes, with 2 procs per node results in a `PMIX_LOCAL_PEERS` string of 
`0,1` for each rank. I would expect it to be the rank relative to the entire job/namespace.

This causes problems with `ompi_comm_split()` and company when splitting with `MPI_COMM_TYPE_SHARED`, as it will result in a communicator with procs not just on its local node.

**Comment by rhc54** [comment]
Yeah, this belongs over here - nothing to do with PMIx itself. I'll take a look

**Comment by awlauria** [comment]
Err..oops. Thanks, I thought this was openpmix, not prrte. My bad.

**Comment by rhc54** [comment]
No problem - it is hard to know which one to blame, but easy to shift

**Comment by rhc54** [comment]
Finally found it...

**Comment by awlauria** [comment]
This looks like it resolved the issue I was hitting. Thanks!
