### ISSUE TITLE
Multiple PRRTE DVMs launched from same node interfere with each other

### ISSUE THREAD

**Issue by acolinisi** [openpmix/prrte#864]
Thank you for taking the time to submit an issue!

## Background information

PRRTE a0de4af21b
PMIX 856d6d4d
OMPI 26c136ae59e2235b1187fd3d9897498860320d68

### Please describe the system on which you are running

* Operating system/version: Gentoo Prefix
* Computer hardware: OLCF Summit
-----------------------------

## Details of the problem

In two separate jobs submitted concurrently to LSF (with bsub): launch a DVM with `prte --daemonize`, then launch one job with `prun`.

Confirmed that the jobs always use node sets that do not overlap. However, multiple jobs may use the same "batch" node, i.e. the special entry node from which MPI applications are to be launched (via whatever launch mechanism, be it `jsrun` or PRRTE DVM).

If those two jobs end up using the same batch node, then I observe bizarre symptoms by which the `prun` instances fail. Instead of going into te very weird symptoms in detail, here's evidence for the hypothesis that the diverse failures are due to interference between the DVM instances.

As a confirmation, the same sets of jobs complete successfully if the LSF jobs are run in sequence, instead of concurrently.

Example: snippet from log of one job. Note the rankfile filename carefully. The filename reported in the log when the app is running differs from the filename passed in the argument to prun. The difference is not accidental: the wrong filename is actually the filename passed to another prun running against another DVM in another unrelated LSF job.

```
prun -n "692" --map-by "rankfile:FILE=dat/fd-26-prod-scratch-5/\
prun_mesh-4096_ranks-692_tpn-42_steps-25.rankfile\
:NOLOCAL:DISPLAY" ...
...
[batch2:98833] [prte-batch2-98833@0,0] rmaps:base set policy with \
rankfile:FILE=dat/fd-26-prod-scratch-5/\
prun_mesh-4096_ranks-346_tpn-42_steps-25.rankfile\
:NOLOCAL:DISPLAY
```

Could you please help debug by explaining how exactly does prun process communicate with the prte process (DVM)? Could shared memory be used and have some kind of concurrency bug? Where should I look in the code / log? Thank you.

**Comment by rhc54** [comment]
The problem is that `prun` can't automatically determine which DVM you want it to use. You need to give it a little help by telling it the `pid` of the DVM, or the namespace of it, or the URL. You can have `prte` output its pid (`--report-pid`) or its URL (`--report-url`):
```text
   --report-pid <arg0>               Printout pid on stdout [-], stderr [+], or a file [anything else]
   --report-uri <arg0>               Printout URI on stdout [-], stderr [+], or a file [anything else]
```
and then pass the result to `prun`:
```text
   --dvm-uri <arg0>                  Specify the URI of the DVM master, or the name of the file (specified as
                                     file:filename) that contains that info
   --pid <arg0>                      PID of the daemon to which we should connect
```

**Comment by acolinisi** [comment]
Ok, I updated my job makefiles to include the matching URI args, thank you. What a bad case of RTFM (although #869 is my fake excuse). But, might be worth keeping this issue open beyond the documentation.

The default behavior (perhaps unintentional) of choosing "some" DVM is deadly and really begs to be revised. When the wrong DVM is picked the failures are so weird, diverse, and non-deterministic (worst part) that it's not at all obvious that the issue has to do with DVMs (first suspect is application,  next suspect resource manager info reported or parsed, etc). It took an unspeakable amount of time and many failed large jobs and wasted core-hours until I could connect the dots into the DVM-interference hypothesis...

I haven't looked at the code, but if prun can somehow pick *a* DVM, then I hope it can tell that there are more than one. If it can, then the fix to this issue is simple: prun shoudl fail hard if number of DVMs detected is more than one and no selection argument is specified. If it can't tell whether there are more than one DVM, then I'd just make --dvi-uri required (more verbose CLI but better than current situation), or at least discuss if there's a way to add the missing functionality for this.

Btw, what does this do:
```
       --system-server
              Start the DVM as the system server
```

**Comment by rhc54** [comment]
I'll give it some thought - could be a middle ground in there somewhere. It isn't quite as random as you might think. There is a clear hierarchy of priorities detailed in the PMIx Standard, but once we fall thru the obvious (the system and session servers) we could look at adding some protection.

The `--system-server` option tells that invocation of `prte` that it should operate like the RM's local daemon - i.e., there can be only one on a node, and its rendezvous file is at the top of the hierarchy. Makes it very easy to find, but you cannot run multiple of them in parallel.

**Comment by rhc54** [comment]
Resolved this in https://github.com/openpmix/openpmix/pull/2141:
```text
If a tool finds multiple servers that it could connect to, then it
shall return an error indicating that the user must provide more
information so a specific server can be selected. Otherwise, it can
be a somewhat random selection. Multiple connection files are permitted,
but we check to see if all point to the same server. If not, then
report the ambibuity and ask for clarification.

```
