### ISSUE TITLE
PMIx "connect" isn't quite complete

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#876]
It doesn't execute a collective across the participants, nor does it result in all endpoint info being made available to each participant. Needs a grpcomm "fence" with collect data set to true.

I'm working on it now.

**Comment by jjhursey** [comment]
With the two PRs below is this now resolved?
 * v2.0: https://github.com/openpmix/prrte/pull/912
 * master: https://github.com/openpmix/prrte/pull/911

**Comment by rhc54** [comment]
Yep - forgot to close it.
