### ISSUE TITLE
Add a PMIx Event for "Ready for Debugger"

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#885]
When an application is launched under tool support it can be told to:
 * `PMIX_DEBUG_STOP_ON_EXEC` : Stop at the first instruction
 * `PMIX_DEBUG_STOP_IN_INIT` : Stop in `PMIx_Init`
 * `PMIX_DEBUG_WAITING_FOR_NOTIFY` : At some point in the application

The tool will then send the `PMIX_DEBUGGER_RELEASE` message to release the application processes from that holding location.

The problem is that there is currently no mechanism for the tool to know when all of the application processes have reached that holding location. There are probably ways to work around this, but the PMIx interface can help.

The solution is to:
 * Add a `PMIX_DEBUG_READY_FOR_RELEASE` event that the RM can post when all of the processes have reached the holding point.
 * Add the functionality to PRRTE in the `ready_for_debug` function [roughly here](https://github.com/openpmix/prrte/blob/7b08531ee0547cc81bd7a8cbcf88ad6b2404c0c5/src/mca/state/dvm/state_dvm.c#L416-L420)
 * Adjust the tool examples to:
   * Issue the `PMIX_DEBUGGER_RELEASE` from the `direct` or `indirect` main process (or from just one daemon) upon receipt of this new event.
   * Synchronize the daemon behavior around the new event and the release of the application processes. This is to simulate the daemons only attaching to the application processes once they have reached the hold point, and only releasing the application processes once all of the daemons have attached.

Notes:
 * This is really an OpenPMIx and PRRTE issue.
 * This new event should be added to the PMIx standard.
 * The examples can assume that we want all of the processes to stop at the holding location, not just some of them. Ideally PRRTE should be more flexible in its accounting.
 * Ref conversation [here](https://github.com/openpmix/prrte/pull/857#discussion_r600849033)

**Comment by rhc54** [comment]
Do you want me to tackle this while you are out?

**Comment by jjhursey** [comment]
If you have the cycles for it then go ahead. Otherwise, I'll work on it when it get back next week.
