### ISSUE TITLE
Cospawn for tools is not working

### ISSUE THREAD

**Issue by jjhursey** [openpmix/prrte#908]
Currently, there are two problems that we have found with co-spawn:
 1. The daemon processes and the application processes share the same namespace instead of creating two distinct namespaces. Cospawn should result in the same as 2 spawns (one for the application and one for the daemons), since it is just an optimization for that case.
 2. Since the daemons and the applications processes currently share the same namespace the "Ready for debug" event is never thrown since only a subset of the namespace has reached that point (namely the application).

I think solving 1 will also resolve 2, but we need to check both.

**Comment by rhc54** [comment]
This is more of a "nice-to-have" really, so adjusting labeling accordingly

**Comment by rhc54** [comment]
Doesn't look like anyone is going to do anything with this, so we can close it for now.
