### ISSUE TITLE
--display map and --display proctable are synonyms

### ISSUE THREAD

**Issue by abouteiller** [openpmix/prrte#920]
We currently have two options that have the exact same effect: `--display map` and `--display proctable`.

We should retain only one of the two. 

## Background information

0a346874 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #911 from rhc54/topic/dyn

**Comment by rhc54** [comment]
Nah, that's a bug - the proctable is something very specific and not equivalent of a "map". I suspect it was inadvertently set to "display-map" because someone wasn't familiar with the proctable format.

**Comment by abouteiller** [comment]
We also have a display map-devel option (should then this one be substituted to proctable?)

**Comment by rhc54** [comment]
No, it's another separate option:

* display-map is intended to be a short output aimed at users that just includes the hostname where each rank is placed
* display-devel-map is a longer output that includes locality, binding, and other info - aimed at PRRTE developers trying to debug mapping algorithms
* display-proctable is mainly used by debugger developers - it displays the "process table" defined by MPIR

You need all three as the target audiences are quite different.

**Comment by abouteiller** [comment]
I see, I'll undo the patch I was working on then

**Comment by abouteiller** [comment]
Issue resolved by removal in #938
