### ISSUE TITLE
Question regarding multiple READY-FOR-DEBUG notifications with multinode PRRTE example

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#944]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Built from latest master source

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Built from latest master source

### Please describe the system on which you are running

* Operating system/version:
RHEL 7.6

* Computer hardware:
Three Power 9 nodes, 20 cores/160 threads per node

* Network type:
Ethernet
-----------------------------

## Details of the problem

I run the current prrte/examples/debugger/indirect.c code on a single node, as **indirect prterun -n 2 hello 10** which launches 2 hello application tasks on the same (local) node. The indirect example registers with the prterun process to get the READY_FOR_DEBUG event notification and gets only one READY-FOR-DEBUG event as an indication that both application processes are ready.

I am working on a different indirect version which launches 8 hello application tasks, 4 per node, on 2 nodes which are different nodes than the node where indirect runs.

In this case, I get 8 READY-FOR-DEBUG events, one per application task.

I also tried this running 5 hello application tasks on the local node and three on a remote node, using a hostfile with 5 slots per node.

In this case, I got 6 READY-FOR-DEBUG events, which I'm guessing is the aggregation of the three tasks on the local node and individual events for each of the r tasks on the remote node.

I'm not sure whether this is a bug in my new indirect code, even though I am registering with the prterun process like the original case or if there is a problem with event aggregation with multiple nodes.

**Comment by drwootton** [comment]
Typo, got it backwards, above. I tried running 5 tasks on the remote node and 3 on the local node, which resulted in 6 READY-FOR-DEBUG events. If I reverse the hostfile to put 5 tasks on the local node and 3 on the remote, then I get 4 READY-FOR-DEBUG events

**Comment by rhc54** [comment]
The referenced PR fixes what you observed. There is still a libevent warning about an orphaned event that needs to be tracked down - if you have a chance and can do so, that would be helpful. Otherwise, we'll have to chase it down later.
