### ISSUE TITLE
prte_abort_delay and prte_abort_printstack have no effect 

### ISSUE THREAD

**Issue by abouteiller** [openpmix/prrte#963]
abort_delay and abort_printstack are useful to debug issues in prted itself. 

## Background information

The options prte_abort_delay and prte_abort_printstack have no effect: 

1. mpiexec --mca prte_abort_printstack true --mca prte_abort_delay 1000 --debug-daemons sleep 60000
2. kill a daemon with a signal (e.g., srun -wnode00 kill -SEGV prted)
3. the job aborts immediately and does not show a stacktrace

## Versions 

```
git submodule
 1191ca59e1d11331b6f36040ba81f64d911730eb 3rd-party/openpmix (v1.1.3-2974-g1191ca59)
+ce9855e0904df08f9a13ec0e0ebd705a862b021d 3rd-party/prrte (dev-31183-gce9855e0)
```

**Comment by rhc54** [comment]
Had to scratch my head and do a little searching. These params do not belong in PRRTE. They historically were defined in OPAL and then used in the MPI layer, never in ORTE itself. I see they are deprecated over there in OMPI v4.1 as well, so I have no idea when/where they were last implemented.

What you are looking for are:

* prted_debug_failure - specify the daemon rank you want to have fail.
* prted_debug_failure_delay - number of seconds the specified prted should stay alive before terminating

There is no equivalent to "hit me with a signal and abort after a delay", nor is there a way to get a stacktrace from the prted when it aborts. I'm not sure how you'd even do the latter. 😄

**Comment by abouteiller** [comment]
I am not looking at a failure injection tool (while that's cool on its own right), I am looking at a debugging tool for prted. What the OPAL equivalent does is 
1. opal_abort_delay -1 will keep the process stuck in the signal handler, with the intent that the user can then do `srun -wnode12 gdb -p $MPI_PROC_PID`
2. opal_abort_print_stack true will issue a `backtrace()` call in the signal handler

Both are designed to ease the debugging of OMPI applications;

~~~~~ 

Now the `prte_info` command reports the following options available. I expected they would do the same (that is, help debug PRTED); they should be removed from`prte_info` if they are actually not available, but they would be a great help when debugging PRTED crashes:

```
 bin/prte_info --param all all  | grep -C 3 abort
                MCA prte: parameter "prte_signal" (current value: "6,7,8,11", data source: default, level: 3 user/all, type: string)
                          Comma-delimited list of integer signal numbers to PRTE to attempt to intercept.  Upon receipt of the intercepted signal, PRTE will display a stack trace and abort.  PRTE will *not* replace signals if handlers are already installed by the time MPI_INIT is invoked.  Optionally append ":complain" to any signal number in the comma-delimited list to make PRTE complain if it detects another signal handler (and therefore does not insert its own).
                MCA prte: parameter "prte_stacktrace_output" (current value: "stderr", data source: default, level: 3 user/all, type: string)
                          Specifies where the stack trace output stream goes.  Accepts one of the following: none (disabled), stderr (default), stdout, file[:filename].   If 'filename' is not specified, a default filename of 'stacktrace' is used.  The 'filename' is appended with either '.PID' or '.RANK.PID', if RANK is available.  The 'filename' can be an absolute path or a relative path to the current working directory.
                MCA prte: parameter "prte_set_max_sys_limits" (current value: "", data source: default, level: 3 user/all, type: string)
                          Set the specified system-imposed limits to the specified value, including "unlimited".Supported params: core, filesize, maxmem, openfiles, stacksize, maxchildren
                MCA prte: parameter "prte_abort_delay" (current value: "0", data source: default, level: 5 tuner/detail, type: int)
                          If nonzero, print out an identifying message when abort operation is invoked (hostname, PID of the process that called abort) and delay for that many seconds before exiting (a negative delay value means to never abort).  This allows attaching of a debugger before quitting the job.
                MCA prte: parameter "prte_abort_print_stack" (current value: "false", data source: default, level: 5 tuner/detail, type: bool)
                          If nonzero, print out a stack trace when abort is invoked
                          Valid values: 0: f|false|disabled|no|n, 1: t|true|enabled|yes|y
```

**Comment by rhc54** [comment]
I removed the last two in that list as they are not implemented anywhere - they are stale carry-over cruft from OPAL that never applied to the ORTE layer. Likewise, one clue that `prte_signal` doesn't really exist is its explicit mention of _MPI_INIT_ in its description.

The way one typically debugs a `prted` crash is by examining its core file. PRRTE does trap a number of signals, however, for forwarding purposes. Those typically aren't the ones that cause the `prted` to segfault. If you want to try and extend that mechanism to implement what you describe, you are welcome to do so.

**Comment by abouteiller** [comment]
I see you already removed the unused ones, so this particular issue is now resolved. 

We'll need to check later what's the story with prte_signal and prte_stacktrace_output, but that's not an emergency.
